In [8]:
import pandas as pd
import json
import numpy as np
import polars as pl
import requests
import plotly.express as px
import time
import datetime
import sys
import os
import matplotlib
import http.client
import urllib.parse
import pickle
import httpx
import csv

from tqdm.notebook import tqdm_notebook as tqdm
from concurrent.futures import ThreadPoolExecutor, as_completed
from pprint import pprint
from io import StringIO
from functools import partial

from requests.adapters import ConnectionError, ReadTimeout, ReadTimeoutError
from urllib3.connection import NewConnectionError
from urllib3.util.retry import MaxRetryError


# Settings
pd.options.display.max_rows = 1_000
pd.options.display.max_columns = 100
pd.options.display.width = 20000
pd.set_option('display.float_format', lambda x: '%.4f' % x)
np.set_printoptions(suppress=True)
pl.Config.set_tbl_rows(100)

from IPython.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [9]:
def make_request(time_data: str, asset: str, request: str, params: dict):
    """

    :param time_data: at_time | hist | bulk_hist | list/...
    :param asset: stock | option | index
    :return: dict or raw csv
    """
    
    headers = {'Accept': "application/json"}
    url = f"http://127.0.0.1:25510/v2/{time_data}/{asset}/{request}".rstrip('/')

    success = False
    while not success:
        try:
            data = requests.get(url, headers=headers, params=params, timeout=60)
            if data.status_code == 474:
                if 'root' in params.keys():
                    print(params['root'])
                print("474 Connection lost to Theta Data. It's going to sleep to 5 sec")
                time.sleep(5)
            elif ('Next-page' not in data.headers) and (data.status_code != 472): 
                if 'root' in params.keys():
                    print(params['root'])
                print("Next-page' not in the data.headers or error in status code. It's going to sleep to 5 sec")
                print(data)
                print(data.url)
                print(data.status_code)
                print(data.content)
                time.sleep(5)
            else:
                success = True
        except (ConnectionError, NewConnectionError, MaxRetryError, ReadTimeout, ReadTimeoutError) as e:
            print(f"--------{params['root']}--------")
            print(e)
            time.sleep(5)
        except Exception as e:
            print(e)
            raise Exception
    try:
        if data.status_code == 471: 
            raise Exception(data.text)
        elif data.status_code == 472:
            return None, data.status_code
        elif data.status_code == 475:
            print(f"The server incorrect compile: {data.url}")
            return None, data.status_code
    
        if data.status_code != 200:
            print(params['root'], data.status_code, data.text)
    
        if ('use_csv' in list(params.keys())) and (params['use_csv'] == 'True'):
            if data.headers['Next-page'] != 'null':
                raise Exception(f"{params['root']} has an additional pages.")
                
            return data.content.decode('utf-8'), data.status_code
            
        else:
            return data.json(), data.status_code
    except Exception as e:
        print(e)
        print(url)
        print(params)
        raise Exception

# 04.2024 Theta Data

## Funcs

In [ ]:
# Get stock  EOD
# params = {
#     'root': 'AAPL', 
#     'start_date': '20240102', 
#     'end_date': '20240202'
# }
# make_request('hist', 'option', 'eod', params)

# Get all symbols
# params = {}
# ans = make_request('list/roots', 'index', '', params)

# Get all expiration
# params = {'root': 'AAPL'}
# ans = make_request('list/expirations', '', '', params)

# Get all strikes
params = {'root': 'AAPL', 'exp': '20171103'}
ans = make_request('list/strikes', '', '', params)

# Get all trade days
params = {'root': 'AAPL'}
ans = make_request('list/dates', 'stock', 'quote', params)

# Get all trade days
params = {'root': 'AAPL,SPY,AMD', 'start_date': '20230512'}
ans = make_request('list/contracts', 'option', 'trade', params)

# Get all contracts
params = {'root': 'AAPL,SPY', 'start_date': '20230512'}
ans = make_request('list/contracts', 'option', 'quote', params)

# pd.DataFrame(data=ans['response'], columns=ans['header']['format'])

## Get all tickers' expirations.

In [10]:
ans = make_request('list/roots', 'stock', '', {})
tickers_list = ans[0]['response']

In [11]:
def fetch_expiration(t):
    params = {'root': t}
    ans, status = make_request('list/expirations', '', '', params)
    if ans == None:
        return t, []
    else:
        return t, ans['response']
    

tickers_all_exp = {}
with ThreadPoolExecutor(max_workers=24) as executor:
    futures = {executor.submit(fetch_expiration, t): t for t in tickers_list}

    for future in tqdm(as_completed(futures), total=len(tickers_list)):
        t, response = future.result()
        tickers_all_exp[t] = response

tickers_all_exp = {t: {'expirations': values} for t, values in tickers_all_exp.items()}
tickers_all_exp = {t: values for t, values in tickers_all_exp.items() if len(values['expirations']) > 10}

""" Ошибки с ['ZWZZT', 'ZXIET', 'ZWRKW', 'ZYBT', 'ZY', 'ZZZ', 'ZYNE', 'ZXZZT', 'ZWS', 'ZYME', 'ZXYZ.A', 'ZYXI', 'ZZK']. Чтобы работало, надо:

elif ('Next-page' not in data.headers) and (data.status_code != 472): 
    if 'root' in params.keys():
        print(params['root'])
    print("Next-page' not in the data.headers or error in status code. It's going to sleep to 5 sec")
    print(data)
    print(data.url)
    print(data.status_code)
    print(data.content)
    time.sleep(5)

    return None, data.status_code
"""

  0%|          | 0/22696 [00:00<?, ?it/s]

' Ошибки с [\'ZWZZT\', \'ZXIET\', \'ZWRKW\', \'ZYBT\', \'ZY\', \'ZZZ\', \'ZYNE\', \'ZXZZT\', \'ZWS\', \'ZYME\', \'ZXYZ.A\', \'ZYXI\', \'ZZK\']. Чтобы работало, надо:\n\nelif (\'Next-page\' not in data.headers) and (data.status_code != 472): \n    if \'root\' in params.keys():\n        print(params[\'root\'])\n    print("Next-page\' not in the data.headers or error in status code. It\'s going to sleep to 5 sec")\n    print(data)\n    print(data.url)\n    print(data.status_code)\n    print(data.content)\n    time.sleep(5)\n\n    return None, data.status_code\n'

## Get all tickers' trade days

In [12]:
def trade_dates(t: str):
    params = {'root': t}
    ans, status = make_request('list/dates', 'stock', 'quote', params)
    if status == 472:
        return t, []
        
    trade_dates = pd.Series(ans['response']).astype(str).to_list()
    return t, trade_dates


with ThreadPoolExecutor(max_workers=24) as executor:
    futures = {executor.submit(trade_dates, t): t for t in tickers_all_exp.keys()}

    for future in tqdm(as_completed(futures), total=len(tickers_all_exp.keys())):
        t, response = future.result()
        tickers_all_exp[t]['trade_dates'] = response

tickers_all_exp = {t: values for t, values in tickers_all_exp.items() if len(values['trade_dates']) > 200}
with open('data/all_tickers_expir.pickle', 'wb') as f:
    pickle.dump(tickers_all_exp, f)

  0%|          | 0/8648 [00:00<?, ?it/s]

## Get tickers prices

In [ ]:
def get_stock_prices(t: str, trade_dates: list):
    months_list = pd.DataFrame(pd.to_datetime(trade_dates))
    months_list = months_list[months_list[0] >= '20160101']
    dates_start = months_list.groupby(months_list[0].dt.strftime('%Y%m')).min()[0].values
    dates_end = months_list.groupby(months_list[0].dt.strftime('%Y%m')).max()[0].values

    final_df = pl.DataFrame()
    for start, end in tqdm(zip(dates_start, dates_end)):   
        start = pd.Timestamp(start).strftime('%Y%m%d')
        end = pd.Timestamp(end).strftime('%Y%m%d')

        params = {'root': t, 'use_csv': 'True', 'start_date': start, 'end_date': end}
        ans, status = make_request('hist', 'stock', 'eod', params)
        if status == 472:
            print(f"{t} don't have data {start_date} - {end_date}")
            continue
        elif status == 475:
            continue
    
        cur_df = pl.read_csv(StringIO(ans))\
            .sort('date')\
            .with_columns(pl.lit(t).alias('ticker'))
        final_df = pl.concat([final_df, cur_df])

    return final_df


with open('data/all_tickers_expir.pickle', 'rb') as f:
    tickers_all_exp = pickle.load(f)

for core, folder, files in os.walk('data\stocks\daily'):
    already_files = set([f.split('_')[2] for f in files])
    
tickers_all_exp = {t: value for t, value in tickers_all_exp.items() if t not in already_files}
with ThreadPoolExecutor(max_workers=24) as executor:
    futures = {
        executor.submit(get_stock_prices, t, values['trade_dates']): 
        (t, values['trade_dates']) 
        for t, values in tickers_all_exp.items()
    }
    for future in tqdm(as_completed(futures), total=len(tickers_all_exp.keys())):
        cur_df = future.result()
        if (cur_df is None) or len(cur_df) == 0: 
            continue

        try:
            cur_df = cur_df.drop([
                    'bid_size', 'bid_exchange', 'bid', 'bid_condition',
                    'ask_size', 'ask_exchange', 'ask', 'ask_condition'
                ]).with_columns(pl.col('date').cast(pl.String).str.strptime(pl.Date, '%Y%m%d', strict=False))\
                .sort('date')\
                .with_columns(rol_50_vol=pl.col('volume').rolling_mean(window_size=50, min_periods=1))
            ticker = cur_df['ticker'].unique()[0]
            
            min_date = cur_df['date'].min().strftime('%Y%m%d')
            max_date = cur_df['date'].max().strftime('%Y%m%d')
            cur_df.write_parquet(f'data/stocks/daily/{min_date}_{max_date}_{ticker}_daily.parquet')
        except Exception as e:
            print(cur_df)
            print(e)
            raise Exception

## Get EOD options data

In [3]:
stocks_df = pl.read_parquet('data/20230601_stocks_data.parquet')\
    .with_columns(pl.col('date').cast(pl.String).str.to_date('%Y%m%d'))

need_tickers = stocks_df\
    .filter(pl.col('date') < datetime.date(2023, 7, 1))\
    .group_by('ticker').agg(pl.col('volume').mean(), pl.col('count').count())\
    .filter(pl.col('volume') > 500_000)\
    ['ticker'].to_list()

In [4]:
with open('data/all_tickers_expir.pickle', 'rb') as f:
    tickers_all_exp = pickle.load(f)

drop_tickers = [t for t in tickers_all_exp.keys() if t in set(need_tickers) and tickers_all_exp[t]['trade_dates'] == []]
for t in drop_tickers:
    del tickers_all_exp[t]

tickers_all_exp_filt = {t: tickers_all_exp[t] for t in tickers_all_exp.keys() if t in set(need_tickers)}

In [5]:
already_tickers = []
for root, direc, files in os.walk('data/options/'):
    for f in files:
        if f.endswith('.parquet') and '20210101' in f:
            f = f.split('_')[2]
            already_tickers.append(f)

for t in already_tickers:
    del tickers_all_exp_filt[t]

need_tickers = tickers_all_exp_filt.keys()

In [6]:
start_range = '20210101'
end_range = '20211231'

dates_start = pd.date_range(start_range, end_range, freq='MS').strftime('%Y%m%d')[::-1]
dates_end = pd.date_range(start_range, end_range, freq='ME').strftime('%Y%m%d')[::-1]
for t in tqdm(need_tickers, total=len(need_tickers)):
    cur_df = pl.DataFrame()
    
    start_time = time.time()
    for start_date, end_date in tqdm(zip(dates_start, dates_end)):
        params = {
            'root': t, 'exp': 0,
            'start_date': start_date, 'end_date': end_date,  
            'use_csv': 'True'
        }
        ans, status_code = make_request('bulk_hist', 'option', 'eod', params)
        if status_code == 472:
            print(f"\033[1;91m {t} {start_date} - {end_date} don't have data \033[0m")
            continue
        elif status_code == 572:
            print(f"\033[1;91m {t} an error \033[0m")
            continue

        ans_df = pl.read_csv(StringIO(ans)).with_columns(pl.lit(t).alias('ticker'))
        cur_df = pl.concat([cur_df, ans_df])

    print(t, round(time.time() - start_time, 2))
    if len(cur_df) == 0:
        continue

    cur_df = cur_df.sort('date', 'expiration', 'right', 'strike')
    cur_df.write_parquet(f'data/options/{start_range}_{end_range}_{t}_opts.parquet')

  0%|          | 0/1911 [00:00<?, ?it/s]

0it [00:00, ?it/s]

 AAC 20211201 - 20211231 don't have data
 AAC 20211101 - 20211130 don't have data
 AAC 20211001 - 20211031 don't have data
 AAC 20210901 - 20210930 don't have data
 AAC 20210801 - 20210831 don't have data
 AAC 20210701 - 20210731 don't have data
 AAC 20210601 - 20210630 don't have data
 AAC 20210501 - 20210531 don't have data
 AAC 20210401 - 20210430 don't have data
 AAC 20210301 - 20210331 don't have data
 AAC 20210201 - 20210228 don't have data
 AAC 20210101 - 20210131 don't have data
AAC 215.12

0it [00:00, ?it/s]

 ABCM 20211201 - 20211231 don't have data
 ABCM 20211101 - 20211130 don't have data
 ABCM 20211001 - 20211031 don't have data
 ABCM 20210901 - 20210930 don't have data
 ABCM 20210801 - 20210831 don't have data
 ABCM 20210701 - 20210731 don't have data
 ABCM 20210601 - 20210630 don't have data
 ABCM 20210501 - 20210531 don't have data
 ABCM 20210401 - 20210430 don't have data
 ABCM 20210301 - 20210331 don't have data
 ABCM 20210201 - 20210228 don't have data
 ABCM 20210101 - 20210131 don't have data
ABCM 215.66

0it [00:00, ?it/s]

 ABSI 20211201 - 20211231 don't have data
 ABSI 20211101 - 20211130 don't have data
 ABSI 20211001 - 20211031 don't have data
 ABSI 20210901 - 20210930 don't have data
 ABSI 20210801 - 20210831 don't have data
 ABSI 20210701 - 20210731 don't have data
 ABSI 20210601 - 20210630 don't have data
 ABSI 20210501 - 20210531 don't have data
 ABSI 20210401 - 20210430 don't have data
 ABSI 20210301 - 20210331 don't have data
 ABSI 20210201 - 20210228 don't have data
 ABSI 20210101 - 20210131 don't have data
ABSI 252.73

0it [00:00, ?it/s]

 ACDC 20211201 - 20211231 don't have data
 ACDC 20211101 - 20211130 don't have data
 ACDC 20211001 - 20211031 don't have data
 ACDC 20210901 - 20210930 don't have data
 ACDC 20210801 - 20210831 don't have data
 ACDC 20210701 - 20210731 don't have data
 ACDC 20210601 - 20210630 don't have data
 ACDC 20210501 - 20210531 don't have data
 ACDC 20210401 - 20210430 don't have data
 ACDC 20210301 - 20210331 don't have data
 ACDC 20210201 - 20210228 don't have data
 ACDC 20210101 - 20210131 don't have data
ACDC 272.82

0it [00:00, ?it/s]

 ACLX 20211201 - 20211231 don't have data
 ACLX 20211101 - 20211130 don't have data
 ACLX 20211001 - 20211031 don't have data
 ACLX 20210901 - 20210930 don't have data
 ACLX 20210801 - 20210831 don't have data
 ACLX 20210701 - 20210731 don't have data
 ACLX 20210601 - 20210630 don't have data
 ACLX 20210501 - 20210531 don't have data
 ACLX 20210401 - 20210430 don't have data
 ACLX 20210301 - 20210331 don't have data
 ACLX 20210201 - 20210228 don't have data
 ACLX 20210101 - 20210131 don't have data
ACLX 269.82

0it [00:00, ?it/s]

 ADEA 20211201 - 20211231 don't have data
 ADEA 20211101 - 20211130 don't have data
 ADEA 20211001 - 20211031 don't have data
 ADEA 20210901 - 20210930 don't have data
 ADEA 20210801 - 20210831 don't have data
 ADEA 20210701 - 20210731 don't have data
 ADEA 20210601 - 20210630 don't have data
 ADEA 20210501 - 20210531 don't have data
 ADEA 20210401 - 20210430 don't have data
 ADEA 20210301 - 20210331 don't have data
 ADEA 20210201 - 20210228 don't have data
 ADEA 20210101 - 20210131 don't have data
ADEA 266.03

0it [00:00, ?it/s]

 ADTH 20211201 - 20211231 don't have data
 ADTH 20211101 - 20211130 don't have data
 ADTH 20211001 - 20211031 don't have data
 ADTH 20210901 - 20210930 don't have data
 ADTH 20210801 - 20210831 don't have data
 ADTH 20210701 - 20210731 don't have data
 ADTH 20210601 - 20210630 don't have data
 ADTH 20210501 - 20210531 don't have data
 ADTH 20210401 - 20210430 don't have data
 ADTH 20210301 - 20210331 don't have data
 ADTH 20210201 - 20210228 don't have data
 ADTH 20210101 - 20210131 don't have data
ADTH 250.07

0it [00:00, ?it/s]

 AGRI 20211201 - 20211231 don't have data
 AGRI 20211101 - 20211130 don't have data
 AGRI 20211001 - 20211031 don't have data
 AGRI 20210901 - 20210930 don't have data
 AGRI 20210801 - 20210831 don't have data
 AGRI 20210701 - 20210731 don't have data
 AGRI 20210601 - 20210630 don't have data
 AGRI 20210501 - 20210531 don't have data
 AGRI 20210401 - 20210430 don't have data
 AGRI 20210301 - 20210331 don't have data
 AGRI 20210201 - 20210228 don't have data
 AGRI 20210101 - 20210131 don't have data
AGRI 215.2

0it [00:00, ?it/s]

 AKYA 20211201 - 20211231 don't have data
 AKYA 20211101 - 20211130 don't have data
 AKYA 20211001 - 20211031 don't have data
 AKYA 20210901 - 20210930 don't have data
 AKYA 20210801 - 20210831 don't have data
 AKYA 20210701 - 20210731 don't have data
 AKYA 20210601 - 20210630 don't have data
 AKYA 20210501 - 20210531 don't have data
 AKYA 20210401 - 20210430 don't have data
 AKYA 20210301 - 20210331 don't have data
 AKYA 20210201 - 20210228 don't have data
 AKYA 20210101 - 20210131 don't have data
AKYA 215.06

0it [00:00, ?it/s]

 AMLX 20211201 - 20211231 don't have data
 AMLX 20211101 - 20211130 don't have data
 AMLX 20211001 - 20211031 don't have data
 AMLX 20210901 - 20210930 don't have data
 AMLX 20210801 - 20210831 don't have data
 AMLX 20210701 - 20210731 don't have data
 AMLX 20210601 - 20210630 don't have data
 AMLX 20210501 - 20210531 don't have data
 AMLX 20210401 - 20210430 don't have data
 AMLX 20210301 - 20210331 don't have data
 AMLX 20210201 - 20210228 don't have data
 AMLX 20210101 - 20210131 don't have data
AMLX 215.74

0it [00:00, ?it/s]

 APE 20211201 - 20211231 don't have data
 APE 20211101 - 20211130 don't have data
 APE 20211001 - 20211031 don't have data
 APE 20210901 - 20210930 don't have data
 APE 20210801 - 20210831 don't have data
 APE 20210701 - 20210731 don't have data
 APE 20210601 - 20210630 don't have data
 APE 20210501 - 20210531 don't have data
 APE 20210401 - 20210430 don't have data
 APE 20210301 - 20210331 don't have data
 APE 20210201 - 20210228 don't have data
 APE 20210101 - 20210131 don't have data
APE 215.21

0it [00:00, ?it/s]

 APLD 20211201 - 20211231 don't have data
 APLD 20211101 - 20211130 don't have data
 APLD 20211001 - 20211031 don't have data
 APLD 20210901 - 20210930 don't have data
 APLD 20210801 - 20210831 don't have data
 APLD 20210701 - 20210731 don't have data
 APLD 20210601 - 20210630 don't have data
 APLD 20210501 - 20210531 don't have data
 APLD 20210401 - 20210430 don't have data
 APLD 20210301 - 20210331 don't have data
 APLD 20210201 - 20210228 don't have data
 APLD 20210101 - 20210131 don't have data
APLD 215.29

0it [00:00, ?it/s]

 ARHS 20211201 - 20211231 don't have data
 ARHS 20211101 - 20211130 don't have data
 ARHS 20211001 - 20211031 don't have data
 ARHS 20210901 - 20210930 don't have data
 ARHS 20210801 - 20210831 don't have data
 ARHS 20210701 - 20210731 don't have data
 ARHS 20210601 - 20210630 don't have data
 ARHS 20210501 - 20210531 don't have data
 ARHS 20210401 - 20210430 don't have data
 ARHS 20210301 - 20210331 don't have data
 ARHS 20210201 - 20210228 don't have data
 ARHS 20210101 - 20210131 don't have data
ARHS 215.34

0it [00:00, ?it/s]

 ASTI 20211201 - 20211231 don't have data
 ASTI 20211101 - 20211130 don't have data
 ASTI 20211001 - 20211031 don't have data
 ASTI 20210901 - 20210930 don't have data
 ASTI 20210801 - 20210831 don't have data
 ASTI 20210701 - 20210731 don't have data
 ASTI 20210601 - 20210630 don't have data
 ASTI 20210501 - 20210531 don't have data
 ASTI 20210401 - 20210430 don't have data
 ASTI 20210301 - 20210331 don't have data
 ASTI 20210201 - 20210228 don't have data
 ASTI 20210101 - 20210131 don't have data
ASTI 215.85

0it [00:00, ?it/s]

 ASTL 20211201 - 20211231 don't have data
 ASTL 20211101 - 20211130 don't have data
 ASTL 20211001 - 20211031 don't have data
 ASTL 20210901 - 20210930 don't have data
 ASTL 20210801 - 20210831 don't have data
 ASTL 20210701 - 20210731 don't have data
 ASTL 20210601 - 20210630 don't have data
 ASTL 20210501 - 20210531 don't have data
 ASTL 20210401 - 20210430 don't have data
 ASTL 20210301 - 20210331 don't have data
 ASTL 20210201 - 20210228 don't have data
 ASTL 20210101 - 20210131 don't have data
ASTL 244.0

0it [00:00, ?it/s]

 ATMU 20211201 - 20211231 don't have data
 ATMU 20211101 - 20211130 don't have data
 ATMU 20211001 - 20211031 don't have data
 ATMU 20210901 - 20210930 don't have data
 ATMU 20210801 - 20210831 don't have data
 ATMU 20210701 - 20210731 don't have data
 ATMU 20210601 - 20210630 don't have data
 ATMU 20210501 - 20210531 don't have data
 ATMU 20210401 - 20210430 don't have data
 ATMU 20210301 - 20210331 don't have data
 ATMU 20210201 - 20210228 don't have data
 ATMU 20210101 - 20210131 don't have data
ATMU 257.95

0it [00:00, ?it/s]

 BAK 20211201 - 20211231 don't have data
 BAK 20211101 - 20211130 don't have data
 BAK 20211001 - 20211031 don't have data
 BAK 20210901 - 20210930 don't have data
 BAK 20210801 - 20210831 don't have data
 BAK 20210701 - 20210731 don't have data
 BAK 20210601 - 20210630 don't have data
 BAK 20210501 - 20210531 don't have data
 BAK 20210401 - 20210430 don't have data
 BAK 20210301 - 20210331 don't have data
 BAK 20210201 - 20210228 don't have data
 BAK 20210101 - 20210131 don't have data
BAK 258.43

0it [00:00, ?it/s]

 BALL 20211201 - 20211231 don't have data
 BALL 20211101 - 20211130 don't have data
 BALL 20211001 - 20211031 don't have data
 BALL 20210901 - 20210930 don't have data
 BALL 20210801 - 20210831 don't have data
 BALL 20210701 - 20210731 don't have data
 BALL 20210601 - 20210630 don't have data
 BALL 20210501 - 20210531 don't have data
 BALL 20210401 - 20210430 don't have data
 BALL 20210301 - 20210331 don't have data
 BALL 20210201 - 20210228 don't have data
 BALL 20210101 - 20210131 don't have data
BALL 258.97

0it [00:00, ?it/s]

 BFH 20211201 - 20211231 don't have data
 BFH 20211101 - 20211130 don't have data
 BFH 20211001 - 20211031 don't have data
 BFH 20210901 - 20210930 don't have data
 BFH 20210801 - 20210831 don't have data
 BFH 20210701 - 20210731 don't have data
 BFH 20210601 - 20210630 don't have data
 BFH 20210501 - 20210531 don't have data
 BFH 20210401 - 20210430 don't have data
 BFH 20210301 - 20210331 don't have data
 BFH 20210201 - 20210228 don't have data
 BFH 20210101 - 20210131 don't have data
BFH 257.18

0it [00:00, ?it/s]

 BGXX 20211201 - 20211231 don't have data
 BGXX 20211101 - 20211130 don't have data
 BGXX 20211001 - 20211031 don't have data
 BGXX 20210901 - 20210930 don't have data
 BGXX 20210801 - 20210831 don't have data
 BGXX 20210701 - 20210731 don't have data
 BGXX 20210601 - 20210630 don't have data
 BGXX 20210501 - 20210531 don't have data
 BGXX 20210401 - 20210430 don't have data
 BGXX 20210301 - 20210331 don't have data
 BGXX 20210201 - 20210228 don't have data
 BGXX 20210101 - 20210131 don't have data
BGXX 258.51

0it [00:00, ?it/s]

 BIOL 20211201 - 20211231 don't have data
 BIOL 20211101 - 20211130 don't have data
 BIOL 20211001 - 20211031 don't have data
 BIOL 20210901 - 20210930 don't have data
 BIOL 20210801 - 20210831 don't have data
 BIOL 20210701 - 20210731 don't have data
 BIOL 20210601 - 20210630 don't have data
 BIOL 20210501 - 20210531 don't have data
 BIOL 20210401 - 20210430 don't have data
 BIOL 20210301 - 20210331 don't have data
 BIOL 20210201 - 20210228 don't have data
 BIOL 20210101 - 20210131 don't have data
BIOL 259.65

0it [00:00, ?it/s]

 BITI 20211201 - 20211231 don't have data
 BITI 20211101 - 20211130 don't have data
 BITI 20211001 - 20211031 don't have data
 BITI 20210901 - 20210930 don't have data
 BITI 20210801 - 20210831 don't have data
 BITI 20210701 - 20210731 don't have data
 BITI 20210601 - 20210630 don't have data
 BITI 20210501 - 20210531 don't have data
 BITI 20210401 - 20210430 don't have data
 BITI 20210301 - 20210331 don't have data
 BITI 20210201 - 20210228 don't have data
 BITI 20210101 - 20210131 don't have data
BITI 258.47

0it [00:00, ?it/s]

 BLPH 20211201 - 20211231 don't have data
 BLPH 20211101 - 20211130 don't have data
 BLPH 20211001 - 20211031 don't have data
 BLPH 20210901 - 20210930 don't have data
 BLPH 20210801 - 20210831 don't have data
 BLPH 20210701 - 20210731 don't have data
 BLPH 20210601 - 20210630 don't have data
 BLPH 20210501 - 20210531 don't have data
 BLPH 20210401 - 20210430 don't have data
 BLPH 20210301 - 20210331 don't have data
 BLPH 20210201 - 20210228 don't have data
 BLPH 20210101 - 20210131 don't have data
BLPH 259.03

0it [00:00, ?it/s]

 BMEA 20211201 - 20211231 don't have data
 BMEA 20211101 - 20211130 don't have data
 BMEA 20211001 - 20211031 don't have data
 BMEA 20210901 - 20210930 don't have data
 BMEA 20210801 - 20210831 don't have data
 BMEA 20210701 - 20210731 don't have data
 BMEA 20210601 - 20210630 don't have data
 BMEA 20210501 - 20210531 don't have data
 BMEA 20210401 - 20210430 don't have data
 BMEA 20210301 - 20210331 don't have data
 BMEA 20210201 - 20210228 don't have data
 BMEA 20210101 - 20210131 don't have data
BMEA 259.35

0it [00:00, ?it/s]

 BMR 20211201 - 20211231 don't have data
 BMR 20211101 - 20211130 don't have data
 BMR 20211001 - 20211031 don't have data
 BMR 20210901 - 20210930 don't have data
 BMR 20210801 - 20210831 don't have data
 BMR 20210701 - 20210731 don't have data
 BMR 20210601 - 20210630 don't have data
 BMR 20210501 - 20210531 don't have data
 BMR 20210401 - 20210430 don't have data
 BMR 20210301 - 20210331 don't have data
 BMR 20210201 - 20210228 don't have data
 BMR 20210101 - 20210131 don't have data
BMR 255.62

0it [00:00, ?it/s]

 BN 20211201 - 20211231 don't have data
 BN 20211101 - 20211130 don't have data
 BN 20211001 - 20211031 don't have data
 BN 20210901 - 20210930 don't have data
 BN 20210801 - 20210831 don't have data
 BN 20210701 - 20210731 don't have data
 BN 20210601 - 20210630 don't have data
 BN 20210501 - 20210531 don't have data
 BN 20210401 - 20210430 don't have data
 BN 20210301 - 20210331 don't have data
 BN 20210201 - 20210228 don't have data
 BN 20210101 - 20210131 don't have data
BN 251.78

0it [00:00, ?it/s]

 BNMV 20211201 - 20211231 don't have data
 BNMV 20211101 - 20211130 don't have data
 BNMV 20211001 - 20211031 don't have data
 BNMV 20210901 - 20210930 don't have data
 BNMV 20210801 - 20210831 don't have data
 BNMV 20210701 - 20210731 don't have data
 BNMV 20210601 - 20210630 don't have data
 BNMV 20210501 - 20210531 don't have data
 BNMV 20210401 - 20210430 don't have data
 BNMV 20210301 - 20210331 don't have data
 BNMV 20210201 - 20210228 don't have data
 BNMV 20210101 - 20210131 don't have data
BNMV 256.21

0it [00:00, ?it/s]

 BORR 20211201 - 20211231 don't have data
 BORR 20211101 - 20211130 don't have data
 BORR 20211001 - 20211031 don't have data
 BORR 20210901 - 20210930 don't have data
 BORR 20210801 - 20210831 don't have data
 BORR 20210701 - 20210731 don't have data
 BORR 20210601 - 20210630 don't have data
 BORR 20210501 - 20210531 don't have data
 BORR 20210401 - 20210430 don't have data
 BORR 20210301 - 20210331 don't have data
 BORR 20210201 - 20210228 don't have data
 BORR 20210101 - 20210131 don't have data
BORR 257.76

0it [00:00, ?it/s]

 BOWL 20211201 - 20211231 don't have data
 BOWL 20211101 - 20211130 don't have data
 BOWL 20211001 - 20211031 don't have data
 BOWL 20210901 - 20210930 don't have data
 BOWL 20210801 - 20210831 don't have data
 BOWL 20210701 - 20210731 don't have data
 BOWL 20210601 - 20210630 don't have data
 BOWL 20210501 - 20210531 don't have data
 BOWL 20210401 - 20210430 don't have data
 BOWL 20210301 - 20210331 don't have data
 BOWL 20210201 - 20210228 don't have data
 BOWL 20210101 - 20210131 don't have data
BOWL 258.49

0it [00:00, ?it/s]

 BRCC 20211201 - 20211231 don't have data
 BRCC 20211101 - 20211130 don't have data
 BRCC 20211001 - 20211031 don't have data
 BRCC 20210901 - 20210930 don't have data
 BRCC 20210801 - 20210831 don't have data
 BRCC 20210701 - 20210731 don't have data
 BRCC 20210601 - 20210630 don't have data
 BRCC 20210501 - 20210531 don't have data
 BRCC 20210401 - 20210430 don't have data
 BRCC 20210301 - 20210331 don't have data
 BRCC 20210201 - 20210228 don't have data
 BRCC 20210101 - 20210131 don't have data
BRCC 256.72

0it [00:00, ?it/s]

 BRZE 20211201 - 20211231 don't have data
 BRZE 20211101 - 20211130 don't have data
 BRZE 20211001 - 20211031 don't have data
 BRZE 20210901 - 20210930 don't have data
 BRZE 20210801 - 20210831 don't have data
 BRZE 20210701 - 20210731 don't have data
 BRZE 20210601 - 20210630 don't have data
 BRZE 20210501 - 20210531 don't have data
 BRZE 20210401 - 20210430 don't have data
 BRZE 20210301 - 20210331 don't have data
 BRZE 20210201 - 20210228 don't have data
 BRZE 20210101 - 20210131 don't have data
BRZE 256.01

0it [00:00, ?it/s]

 BTAL 20211201 - 20211231 don't have data
 BTAL 20211101 - 20211130 don't have data
 BTAL 20211001 - 20211031 don't have data
 BTAL 20210901 - 20210930 don't have data
 BTAL 20210801 - 20210831 don't have data
 BTAL 20210701 - 20210731 don't have data
 BTAL 20210601 - 20210630 don't have data
 BTAL 20210501 - 20210531 don't have data
 BTAL 20210401 - 20210430 don't have data
 BTAL 20210301 - 20210331 don't have data
 BTAL 20210201 - 20210228 don't have data
 BTAL 20210101 - 20210131 don't have data
BTAL 256.2

0it [00:00, ?it/s]

 BTE 20211201 - 20211231 don't have data
 BTE 20211101 - 20211130 don't have data
 BTE 20211001 - 20211031 don't have data
 BTE 20210901 - 20210930 don't have data
 BTE 20210801 - 20210831 don't have data
 BTE 20210701 - 20210731 don't have data
 BTE 20210601 - 20210630 don't have data
 BTE 20210501 - 20210531 don't have data
 BTE 20210401 - 20210430 don't have data
 BTE 20210301 - 20210331 don't have data
 BTE 20210201 - 20210228 don't have data
 BTE 20210101 - 20210131 don't have data
BTE 253.09

0it [00:00, ?it/s]

 BXSL 20211201 - 20211231 don't have data
 BXSL 20211101 - 20211130 don't have data
 BXSL 20211001 - 20211031 don't have data
 BXSL 20210901 - 20210930 don't have data
 BXSL 20210801 - 20210831 don't have data
 BXSL 20210701 - 20210731 don't have data
 BXSL 20210601 - 20210630 don't have data
 BXSL 20210501 - 20210531 don't have data
 BXSL 20210401 - 20210430 don't have data
 BXSL 20210301 - 20210331 don't have data
 BXSL 20210201 - 20210228 don't have data
 BXSL 20210101 - 20210131 don't have data
BXSL 258.55

0it [00:00, ?it/s]

 CAVA 20211201 - 20211231 don't have data
 CAVA 20211101 - 20211130 don't have data
 CAVA 20211001 - 20211031 don't have data
 CAVA 20210901 - 20210930 don't have data
 CAVA 20210801 - 20210831 don't have data
 CAVA 20210701 - 20210731 don't have data
 CAVA 20210601 - 20210630 don't have data
 CAVA 20210501 - 20210531 don't have data
 CAVA 20210401 - 20210430 don't have data
 CAVA 20210301 - 20210331 don't have data
 CAVA 20210201 - 20210228 don't have data
 CAVA 20210101 - 20210131 don't have data
CAVA 258.06

0it [00:00, ?it/s]

 CECO 20211201 - 20211231 don't have data
 CECO 20211101 - 20211130 don't have data
 CECO 20211001 - 20211031 don't have data
 CECO 20210901 - 20210930 don't have data
 CECO 20210801 - 20210831 don't have data
 CECO 20210701 - 20210731 don't have data
 CECO 20210601 - 20210630 don't have data
 CECO 20210501 - 20210531 don't have data
 CECO 20210401 - 20210430 don't have data
 CECO 20210301 - 20210331 don't have data
 CECO 20210201 - 20210228 don't have data
 CECO 20210101 - 20210131 don't have data
CECO 257.27

0it [00:00, ?it/s]

 CEG 20211201 - 20211231 don't have data
 CEG 20211101 - 20211130 don't have data
 CEG 20211001 - 20211031 don't have data
 CEG 20210901 - 20210930 don't have data
 CEG 20210801 - 20210831 don't have data
 CEG 20210701 - 20210731 don't have data
 CEG 20210601 - 20210630 don't have data
 CEG 20210501 - 20210531 don't have data
 CEG 20210401 - 20210430 don't have data
 CEG 20210301 - 20210331 don't have data
 CEG 20210201 - 20210228 don't have data
 CEG 20210101 - 20210131 don't have data
CEG 254.77

0it [00:00, ?it/s]

 CELL 20211201 - 20211231 don't have data
 CELL 20211101 - 20211130 don't have data
 CELL 20211001 - 20211031 don't have data
 CELL 20210901 - 20210930 don't have data
 CELL 20210801 - 20210831 don't have data
 CELL 20210701 - 20210731 don't have data
 CELL 20210601 - 20210630 don't have data
 CELL 20210501 - 20210531 don't have data
 CELL 20210401 - 20210430 don't have data
 CELL 20210301 - 20210331 don't have data
 CELL 20210201 - 20210228 don't have data
 CELL 20210101 - 20210131 don't have data
CELL 254.63

0it [00:00, ?it/s]

 CENN 20211201 - 20211231 don't have data
 CENN 20211101 - 20211130 don't have data
 CENN 20211001 - 20211031 don't have data
 CENN 20210901 - 20210930 don't have data
 CENN 20210801 - 20210831 don't have data
 CENN 20210701 - 20210731 don't have data
 CENN 20210601 - 20210630 don't have data
 CENN 20210501 - 20210531 don't have data
 CENN 20210401 - 20210430 don't have data
 CENN 20210301 - 20210331 don't have data
 CENN 20210201 - 20210228 don't have data
 CENN 20210101 - 20210131 don't have data
CENN 254.05

0it [00:00, ?it/s]

 CGDV 20211201 - 20211231 don't have data
 CGDV 20211101 - 20211130 don't have data
 CGDV 20211001 - 20211031 don't have data
 CGDV 20210901 - 20210930 don't have data
 CGDV 20210801 - 20210831 don't have data
 CGDV 20210701 - 20210731 don't have data
 CGDV 20210601 - 20210630 don't have data
 CGDV 20210501 - 20210531 don't have data
 CGDV 20210401 - 20210430 don't have data
 CGDV 20210301 - 20210331 don't have data
 CGDV 20210201 - 20210228 don't have data
 CGDV 20210101 - 20210131 don't have data
CGDV 253.49

0it [00:00, ?it/s]

 CGGR 20211201 - 20211231 don't have data
 CGGR 20211101 - 20211130 don't have data
 CGGR 20211001 - 20211031 don't have data
 CGGR 20210901 - 20210930 don't have data
 CGGR 20210801 - 20210831 don't have data
 CGGR 20210701 - 20210731 don't have data
 CGGR 20210601 - 20210630 don't have data
 CGGR 20210501 - 20210531 don't have data
 CGGR 20210401 - 20210430 don't have data
 CGGR 20210301 - 20210331 don't have data
 CGGR 20210201 - 20210228 don't have data
 CGGR 20210101 - 20210131 don't have data
CGGR 252.79

0it [00:00, ?it/s]

 CISO 20211201 - 20211231 don't have data
 CISO 20211101 - 20211130 don't have data
 CISO 20211001 - 20211031 don't have data
 CISO 20210901 - 20210930 don't have data
 CISO 20210801 - 20210831 don't have data
 CISO 20210701 - 20210731 don't have data
 CISO 20210601 - 20210630 don't have data
 CISO 20210501 - 20210531 don't have data
 CISO 20210401 - 20210430 don't have data
 CISO 20210301 - 20210331 don't have data
 CISO 20210201 - 20210228 don't have data
 CISO 20210101 - 20210131 don't have data
CISO 252.46

0it [00:00, ?it/s]

 CMAX 20211201 - 20211231 don't have data
 CMAX 20211101 - 20211130 don't have data
 CMAX 20211001 - 20211031 don't have data
 CMAX 20210901 - 20210930 don't have data
 CMAX 20210801 - 20210831 don't have data
 CMAX 20210701 - 20210731 don't have data
 CMAX 20210601 - 20210630 don't have data
 CMAX 20210501 - 20210531 don't have data
 CMAX 20210401 - 20210430 don't have data
 CMAX 20210301 - 20210331 don't have data
 CMAX 20210201 - 20210228 don't have data
 CMAX 20210101 - 20210131 don't have data
CMAX 253.13

0it [00:00, ?it/s]

 CRBG 20211201 - 20211231 don't have data
 CRBG 20211101 - 20211130 don't have data
 CRBG 20211001 - 20211031 don't have data
 CRBG 20210901 - 20210930 don't have data
 CRBG 20210801 - 20210831 don't have data
 CRBG 20210701 - 20210731 don't have data
 CRBG 20210601 - 20210630 don't have data
 CRBG 20210501 - 20210531 don't have data
 CRBG 20210401 - 20210430 don't have data
 CRBG 20210301 - 20210331 don't have data
 CRBG 20210201 - 20210228 don't have data
 CRBG 20210101 - 20210131 don't have data
CRBG 227.04

0it [00:00, ?it/s]

 CRDO 20211201 - 20211231 don't have data
 CRDO 20211101 - 20211130 don't have data
 CRDO 20211001 - 20211031 don't have data
 CRDO 20210901 - 20210930 don't have data
 CRDO 20210801 - 20210831 don't have data
 CRDO 20210701 - 20210731 don't have data
 CRDO 20210601 - 20210630 don't have data
 CRDO 20210501 - 20210531 don't have data
 CRDO 20210401 - 20210430 don't have data
 CRDO 20210301 - 20210331 don't have data
 CRDO 20210201 - 20210228 don't have data
 CRDO 20210101 - 20210131 don't have data
CRDO 215.56

0it [00:00, ?it/s]

 CTKB 20211201 - 20211231 don't have data
 CTKB 20211101 - 20211130 don't have data
 CTKB 20211001 - 20211031 don't have data
 CTKB 20210901 - 20210930 don't have data
 CTKB 20210801 - 20210831 don't have data
 CTKB 20210701 - 20210731 don't have data
 CTKB 20210601 - 20210630 don't have data
 CTKB 20210501 - 20210531 don't have data
 CTKB 20210401 - 20210430 don't have data
 CTKB 20210301 - 20210331 don't have data
 CTKB 20210201 - 20210228 don't have data
 CTKB 20210101 - 20210131 don't have data
CTKB 218.14

0it [00:00, ?it/s]

 CXAI 20211201 - 20211231 don't have data
 CXAI 20211101 - 20211130 don't have data
 CXAI 20211001 - 20211031 don't have data
 CXAI 20210901 - 20210930 don't have data
 CXAI 20210801 - 20210831 don't have data
 CXAI 20210701 - 20210731 don't have data
 CXAI 20210601 - 20210630 don't have data
 CXAI 20210501 - 20210531 don't have data
 CXAI 20210401 - 20210430 don't have data
 CXAI 20210301 - 20210331 don't have data
 CXAI 20210201 - 20210228 don't have data
 CXAI 20210101 - 20210131 don't have data
CXAI 215.89

0it [00:00, ?it/s]

 CYT 20211201 - 20211231 don't have data
 CYT 20211101 - 20211130 don't have data
 CYT 20211001 - 20211031 don't have data
 CYT 20210901 - 20210930 don't have data
 CYT 20210801 - 20210831 don't have data
 CYT 20210701 - 20210731 don't have data
 CYT 20210601 - 20210630 don't have data
 CYT 20210501 - 20210531 don't have data
 CYT 20210401 - 20210430 don't have data
 CYT 20210301 - 20210331 don't have data
 CYT 20210201 - 20210228 don't have data
 CYT 20210101 - 20210131 don't have data
CYT 220.59

0it [00:00, ?it/s]

 DAWN 20211201 - 20211231 don't have data
 DAWN 20211101 - 20211130 don't have data
 DAWN 20211001 - 20211031 don't have data
 DAWN 20210901 - 20210930 don't have data
 DAWN 20210801 - 20210831 don't have data
 DAWN 20210701 - 20210731 don't have data
 DAWN 20210601 - 20210630 don't have data
 DAWN 20210501 - 20210531 don't have data
 DAWN 20210401 - 20210430 don't have data
 DAWN 20210301 - 20210331 don't have data
 DAWN 20210201 - 20210228 don't have data
 DAWN 20210101 - 20210131 don't have data
DAWN 253.02

0it [00:00, ?it/s]

 DCFC 20211201 - 20211231 don't have data
 DCFC 20211101 - 20211130 don't have data
 DCFC 20211001 - 20211031 don't have data
 DCFC 20210901 - 20210930 don't have data
 DCFC 20210801 - 20210831 don't have data
 DCFC 20210701 - 20210731 don't have data
 DCFC 20210601 - 20210630 don't have data
 DCFC 20210501 - 20210531 don't have data
 DCFC 20210401 - 20210430 don't have data
 DCFC 20210301 - 20210331 don't have data
 DCFC 20210201 - 20210228 don't have data
 DCFC 20210101 - 20210131 don't have data
DCFC 254.02

0it [00:00, ?it/s]

 DCGO 20211201 - 20211231 don't have data
 DCGO 20211101 - 20211130 don't have data
 DCGO 20211001 - 20211031 don't have data
 DCGO 20210901 - 20210930 don't have data
 DCGO 20210801 - 20210831 don't have data
 DCGO 20210701 - 20210731 don't have data
 DCGO 20210601 - 20210630 don't have data
 DCGO 20210501 - 20210531 don't have data
 DCGO 20210401 - 20210430 don't have data
 DCGO 20210301 - 20210331 don't have data
 DCGO 20210201 - 20210228 don't have data
 DCGO 20210101 - 20210131 don't have data
DCGO 255.27

0it [00:00, ?it/s]

 DFIC 20211201 - 20211231 don't have data
 DFIC 20211101 - 20211130 don't have data
 DFIC 20211001 - 20211031 don't have data
 DFIC 20210901 - 20210930 don't have data
 DFIC 20210801 - 20210831 don't have data
 DFIC 20210701 - 20210731 don't have data
 DFIC 20210601 - 20210630 don't have data
 DFIC 20210501 - 20210531 don't have data
 DFIC 20210401 - 20210430 don't have data
 DFIC 20210301 - 20210331 don't have data
 DFIC 20210201 - 20210228 don't have data
 DFIC 20210101 - 20210131 don't have data
DFIC 254.75

0it [00:00, ?it/s]

 DFLI 20211201 - 20211231 don't have data
 DFLI 20211101 - 20211130 don't have data
 DFLI 20211001 - 20211031 don't have data
 DFLI 20210901 - 20210930 don't have data
 DFLI 20210801 - 20210831 don't have data
 DFLI 20210701 - 20210731 don't have data
 DFLI 20210601 - 20210630 don't have data
 DFLI 20210501 - 20210531 don't have data
 DFLI 20210401 - 20210430 don't have data
 DFLI 20210301 - 20210331 don't have data
 DFLI 20210201 - 20210228 don't have data
 DFLI 20210101 - 20210131 don't have data
DFLI 254.33

0it [00:00, ?it/s]

 DFIV 20211201 - 20211231 don't have data
 DFIV 20211101 - 20211130 don't have data
 DFIV 20211001 - 20211031 don't have data
 DFIV 20210901 - 20210930 don't have data
 DFIV 20210801 - 20210831 don't have data
 DFIV 20210701 - 20210731 don't have data
 DFIV 20210601 - 20210630 don't have data
 DFIV 20210501 - 20210531 don't have data
 DFIV 20210401 - 20210430 don't have data
 DFIV 20210301 - 20210331 don't have data
 DFIV 20210201 - 20210228 don't have data
 DFIV 20210101 - 20210131 don't have data
DFIV 252.75

0it [00:00, ?it/s]

 DICE 20211201 - 20211231 don't have data
 DICE 20211101 - 20211130 don't have data
 DICE 20211001 - 20211031 don't have data
 DICE 20210901 - 20210930 don't have data
 DICE 20210801 - 20210831 don't have data
 DICE 20210701 - 20210731 don't have data
 DICE 20210601 - 20210630 don't have data
 DICE 20210501 - 20210531 don't have data
 DICE 20210401 - 20210430 don't have data
 DICE 20210301 - 20210331 don't have data
 DICE 20210201 - 20210228 don't have data
 DICE 20210101 - 20210131 don't have data
DICE 251.97

0it [00:00, ?it/s]

 DINO 20211201 - 20211231 don't have data
 DINO 20211101 - 20211130 don't have data
 DINO 20211001 - 20211031 don't have data
 DINO 20210901 - 20210930 don't have data
 DINO 20210801 - 20210831 don't have data
 DINO 20210701 - 20210731 don't have data
 DINO 20210601 - 20210630 don't have data
 DINO 20210501 - 20210531 don't have data
 DINO 20210401 - 20210430 don't have data
 DINO 20210301 - 20210331 don't have data
 DINO 20210201 - 20210228 don't have data
 DINO 20210101 - 20210131 don't have data
DINO 252.11

0it [00:00, ?it/s]

 DO 20211201 - 20211231 don't have data
 DO 20211101 - 20211130 don't have data
 DO 20211001 - 20211031 don't have data
 DO 20210901 - 20210930 don't have data
 DO 20210801 - 20210831 don't have data
 DO 20210701 - 20210731 don't have data
 DO 20210601 - 20210630 don't have data
 DO 20210501 - 20210531 don't have data
 DO 20210401 - 20210430 don't have data
 DO 20210301 - 20210331 don't have data
 DO 20210201 - 20210228 don't have data
 DO 20210101 - 20210131 don't have data
DO 252.23

0it [00:00, ?it/s]

 DOUG 20211201 - 20211231 don't have data
 DOUG 20211101 - 20211130 don't have data
 DOUG 20211001 - 20211031 don't have data
 DOUG 20210901 - 20210930 don't have data
 DOUG 20210801 - 20210831 don't have data
 DOUG 20210701 - 20210731 don't have data
 DOUG 20210601 - 20210630 don't have data
 DOUG 20210501 - 20210531 don't have data
 DOUG 20210401 - 20210430 don't have data
 DOUG 20210301 - 20210331 don't have data
 DOUG 20210201 - 20210228 don't have data
 DOUG 20210101 - 20210131 don't have data
DOUG 222.86

0it [00:00, ?it/s]

 DRS 20211201 - 20211231 don't have data
 DRS 20211101 - 20211130 don't have data
 DRS 20211001 - 20211031 don't have data
 DRS 20210901 - 20210930 don't have data
 DRS 20210801 - 20210831 don't have data
 DRS 20210701 - 20210731 don't have data
 DRS 20210601 - 20210630 don't have data
 DRS 20210501 - 20210531 don't have data
 DRS 20210401 - 20210430 don't have data
 DRS 20210301 - 20210331 don't have data
 DRS 20210201 - 20210228 don't have data
 DRS 20210101 - 20210131 don't have data
DRS 243.95

0it [00:00, ?it/s]

 DSS 20211201 - 20211231 don't have data
 DSS 20211101 - 20211130 don't have data
 DSS 20211001 - 20211031 don't have data
 DSS 20210901 - 20210930 don't have data
 DSS 20210801 - 20210831 don't have data
 DSS 20210701 - 20210731 don't have data
 DSS 20210601 - 20210630 don't have data
 DSS 20210501 - 20210531 don't have data
 DSS 20210401 - 20210430 don't have data
 DSS 20210301 - 20210331 don't have data
 DSS 20210201 - 20210228 don't have data
 DSS 20210101 - 20210131 don't have data
DSS 254.22

0it [00:00, ?it/s]

 DTC 20211201 - 20211231 don't have data
 DTC 20211101 - 20211130 don't have data
 DTC 20211001 - 20211031 don't have data
 DTC 20210901 - 20210930 don't have data
 DTC 20210801 - 20210831 don't have data
 DTC 20210701 - 20210731 don't have data
 DTC 20210601 - 20210630 don't have data
 DTC 20210501 - 20210531 don't have data
 DTC 20210401 - 20210430 don't have data
 DTC 20210301 - 20210331 don't have data
 DTC 20210201 - 20210228 don't have data
 DTC 20210101 - 20210131 don't have data
DTC 254.98

0it [00:00, ?it/s]

 DUHP 20211201 - 20211231 don't have data
 DUHP 20211101 - 20211130 don't have data
 DUHP 20211001 - 20211031 don't have data
 DUHP 20210901 - 20210930 don't have data
 DUHP 20210801 - 20210831 don't have data
 DUHP 20210701 - 20210731 don't have data
 DUHP 20210601 - 20210630 don't have data
 DUHP 20210501 - 20210531 don't have data
 DUHP 20210401 - 20210430 don't have data
 DUHP 20210301 - 20210331 don't have data
 DUHP 20210201 - 20210228 don't have data
 DUHP 20210101 - 20210131 don't have data
DUHP 254.2

0it [00:00, ?it/s]

 EBET 20211201 - 20211231 don't have data
 EBET 20211101 - 20211130 don't have data
 EBET 20211001 - 20211031 don't have data
 EBET 20210901 - 20210930 don't have data
 EBET 20210801 - 20210831 don't have data
 EBET 20210701 - 20210731 don't have data
 EBET 20210601 - 20210630 don't have data
 EBET 20210501 - 20210531 don't have data
 EBET 20210401 - 20210430 don't have data
 EBET 20210301 - 20210331 don't have data
 EBET 20210201 - 20210228 don't have data
 EBET 20210101 - 20210131 don't have data
EBET 253.32

0it [00:00, ?it/s]

 EBR 20211201 - 20211231 don't have data
 EBR 20211101 - 20211130 don't have data
 EBR 20211001 - 20211031 don't have data
 EBR 20210901 - 20210930 don't have data
 EBR 20210801 - 20210831 don't have data
 EBR 20210701 - 20210731 don't have data
 EBR 20210601 - 20210630 don't have data
 EBR 20210501 - 20210531 don't have data
 EBR 20210401 - 20210430 don't have data
 EBR 20210301 - 20210331 don't have data
 EBR 20210201 - 20210228 don't have data
 EBR 20210101 - 20210131 don't have data
EBR 253.27

0it [00:00, ?it/s]

 EFTR 20211201 - 20211231 don't have data
 EFTR 20211101 - 20211130 don't have data
 EFTR 20211001 - 20211031 don't have data
 EFTR 20210901 - 20210930 don't have data
 EFTR 20210801 - 20210831 don't have data
 EFTR 20210701 - 20210731 don't have data
 EFTR 20210601 - 20210630 don't have data
 EFTR 20210501 - 20210531 don't have data
 EFTR 20210401 - 20210430 don't have data
 EFTR 20210301 - 20210331 don't have data
 EFTR 20210201 - 20210228 don't have data
 EFTR 20210101 - 20210131 don't have data
EFTR 252.45

0it [00:00, ?it/s]

 EGIO 20211201 - 20211231 don't have data
 EGIO 20211101 - 20211130 don't have data
 EGIO 20211001 - 20211031 don't have data
 EGIO 20210901 - 20210930 don't have data
 EGIO 20210801 - 20210831 don't have data
 EGIO 20210701 - 20210731 don't have data
 EGIO 20210601 - 20210630 don't have data
 EGIO 20210501 - 20210531 don't have data
 EGIO 20210401 - 20210430 don't have data
 EGIO 20210301 - 20210331 don't have data
 EGIO 20210201 - 20210228 don't have data
 EGIO 20210101 - 20210131 don't have data
EGIO 253.48

0it [00:00, ?it/s]

 EHAB 20211201 - 20211231 don't have data
 EHAB 20211101 - 20211130 don't have data
 EHAB 20211001 - 20211031 don't have data
 EHAB 20210901 - 20210930 don't have data
 EHAB 20210801 - 20210831 don't have data
 EHAB 20210701 - 20210731 don't have data
 EHAB 20210601 - 20210630 don't have data
 EHAB 20210501 - 20210531 don't have data
 EHAB 20210401 - 20210430 don't have data
 EHAB 20210301 - 20210331 don't have data
 EHAB 20210201 - 20210228 don't have data
 EHAB 20210101 - 20210131 don't have data
EHAB 252.86

0it [00:00, ?it/s]

 ELEV 20211201 - 20211231 don't have data
 ELEV 20211101 - 20211130 don't have data
 ELEV 20211001 - 20211031 don't have data
 ELEV 20210901 - 20210930 don't have data
 ELEV 20210801 - 20210831 don't have data
 ELEV 20210701 - 20210731 don't have data
 ELEV 20210601 - 20210630 don't have data
 ELEV 20210501 - 20210531 don't have data
 ELEV 20210401 - 20210430 don't have data
 ELEV 20210301 - 20210331 don't have data
 ELEV 20210201 - 20210228 don't have data
 ELEV 20210101 - 20210131 don't have data
ELEV 250.82

0it [00:00, ?it/s]

 ELME 20211201 - 20211231 don't have data
 ELME 20211101 - 20211130 don't have data
 ELME 20211001 - 20211031 don't have data
 ELME 20210901 - 20210930 don't have data
 ELME 20210801 - 20210831 don't have data
 ELME 20210701 - 20210731 don't have data
 ELME 20210601 - 20210630 don't have data
 ELME 20210501 - 20210531 don't have data
 ELME 20210401 - 20210430 don't have data
 ELME 20210301 - 20210331 don't have data
 ELME 20210201 - 20210228 don't have data
 ELME 20210101 - 20210131 don't have data
ELME 217.13

0it [00:00, ?it/s]

 ELV 20211201 - 20211231 don't have data
 ELV 20211101 - 20211130 don't have data
 ELV 20211001 - 20211031 don't have data
 ELV 20210901 - 20210930 don't have data
 ELV 20210801 - 20210831 don't have data
 ELV 20210701 - 20210731 don't have data
 ELV 20210601 - 20210630 don't have data
 ELV 20210501 - 20210531 don't have data
 ELV 20210401 - 20210430 don't have data
 ELV 20210301 - 20210331 don't have data
 ELV 20210201 - 20210228 don't have data
 ELV 20210101 - 20210131 don't have data
ELV 251.49

0it [00:00, ?it/s]

 EMBC 20211201 - 20211231 don't have data
 EMBC 20211101 - 20211130 don't have data
 EMBC 20211001 - 20211031 don't have data
 EMBC 20210901 - 20210930 don't have data
 EMBC 20210801 - 20210831 don't have data
 EMBC 20210701 - 20210731 don't have data
 EMBC 20210601 - 20210630 don't have data
 EMBC 20210501 - 20210531 don't have data
 EMBC 20210401 - 20210430 don't have data
 EMBC 20210301 - 20210331 don't have data
 EMBC 20210201 - 20210228 don't have data
 EMBC 20210101 - 20210131 don't have data
EMBC 252.82

0it [00:00, ?it/s]

 ENFN 20211201 - 20211231 don't have data
 ENFN 20211101 - 20211130 don't have data
 ENFN 20211001 - 20211031 don't have data
 ENFN 20210901 - 20210930 don't have data
 ENFN 20210801 - 20210831 don't have data
 ENFN 20210701 - 20210731 don't have data
 ENFN 20210601 - 20210630 don't have data
 ENFN 20210501 - 20210531 don't have data
 ENFN 20210401 - 20210430 don't have data
 ENFN 20210301 - 20210331 don't have data
 ENFN 20210201 - 20210228 don't have data
 ENFN 20210101 - 20210131 don't have data
ENFN 258.56

0it [00:00, ?it/s]

 ERAS 20211201 - 20211231 don't have data
 ERAS 20211101 - 20211130 don't have data
 ERAS 20211001 - 20211031 don't have data
 ERAS 20210901 - 20210930 don't have data
 ERAS 20210801 - 20210831 don't have data
 ERAS 20210701 - 20210731 don't have data
 ERAS 20210601 - 20210630 don't have data
 ERAS 20210501 - 20210531 don't have data
 ERAS 20210401 - 20210430 don't have data
 ERAS 20210301 - 20210331 don't have data
 ERAS 20210201 - 20210228 don't have data
 ERAS 20210101 - 20210131 don't have data
ERAS 264.45

0it [00:00, ?it/s]

 EU 20211201 - 20211231 don't have data
 EU 20211101 - 20211130 don't have data
 EU 20211001 - 20211031 don't have data
 EU 20210901 - 20210930 don't have data
 EU 20210801 - 20210831 don't have data
 EU 20210701 - 20210731 don't have data
 EU 20210601 - 20210630 don't have data
 EU 20210501 - 20210531 don't have data
 EU 20210401 - 20210430 don't have data
 EU 20210301 - 20210331 don't have data
 EU 20210201 - 20210228 don't have data
 EU 20210101 - 20210131 don't have data
EU 253.62

0it [00:00, ?it/s]

 EVE 20211201 - 20211231 don't have data
 EVE 20211101 - 20211130 don't have data
 EVE 20211001 - 20211031 don't have data
 EVE 20210901 - 20210930 don't have data
 EVE 20210801 - 20210831 don't have data
 EVE 20210701 - 20210731 don't have data
 EVE 20210601 - 20210630 don't have data
 EVE 20210501 - 20210531 don't have data
 EVE 20210401 - 20210430 don't have data
 EVE 20210301 - 20210331 don't have data
 EVE 20210201 - 20210228 don't have data
 EVE 20210101 - 20210131 don't have data
EVE 252.55

0it [00:00, ?it/s]

 EXFY 20211201 - 20211231 don't have data
 EXFY 20211101 - 20211130 don't have data
 EXFY 20211001 - 20211031 don't have data
 EXFY 20210901 - 20210930 don't have data
 EXFY 20210801 - 20210831 don't have data
 EXFY 20210701 - 20210731 don't have data
 EXFY 20210601 - 20210630 don't have data
 EXFY 20210501 - 20210531 don't have data
 EXFY 20210401 - 20210430 don't have data
 EXFY 20210301 - 20210331 don't have data
 EXFY 20210201 - 20210228 don't have data
 EXFY 20210101 - 20210131 don't have data
EXFY 253.51

0it [00:00, ?it/s]

 FBIN 20211201 - 20211231 don't have data
 FBIN 20211101 - 20211130 don't have data
 FBIN 20211001 - 20211031 don't have data
 FBIN 20210901 - 20210930 don't have data
 FBIN 20210801 - 20210831 don't have data
 FBIN 20210701 - 20210731 don't have data

KeyboardInterrupt:

In [23]:
cur_df

shape: (0, 0)
┌┐
╞╡
└┘

In [7]:
minute_1 = 60000
minute_1 * 60 * 16, 62917076 / minute_1 / 60

(57600000, 17.47696555555556)

In [6]:
62638161 / minute_1 / 60 // 15, (57000000 / minute_1 / 60 % 15) * 60

(1.0, 50.000000000000036)

In [211]:
minute_1 = 60000
minute_1 * 60 * 16

57600000

## Create united options file

In [4]:
year: str = '2022'
chunk_size = 500
chunk_counter = 0
batch_dfs = []

for root, dirs, files in os.walk('data/options/'):
    parquet_files = [f for f in files if f.endswith('.parquet') and year in f]
    num_files = len(parquet_files)

    for i in tqdm(range(0, num_files, chunk_size)):
        total_df = pl.DataFrame()
        
        for file in tqdm(parquet_files[i:i + chunk_size]):
            try:
                cur_df = pl.read_parquet(os.path.join(root, file), low_memory=True)\
                    .drop(['root', 'ms_of_day2', 'open', 'high', 'low'])
                total_df = pl.concat([total_df, cur_df])
            except Exception as e:
                print(file)
                print(e)

        # Save intermediate result
        total_df = total_df.with_columns(
            [pl.col(col).cast(pl.String).str.to_date('%Y%m%d') for col in ['expiration', 'date']],
        ).with_columns(
            [pl.col(col).cast(pl.Int16) for col in ['bid_exchange', 'bid_condition', 'ask_exchange', 'ask_condition']],
        ).with_columns(
            [pl.col(col).cast(pl.Int32) for col in ['ms_of_day', 'volume', 'count', 'bid_size', 'ask_size']],
        ).with_columns(
            [pl.col(col).cast(pl.Float32) for col in ['close', 'bid', 'ask']],
        )
        
        batch_file = f'data/temp//batch_{year}_{chunk_counter}.parquet'
        total_df.write_parquet(batch_file)
        batch_dfs.append(batch_file)
        chunk_counter += 1

  0%|          | 0/6 [00:00<?, ?it/s]

  0%|          | 0/500 [00:00<?, ?it/s]

  0%|          | 0/500 [00:00<?, ?it/s]

  0%|          | 0/500 [00:00<?, ?it/s]

  0%|          | 0/500 [00:00<?, ?it/s]

  0%|          | 0/500 [00:00<?, ?it/s]

  0%|          | 0/169 [00:00<?, ?it/s]

In [3]:
qqq_df = pl.read_parquet('data/options/20230101_QQQ_opts.parquet')\
    .drop(['root', 'ms_of_day2', 'open', 'high', 'low'])
iwm_df = pl.read_parquet('data/options/20230101_IWM_opts.parquet')\
    .drop(['root', 'ms_of_day2', 'open', 'high', 'low'])
total_df = pl.concat([qqq_df, iwm_df])

batch_file = f'data/temp//batch_6.parquet'
total_df.write_parquet(batch_file)

In [57]:
ans_df = pl.read_csv(StringIO(ans)).with_columns(pl.lit(t).alias('ticker'))

## Load Stocks 1 minute

In [7]:
def get_stock_1m(t: str, start_date: str, end_date: str):
    if end_date < '20160101':
        return None

    params = {
        'root': t, 'exp': 0,
        'start_date': start_date, 'end_date': end_date,  
        'use_csv': 'True', 'ivl': '60000'
    }
    ans, status_code = make_request('hist', 'stock', 'ohlc', params)
    
    if status_code == 472:
        print(f"\033[1;91m {t} {start_date} - {end_date} don't have data \033[0m")
        return None
    elif status_code == 572:
        print(f"\033[1;91m {t} an error \033[0m")
        return None
    
    ans_df = pl.read_csv(StringIO(ans)).with_columns(pl.lit(t).alias('ticker'))

    return ans_df

In [8]:
liquid_tickers = []
for core, folder, files in os.walk('data\stocks\daily'):
    for file in tqdm(files):
        cur_df = pl.read_parquet(os.path.join(core, file))
        if (cur_df['rol_50_vol'] > 1_000_000).any():
            liquid_tickers.append(file.split('_')[2])

for core, folder, files in os.walk('data/stocks/m1'):
    already_tickers = [file.split('_')[2] for file in files]

tickers_for_load = set(liquid_tickers) - set(already_tickers)

  0%|          | 0/7804 [00:00<?, ?it/s]

In [5]:
with open('data/all_tickers_expir.pickle', 'rb') as f:
    tickers_all_exp = pickle.load(f)

tickers_dates = {}
for t in tqdm(tickers_for_load):
    tickers_dates[t] = {}
    
    cur_dates = tickers_all_exp[t]['trade_dates']
    cur_dates = pd.Series(cur_dates, index=cur_dates)[f'20160101':].values
    start_range = cur_dates[0]
    end_range = cur_dates[-1]

    weekly_start = list(pd.date_range(start_range, end_range, freq='W-MON').strftime('%Y%m%d')[::-1])
    weekly_end = list(pd.date_range(start_range, end_range, freq='W-SUN').strftime('%Y%m%d')[::-1])
    weekly_end.extend([end_range])
    weekly_end = np.sort(weekly_end)[::-1]

    tickers_dates[t]['weekly_start'] = weekly_start
    tickers_dates[t]['weekly_end'] = weekly_end

0it [00:00, ?it/s]

In [6]:
for t in tqdm(tickers_for_load, total=len(tickers_for_load)):
    cur_data = tickers_dates[t]
    
    final_df = pl.DataFrame()    
    with ThreadPoolExecutor(max_workers=24) as executor:
        futures = {
            executor.submit(get_stock_1m, t, w_s, w_e): 
            (t, w_s, w_e) for w_s, w_e in zip(cur_data['weekly_start'], cur_data['weekly_end'])
        }
        for future in tqdm(as_completed(futures), total=len(cur_data['weekly_start'])):
            try:
                cur_df = future.result()
                if (cur_df is None) or len(cur_df) == 0: 
                    continue
                final_df = pl.concat([final_df, cur_df])
            except Exception as e:
                print(e)
                raise Exception

    try:
        if (final_df is None) or len(final_df) == 0: 
            continue
    
        final_df = final_df.sort('date')
        min_date = str(final_df['date'].min())
        max_date = str(final_df['date'].max())
        final_df.write_parquet(f'data/stocks/m1/{min_date}_{max_date}_{t}_opts.parquet')
    except Exception as e:
        print(e)
        raise Exception

0it [00:00, ?it/s]

# Options EOD

In [7]:
def get_option_eod(t: str, start_date: str, end_date: str):
    if end_date < '20160101':
        return None
        
    params = {
        'root': t, 'exp': 0,
        'start_date': start_date, 'end_date': end_date,  
        'use_csv': 'True'
    }
    ans, status_code = make_request('bulk_hist', 'option', 'eod', params)
    
    if status_code == 472:
        print(f"\033[1;91m {t} {start_date} - {end_date} don't have data \033[0m")
        return None
    elif status_code == 572:
        print(f"\033[1;91m {t} an error \033[0m")
        return None
    
    ans_df = pl.read_csv(StringIO(ans)).with_columns(pl.lit(t).alias('ticker'))
    
    return ans_df

In [8]:
load_year: str = '2020'

liquid_tickers = []
for core, folder, files in os.walk('data\stocks\daily'):
    for file in tqdm(files):
        cur_df = pl.read_parquet(os.path.join(core, file))
        if (cur_df['rol_50_vol'] > 1_000_000).any():
            liquid_tickers.append(file.split('_')[2])

already_tickers = [file.split('_')[2] for file in os.listdir('data/options') if load_year in file]
tickers_for_load = set(liquid_tickers) - set(already_tickers)
len(tickers_for_load)

  0%|          | 0/7804 [00:00<?, ?it/s]

1681

In [9]:
with open('data/all_tickers_expir.pickle', 'rb') as f:
    tickers_all_exp = pickle.load(f)
    
for t in tqdm(tickers_for_load, total=len(tickers_for_load)):
    dates = tickers_all_exp[t]['trade_dates']
    dates = pd.Series(dates, index=dates)[f'{load_year}0101':f'{load_year}1231'].values
    if len(dates) == 0:
        continue

    expirations = tickers_all_exp[t]['expirations']
    interseс = set(pd.Series(dates).astype(str)) & set(pd.Series(expirations).astype(str))
    if len(interseс) == 0:
        continue

    final_df = pl.DataFrame()   
    with ThreadPoolExecutor(max_workers=24) as executor:
        futures = {
            executor.submit(get_option_eod, t, start, end): 
            (t, start, end) for start, end in zip(dates, dates)
        }
        for future in tqdm(as_completed(futures), total=len(dates)):
            try:
                cur_df = future.result()
                if (cur_df is None) or len(cur_df) == 0: 
                    continue
                final_df = pl.concat([final_df, cur_df])
            except Exception as e:
                print(cur_df)
                print(e)
                raise Exception
    try:
        if (final_df is None) or len(final_df) == 0: 
            continue
        final_df = final_df.sort('date', 'expiration', 'right', 'strike')\
            .with_columns(pl.col('date').cast(pl.String).str.strptime(pl.Date, '%Y%m%d', strict=False))
        for year in final_df['date'].dt.year().unique():
            cur_df = final_df.filter(pl.col('date').dt.year() == year)\
                .unique(subset=['expiration', 'date', 'right', 'strike'])
            min_date = cur_df['date'].min().strftime('%Y%m%d')
            max_date = cur_df['date'].max().strftime('%Y%m%d')

            cur_df.write_parquet(f'data/options/{min_date}_{max_date}_{t}_opts.parquet')
    except Exception as e:
        print(final_df)
        print(cur_df)
        print(e)
        raise Exception

  0%|          | 0/1681 [00:00<?, ?it/s]

  0%|          | 0/253 [00:00<?, ?it/s]

  0%|          | 0/241 [00:00<?, ?it/s]

 FRAN 20200103 - 20200103 don't have data
 FRAN 20200102 - 20200102 don't have data
 FRAN 20200106 - 20200106 don't have data
 FRAN 20200107 - 20200107 don't have data
 FRAN 20200108 - 20200108 don't have data
 FRAN 20200113 - 20200113 don't have data
 FRAN 20200114 - 20200114 don't have data
 FRAN 20200109 - 20200109 don't have data
 FRAN 20200110 - 20200110 don't have data
 FRAN 20200115 - 20200115 don't have data
 FRAN 20200121 - 20200121 don't have data
 FRAN 20200122 - 20200122 don't have data
 FRAN 20200116 - 20200116 don't have data
 FRAN 20200123 - 20200123 don't have data
 FRAN 20200117 - 20200117 don't have data
 FRAN 20200127 - 20200127 don't have data
 FRAN 20200124 - 20200124 don't have data
 FRAN 20200130 - 20200130 don't have data
 FRAN 20200128 - 20200128 don't have data
 FRAN 20200203 - 20200203 don't have data
 FRAN 20200129 - 20200129 don't have data
 FRAN 20200205 - 20200205 don't have data
 FRAN 20200131 - 20200131 don't have data
 FRAN 20200206 - 20200206 don't have data
 FRAN 20200204 - 20200204 don't have data
 FRAN 20200211 - 20200211 don't have data
 FRAN 20200207 - 20200207 don't have data
 FRAN 20200213 - 20200213 don't have data
 FRAN 20200210 - 20200210 don't have data
 FRAN 20200219 - 20200219 don't have data
 FRAN 20200212 - 20200212 don't have data
 FRAN 20200224 - 20200224 don't have data
 FRAN 20200214 - 20200214 don't have data
 FRAN 20200226 - 20200226 don't have data
 FRAN 20200218 - 20200218 don't have data
 FRAN 20200227 - 20200227 don't have data
 FRAN 20200220 - 20200220 don't have data
 FRAN 20200302 - 20200302 don't have data
 FRAN 20200221 - 20200221 don't have data
 FRAN 20200303 - 20200303 don't have data
 FRAN 20200225 - 20200225 don't have data
 FRAN 20200305 - 20200305 don't have data
 FRAN 20200228 - 20200228 don't have data
 FRAN 20200310 - 20200310 don't have data
 FRAN 20200304 - 20200304 don't have data
 FRAN 20200312 - 20200312 don't have data
 FRAN 20200306 - 20200306 don't have data
 FRAN 20200317 - 20200317 don't have data
 FRAN 20200309 - 20200309 don't have data
 FRAN 20200319 - 20200319 don't have data
 FRAN 20200311 - 20200311 don't have data
 FRAN 20200320 - 20200320 don't have data
 FRAN 20200313 - 20200313 don't have data
 FRAN 20200324 - 20200324 don't have data
 FRAN 20200316 - 20200316 don't have data
 FRAN 20200325 - 20200325 don't have data
 FRAN 20200318 - 20200318 don't have data
 FRAN 20200327 - 20200327 don't have data
 FRAN 20200323 - 20200323 don't have data
 FRAN 20200330 - 20200330 don't have data
 FRAN 20200326 - 20200326 don't have data
 FRAN 20200401 - 20200401 don't have data
 FRAN 20200331 - 20200331 don't have data
 FRAN 20200403 - 20200403 don't have data
 FRAN 20200402 - 20200402 don't have data
 FRAN 20200406 - 20200406 don't have data
 FRAN 20200407 - 20200407 don't have data
 FRAN 20200409 - 20200409 don't have data
 FRAN 20200408 - 20200408 don't have data
 FRAN 20200414 - 20200414 don't have data
 FRAN 20200413 - 20200413 don't have data
 FRAN 20200415 - 20200415 don't have data
 FRAN 20200420 - 20200420 don't have data
 FRAN 20200416 - 20200416 don't have data
 FRAN 20200422 - 20200422 don't have data
 FRAN 20200417 - 20200417 don't have data
 FRAN 20200423 - 20200423 don't have data
 FRAN 20200421 - 20200421 don't have data
 FRAN 20200428 - 20200428 don't have data
 FRAN 20200424 - 20200424 don't have data
 FRAN 20200501 - 20200501 don't have data
 FRAN 20200427 - 20200427 don't have data
 FRAN 20200505 - 20200505 don't have data
 FRAN 20200429 - 20200429 don't have data
 FRAN 20200506 - 20200506 don't have data
 FRAN 20200430 - 20200430 don't have data
 FRAN 20200511 - 20200511 don't have data
 FRAN 20200504 - 20200504 don't have data
 FRAN 20200514 - 20200514 don't have data
 FRAN 20200507 - 20200507 don't have data
 FRAN 20200519 - 20200519 don't have data
 FRAN 20200521 - 20200521 don't have data
 FRAN 20200508 - 20200508 don't have data
 FRAN 20200522 - 20200522 don't have data
 FRAN 20200512 - 20200512 don't have data
 FRAN 20200528 - 20200528 don't have data
 FRAN 20200513 - 20200513 don't have data
 FRAN 20200601 - 20200601 don't have data
 FRAN 20200515 - 20200515 don't have data
 FRAN 20200602 - 20200602 don't have data
 FRAN 20200518 - 20200518 don't have data
 FRAN 20200604 - 20200604 don't have data
 FRAN 20200520 - 20200520 don't have data
 FRAN 20200605 - 20200605 don't have data
 FRAN 20200526 - 20200526 don't have data
 FRAN 20200609 - 20200609 don't have data
 FRAN 20200527 - 20200527 don't have data
 FRAN 20200612 - 20200612 don't have data
 FRAN 20200529 - 20200529 don't have data
 FRAN 20200615 - 20200615 don't have data
 FRAN 20200617 - 20200617 don't have data
 FRAN 20200603 - 20200603 don't have data
 FRAN 20200618 - 20200618 don't have data
 FRAN 20200608 - 20200608 don't have data
 FRAN 20200622 - 20200622 don't have data
 FRAN 20200610 - 20200610 don't have data
 FRAN 20200623 - 20200623 don't have data
 FRAN 20200611 - 20200611 don't have data
 FRAN 20200625 - 20200625 don't have data
 FRAN 20200616 - 20200616 don't have data
 FRAN 20200626 - 20200626 don't have data
 FRAN 20200619 - 20200619 don't have data
 FRAN 20200630 - 20200630 don't have data
 FRAN 20200706 - 20200706 don't have data
 FRAN 20200624 - 20200624 don't have data
 FRAN 20200707 - 20200707 don't have data
 FRAN 20200629 - 20200629 don't have data
 FRAN 20200709 - 20200709 don't have data
 FRAN 20200701 - 20200701 don't have data
 FRAN 20200710 - 20200710 don't have data
 FRAN 20200702 - 20200702 don't have data
 FRAN 20200715 - 20200715 don't have data
 FRAN 20200708 - 20200708 don't have data
 FRAN 20200720 - 20200720 don't have data
 FRAN 20200713 - 20200713 don't have data
 FRAN 20200723 - 20200723 don't have data
 FRAN 20200714 - 20200714 don't have data
 FRAN 20200729 - 20200729 don't have data
 FRAN 20200716 - 20200716 don't have data
 FRAN 20200731 - 20200731 don't have data
 FRAN 20200717 - 20200717 don't have data
 FRAN 20200803 - 20200803 don't have data
 FRAN 20200805 - 20200805 don't have data
 FRAN 20200721 - 20200721 don't have data
 FRAN 20200806 - 20200806 don't have data
 FRAN 20200722 - 20200722 don't have data
 FRAN 20200810 - 20200810 don't have data
 FRAN 20200724 - 20200724 don't have data
 FRAN 20200811 - 20200811 don't have data
 FRAN 20200727 - 20200727 don't have data
 FRAN 20200813 - 20200813 don't have data
 FRAN 20200728 - 20200728 don't have data
 FRAN 20200814 - 20200814 don't have data
 FRAN 20200730 - 20200730 don't have data
 FRAN 20200818 - 20200818 don't have data
 FRAN 20200819 - 20200819 don't have data
 FRAN 20200804 - 20200804 don't have data
 FRAN 20200821 - 20200821 don't have data
 FRAN 20200807 - 20200807 don't have data
 FRAN 20200826 - 20200826 don't have data
 FRAN 20200812 - 20200812 don't have data
 FRAN 20200831 - 20200831 don't have data
 FRAN 20200817 - 20200817 don't have data
 FRAN 20200903 - 20200903 don't have data
 FRAN 20200820 - 20200820 don't have data
 FRAN 20200909 - 20200909 don't have data
 FRAN 20200914 - 20200914 don't have data
 FRAN 20200824 - 20200824 don't have data
 FRAN 20200916 - 20200916 don't have data
 FRAN 20200825 - 20200825 don't have data
 FRAN 20200917 - 20200917 don't have data
 FRAN 20200827 - 20200827 don't have data
 FRAN 20200922 - 20200922 don't have data
 FRAN 20200828 - 20200828 don't have data
 FRAN 20200924 - 20200924 don't have data
 FRAN 20200901 - 20200901 don't have data
 FRAN 20200925 - 20200925 don't have data
 FRAN 20200902 - 20200902 don't have data
 FRAN 20200929 - 20200929 don't have data
 FRAN 20200904 - 20200904 don't have data
 FRAN 20200930 - 20200930 don't have data
 FRAN 20200908 - 20200908 don't have data
 FRAN 20201005 - 20201005 don't have data
 FRAN 20200910 - 20200910 don't have data
 FRAN 20201007 - 20201007 don't have data
 FRAN 20200911 - 20200911 don't have data
 FRAN 20201008 - 20201008 don't have data
 FRAN 20200915 - 20200915 don't have data
 FRAN 20201012 - 20201012 don't have data
 FRAN 20200918 - 20200918 don't have data
 FRAN 20201013 - 20201013 don't have data
 FRAN 20200921 - 20200921 don't have data
 FRAN 20201015 - 20201015 don't have data
 FRAN 20200923 - 20200923 don't have data
 FRAN 20201016 - 20201016 don't have data
 FRAN 20200928 - 20200928 don't have data
 FRAN 20201020 - 20201020 don't have data
 FRAN 20201021 - 20201021 don't have data
 FRAN 20201001 - 20201001 don't have data
 FRAN 20201023 - 20201023 don't have data
 FRAN 20201002 - 20201002 don't have data
 FRAN 20201028 - 20201028 don't have data
 FRAN 20201006 - 20201006 don't have data
 FRAN 20201029 - 20201029 don't have data
 FRAN 20201009 - 20201009 don't have data
 FRAN 20201102 - 20201102 don't have data
 FRAN 20201014 - 20201014 don't have data
 FRAN 20201105 - 20201105 don't have data
 FRAN 20201019 - 20201019 don't have data
 FRAN 20201106 - 20201106 don't have data
 FRAN 20201022 - 20201022 don't have data
 FRAN 20201110 - 20201110 don't have data
 FRAN 20201026 - 20201026 don't have data
 FRAN 20201113 - 20201113 don't have data
 FRAN 20201027 - 20201027 don't have data
 FRAN 20201116 - 20201116 don't have data
 FRAN 20201030 - 20201030 don't have data
 FRAN 20201118 - 20201118 don't have data
 FRAN 20201123 - 20201123 don't have data
 FRAN 20201103 - 20201103 don't have data
 FRAN 20201125 - 20201125 don't have data
 FRAN 20201104 - 20201104 don't have data
 FRAN 20201127 - 20201127 don't have data
 FRAN 20201109 - 20201109 don't have data
 FRAN 20201202 - 20201202 don't have data
 FRAN 20201111 - 20201111 don't have data
 FRAN 20201207 - 20201207 don't have data
 FRAN 20201112 - 20201112 don't have data
 FRAN 20201210 - 20201210 don't have data
 FRAN 20201117 - 20201117 don't have data
 FRAN 20201211 - 20201211 don't have data
 FRAN 20201119 - 20201119 don't have data
 FRAN 20201120 - 20201120 don't have data
 FRAN 20201124 - 20201124 don't have data
 FRAN 20201130 - 20201130 don't have data
 FRAN 20201201 - 20201201 don't have data
 FRAN 20201203 - 20201203 don't have data
 FRAN 20201204 - 20201204 don't have data
 FRAN 20201208 - 20201208 don't have data
 FRAN 20201209 - 20201209 don't have data
 FRAN 20201214 - 20201214 don't have data

  0%|          | 0/253 [00:00<?, ?it/s]

  0%|          | 0/253 [00:00<?, ?it/s]

  0%|          | 0/253 [00:00<?, ?it/s]

 APDN 20200103 - 20200103 don't have data
 APDN 20200102 - 20200102 don't have data
 APDN 20200107 - 20200107 don't have data
 APDN 20200106 - 20200106 don't have data
 APDN 20200109 - 20200109 don't have data
 APDN 20200108 - 20200108 don't have data
 APDN 20200113 - 20200113 don't have data
 APDN 20200110 - 20200110 don't have data
 APDN 20200116 - 20200116 don't have data
 APDN 20200114 - 20200114 don't have data
 APDN 20200117 - 20200117 don't have data
 APDN 20200115 - 20200115 don't have data
 APDN 20200123 - 20200123 don't have data
 APDN 20200121 - 20200121 don't have data
 APDN 20200127 - 20200127 don't have data
 APDN 20200124 - 20200124 don't have data
 APDN 20200130 - 20200130 don't have data
 APDN 20200128 - 20200128 don't have data
 APDN 20200129 - 20200129 don't have data
 APDN 20200131 - 20200131 don't have data
 APDN 20200204 - 20200204 don't have data
 APDN 20200203 - 20200203 don't have data
 APDN 20200205 - 20200205 don't have data
 APDN 20200122 - 20200122 don't have data
 APDN 20200206 - 20200206 don't have data
 APDN 20200207 - 20200207 don't have data
 APDN 20200210 - 20200210 don't have data
 APDN 20200211 - 20200211 don't have data
 APDN 20200213 - 20200213 don't have data
 APDN 20200212 - 20200212 don't have data
 APDN 20200218 - 20200218 don't have data
 APDN 20200214 - 20200214 don't have data
 APDN 20200219 - 20200219 don't have data
 APDN 20200220 - 20200220 don't have data
 APDN 20200221 - 20200221 don't have data
 APDN 20200224 - 20200224 don't have data
 APDN 20200225 - 20200225 don't have data
 APDN 20200227 - 20200227 don't have data
 APDN 20200226 - 20200226 don't have data
 APDN 20200303 - 20200303 don't have data
 APDN 20200228 - 20200228 don't have data
 APDN 20200305 - 20200305 don't have data
 APDN 20200302 - 20200302 don't have data
 APDN 20200310 - 20200310 don't have data
 APDN 20200304 - 20200304 don't have data
 APDN 20200313 - 20200313 don't have data
 APDN 20200306 - 20200306 don't have data
 APDN 20200309 - 20200309 don't have data
 APDN 20200317 - 20200317 don't have data
 APDN 20200311 - 20200311 don't have data
 APDN 20200320 - 20200320 don't have data
 APDN 20200312 - 20200312 don't have data
 APDN 20200324 - 20200324 don't have data
 APDN 20200316 - 20200316 don't have data
 APDN 20200325 - 20200325 don't have data
 APDN 20200318 - 20200318 don't have data
 APDN 20200327 - 20200327 don't have data
 APDN 20200319 - 20200319 don't have data
 APDN 20200330 - 20200330 don't have data
 APDN 20200323 - 20200323 don't have data
 APDN 20200401 - 20200401 don't have data
 APDN 20200326 - 20200326 don't have data
 APDN 20200402 - 20200402 don't have data
 APDN 20200331 - 20200331 don't have data
 APDN 20200406 - 20200406 don't have data
 APDN 20200403 - 20200403 don't have data
 APDN 20200409 - 20200409 don't have data
 APDN 20200407 - 20200407 don't have data
 APDN 20200408 - 20200408 don't have data
 APDN 20200414 - 20200414 don't have data
 APDN 20200413 - 20200413 don't have data
 APDN 20200415 - 20200415 don't have data
 APDN 20200416 - 20200416 don't have data
 APDN 20200420 - 20200420 don't have data
 APDN 20200417 - 20200417 don't have data
 APDN 20200422 - 20200422 don't have data
 APDN 20200421 - 20200421 don't have data
 APDN 20200423 - 20200423 don't have data
 APDN 20200424 - 20200424 don't have data
 APDN 20200427 - 20200427 don't have data
 APDN 20200429 - 20200429 don't have data
 APDN 20200428 - 20200428 don't have data
 APDN 20200504 - 20200504 don't have data
 APDN 20200430 - 20200430 don't have data
 APDN 20200507 - 20200507 don't have data
 APDN 20200501 - 20200501 don't have data
 APDN 20200508 - 20200508 don't have data
 APDN 20200505 - 20200505 don't have data
 APDN 20200512 - 20200512 don't have data
 APDN 20200506 - 20200506 don't have data
 APDN 20200515 - 20200515 don't have data
 APDN 20200511 - 20200511 don't have data
 APDN 20200518 - 20200518 don't have data
 APDN 20200513 - 20200513 don't have data
 APDN 20200520 - 20200520 don't have data
 APDN 20200514 - 20200514 don't have data
 APDN 20200526 - 20200526 don't have data
 APDN 20200529 - 20200529 don't have data
 APDN 20200519 - 20200519 don't have data
 APDN 20200603 - 20200603 don't have data
 APDN 20200521 - 20200521 don't have data
 APDN 20200608 - 20200608 don't have data
 APDN 20200522 - 20200522 don't have data
 APDN 20200611 - 20200611 don't have data
 APDN 20200527 - 20200527 don't have data
 APDN 20200616 - 20200616 don't have data
 APDN 20200528 - 20200528 don't have data
 APDN 20200618 - 20200618 don't have data
 APDN 20200601 - 20200601 don't have data
 APDN 20200619 - 20200619 don't have data
 APDN 20200602 - 20200602 don't have data
 APDN 20200623 - 20200623 don't have data
 APDN 20200604 - 20200604 don't have data
 APDN 20200626 - 20200626 don't have data
 APDN 20200605 - 20200605 don't have data
 APDN 20200629 - 20200629 don't have data
 APDN 20200609 - 20200609 don't have data
 APDN 20200701 - 20200701 don't have data
 APDN 20200702 - 20200702 don't have data
 APDN 20200610 - 20200610 don't have data
 APDN 20200707 - 20200707 don't have data
 APDN 20200612 - 20200612 don't have data
 APDN 20200710 - 20200710 don't have data
 APDN 20200615 - 20200615 don't have data
 APDN 20200713 - 20200713 don't have data
 APDN 20200617 - 20200617 don't have data
 APDN 20200715 - 20200715 don't have data
 APDN 20200622 - 20200622 don't have data
 APDN 20200720 - 20200720 don't have data
 APDN 20200624 - 20200624 don't have data
 APDN 20200723 - 20200723 don't have data
 APDN 20200728 - 20200728 don't have data
 APDN 20200625 - 20200625 don't have data
 APDN 20200729 - 20200729 don't have data
 APDN 20200630 - 20200630 don't have data
 APDN 20200731 - 20200731 don't have data
 APDN 20200706 - 20200706 don't have data
 APDN 20200803 - 20200803 don't have data
 APDN 20200708 - 20200708 don't have data
 APDN 20200805 - 20200805 don't have data
 APDN 20200709 - 20200709 don't have data
 APDN 20200806 - 20200806 don't have data
 APDN 20200714 - 20200714 don't have data
 APDN 20200810 - 20200810 don't have data
 APDN 20200813 - 20200813 don't have data
 APDN 20200716 - 20200716 don't have data
 APDN 20200818 - 20200818 don't have data
 APDN 20200717 - 20200717 don't have data
 APDN 20200820 - 20200820 don't have data
 APDN 20200721 - 20200721 don't have data
 APDN 20200821 - 20200821 don't have data
 APDN 20200722 - 20200722 don't have data
 APDN 20200826 - 20200826 don't have data
 APDN 20200724 - 20200724 don't have data
 APDN 20200831 - 20200831 don't have data
 APDN 20200727 - 20200727 don't have data
 APDN 20200903 - 20200903 don't have data
 APDN 20200909 - 20200909 don't have data
 APDN 20200730 - 20200730 don't have data
 APDN 20200914 - 20200914 don't have data
 APDN 20200804 - 20200804 don't have data
 APDN 20200917 - 20200917 don't have data
 APDN 20200807 - 20200807 don't have data
 APDN 20200922 - 20200922 don't have data
 APDN 20200811 - 20200811 don't have data
 APDN 20200924 - 20200924 don't have data
 APDN 20200812 - 20200812 don't have data
 APDN 20200925 - 20200925 don't have data
 APDN 20200814 - 20200814 don't have data
 APDN 20200930 - 20200930 don't have data
 APDN 20200817 - 20200817 don't have data
 APDN 20201002 - 20201002 don't have data
 APDN 20200819 - 20200819 don't have data
 APDN 20201005 - 20201005 don't have data
 APDN 20200824 - 20200824 don't have data
 APDN 20201008 - 20201008 don't have data
 APDN 20200825 - 20200825 don't have data
 APDN 20201013 - 20201013 don't have data
 APDN 20200827 - 20200827 don't have data
 APDN 20201016 - 20201016 don't have data
 APDN 20200828 - 20200828 don't have data
 APDN 20201020 - 20201020 don't have data
 APDN 20200901 - 20200901 don't have data
 APDN 20201021 - 20201021 don't have data
 APDN 20200902 - 20200902 don't have data
 APDN 20201023 - 20201023 don't have data
 APDN 20200904 - 20200904 don't have data
 APDN 20201026 - 20201026 don't have data
 APDN 20200908 - 20200908 don't have data
 APDN 20201028 - 20201028 don't have data
 APDN 20200910 - 20200910 don't have data
 APDN 20201029 - 20201029 don't have data
 APDN 20201102 - 20201102 don't have data
 APDN 20200911 - 20200911 don't have data
 APDN 20201105 - 20201105 don't have data
 APDN 20200915 - 20200915 don't have data
 APDN 20201110 - 20201110 don't have data
 APDN 20200916 - 20200916 don't have data
 APDN 20201113 - 20201113 don't have data
 APDN 20200918 - 20200918 don't have data
 APDN 20201117 - 20201117 don't have data
 APDN 20200921 - 20200921 don't have data
 APDN 20201118 - 20201118 don't have data
 APDN 20200923 - 20200923 don't have data
 APDN 20201119 - 20201119 don't have data
 APDN 20200928 - 20200928 don't have data
 APDN 20201123 - 20201123 don't have data
 APDN 20200929 - 20200929 don't have data
 APDN 20201127 - 20201127 don't have data
 APDN 20201001 - 20201001 don't have data
 APDN 20201201 - 20201201 don't have data
 APDN 20201006 - 20201006 don't have data
 APDN 20201202 - 20201202 don't have data
 APDN 20201007 - 20201007 don't have data
 APDN 20201204 - 20201204 don't have data
 APDN 20201009 - 20201009 don't have data
 APDN 20201207 - 20201207 don't have data
 APDN 20201012 - 20201012 don't have data
 APDN 20201209 - 20201209 don't have data
 APDN 20201014 - 20201014 don't have data
 APDN 20201214 - 20201214 don't have data
 APDN 20201215 - 20201215 don't have data
 APDN 20201015 - 20201015 don't have data
 APDN 20201217 - 20201217 don't have data
 APDN 20201019 - 20201019 don't have data
 APDN 20201218 - 20201218 don't have data
 APDN 20201022 - 20201022 don't have data
 APDN 20201222 - 20201222 don't have data
 APDN 20201027 - 20201027 don't have data
 APDN 20201223 - 20201223 don't have data
 APDN 20201030 - 20201030 don't have data
 APDN 20201228 - 20201228 don't have data
 APDN 20201103 - 20201103 don't have data
 APDN 20201229 - 20201229 don't have data
 APDN 20201104 - 20201104 don't have data
 APDN 20201231 - 20201231 don't have data
 APDN 20201106 - 20201106 don't have data
 APDN 20201109 - 20201109 don't have data
 APDN 20201111 - 20201111 don't have data
 APDN 20201112 - 20201112 don't have data
 APDN 20201116 - 20201116 don't have data
 APDN 20201120 - 20201120 don't have data
 APDN 20201124 - 20201124 don't have data
 APDN 20201125 - 20201125 don't have data
 APDN 20201130 - 20201130 don't have data
 APDN 20201203 - 20201203 don't have data
 APDN 20201208 - 20201208 don't have data
 APDN 20201210 - 20201210 don't have data
 APDN 20201211 - 20201211 don't have data
 APDN 20201216 - 20201216 don't have data
 APDN 20201221 - 20201221 don't have data
 APDN 20201224 - 20201224 don't have data
 APDN 20201230 - 20201230 don't have data

  0%|          | 0/29 [00:00<?, ?it/s]

  0%|          | 0/144 [00:00<?, ?it/s]

 TTPH 20200102 - 20200102 don't have data
 TTPH 20200103 - 20200103 don't have data
 TTPH 20200106 - 20200106 don't have data
 TTPH 20200107 - 20200107 don't have data
 TTPH 20200108 - 20200108 don't have data
 TTPH 20200110 - 20200110 don't have data
 TTPH 20200109 - 20200109 don't have data
 TTPH 20200114 - 20200114 don't have data
 TTPH 20200113 - 20200113 don't have data
 TTPH 20200116 - 20200116 don't have data
 TTPH 20200115 - 20200115 don't have data
 TTPH 20200117 - 20200117 don't have data
 TTPH 20200122 - 20200122 don't have data
 TTPH 20200121 - 20200121 don't have data
 TTPH 20200123 - 20200123 don't have data
 TTPH 20200127 - 20200127 don't have data
 TTPH 20200124 - 20200124 don't have data
 TTPH 20200130 - 20200130 don't have data
 TTPH 20200128 - 20200128 don't have data
 TTPH 20200131 - 20200131 don't have data
 TTPH 20200129 - 20200129 don't have data
 TTPH 20200205 - 20200205 don't have data
 TTPH 20200203 - 20200203 don't have data
 TTPH 20200207 - 20200207 don't have data
 TTPH 20200204 - 20200204 don't have data
 TTPH 20200211 - 20200211 don't have data
 TTPH 20200206 - 20200206 don't have data
 TTPH 20200212 - 20200212 don't have data
 TTPH 20200210 - 20200210 don't have data
 TTPH 20200214 - 20200214 don't have data
 TTPH 20200213 - 20200213 don't have data
 TTPH 20200218 - 20200218 don't have data
 TTPH 20200219 - 20200219 don't have data
 TTPH 20200220 - 20200220 don't have data
 TTPH 20200221 - 20200221 don't have data
 TTPH 20200225 - 20200225 don't have data
 TTPH 20200224 - 20200224 don't have data
 TTPH 20200227 - 20200227 don't have data
 TTPH 20200226 - 20200226 don't have data
 TTPH 20200228 - 20200228 don't have data
 TTPH 20200302 - 20200302 don't have data
 TTPH 20200303 - 20200303 don't have data
 TTPH 20200304 - 20200304 don't have data
 TTPH 20200306 - 20200306 don't have data
 TTPH 20200305 - 20200305 don't have data
 TTPH 20200310 - 20200310 don't have data
 TTPH 20200309 - 20200309 don't have data
 TTPH 20200311 - 20200311 don't have data
 TTPH 20200312 - 20200312 don't have data
 TTPH 20200313 - 20200313 don't have data
 TTPH 20200316 - 20200316 don't have data
 TTPH 20200318 - 20200318 don't have data
 TTPH 20200317 - 20200317 don't have data
 TTPH 20200320 - 20200320 don't have data
 TTPH 20200319 - 20200319 don't have data
 TTPH 20200323 - 20200323 don't have data
 TTPH 20200324 - 20200324 don't have data
 TTPH 20200325 - 20200325 don't have data
 TTPH 20200326 - 20200326 don't have data
 TTPH 20200330 - 20200330 don't have data
 TTPH 20200327 - 20200327 don't have data
 TTPH 20200401 - 20200401 don't have data
 TTPH 20200331 - 20200331 don't have data
 TTPH 20200402 - 20200402 don't have data
 TTPH 20200403 - 20200403 don't have data
 TTPH 20200406 - 20200406 don't have data
 TTPH 20200409 - 20200409 don't have data
 TTPH 20200407 - 20200407 don't have data
 TTPH 20200415 - 20200415 don't have data
 TTPH 20200408 - 20200408 don't have data
 TTPH 20200420 - 20200420 don't have data
 TTPH 20200413 - 20200413 don't have data
 TTPH 20200423 - 20200423 don't have data
 TTPH 20200414 - 20200414 don't have data
 TTPH 20200428 - 20200428 don't have data
 TTPH 20200416 - 20200416 don't have data
 TTPH 20200501 - 20200501 don't have data
 TTPH 20200417 - 20200417 don't have data
 TTPH 20200504 - 20200504 don't have data
 TTPH 20200421 - 20200421 don't have data
 TTPH 20200506 - 20200506 don't have data
 TTPH 20200511 - 20200511 don't have data
 TTPH 20200422 - 20200422 don't have data
 TTPH 20200512 - 20200512 don't have data
 TTPH 20200424 - 20200424 don't have data
 TTPH 20200514 - 20200514 don't have data
 TTPH 20200427 - 20200427 don't have data
 TTPH 20200515 - 20200515 don't have data
 TTPH 20200429 - 20200429 don't have data
 TTPH 20200519 - 20200519 don't have data
 TTPH 20200430 - 20200430 don't have data
 TTPH 20200520 - 20200520 don't have data
 TTPH 20200505 - 20200505 don't have data
 TTPH 20200522 - 20200522 don't have data
 TTPH 20200507 - 20200507 don't have data
 TTPH 20200526 - 20200526 don't have data
 TTPH 20200508 - 20200508 don't have data
 TTPH 20200528 - 20200528 don't have data
 TTPH 20200513 - 20200513 don't have data
 TTPH 20200529 - 20200529 don't have data
 TTPH 20200518 - 20200518 don't have data
 TTPH 20200602 - 20200602 don't have data
 TTPH 20200521 - 20200521 don't have data
 TTPH 20200603 - 20200603 don't have data
 TTPH 20200527 - 20200527 don't have data
 TTPH 20200605 - 20200605 don't have data
 TTPH 20200601 - 20200601 don't have data
 TTPH 20200610 - 20200610 don't have data
 TTPH 20200604 - 20200604 don't have data
 TTPH 20200615 - 20200615 don't have data
 TTPH 20200608 - 20200608 don't have data
 TTPH 20200618 - 20200618 don't have data
 TTPH 20200609 - 20200609 don't have data
 TTPH 20200622 - 20200622 don't have data
 TTPH 20200623 - 20200623 don't have data
 TTPH 20200611 - 20200611 don't have data
 TTPH 20200625 - 20200625 don't have data
 TTPH 20200612 - 20200612 don't have data
 TTPH 20200626 - 20200626 don't have data
 TTPH 20200616 - 20200616 don't have data
 TTPH 20200630 - 20200630 don't have data
 TTPH 20200617 - 20200617 don't have data
 TTPH 20200706 - 20200706 don't have data
 TTPH 20200619 - 20200619 don't have data
 TTPH 20200708 - 20200708 don't have data
 TTPH 20200624 - 20200624 don't have data
 TTPH 20200709 - 20200709 don't have data
 TTPH 20200629 - 20200629 don't have data
 TTPH 20200714 - 20200714 don't have data
 TTPH 20200701 - 20200701 don't have data
 TTPH 20200716 - 20200716 don't have data
 TTPH 20200702 - 20200702 don't have data
 TTPH 20200717 - 20200717 don't have data
 TTPH 20200707 - 20200707 don't have data
 TTPH 20200722 - 20200722 don't have data
 TTPH 20200710 - 20200710 don't have data
 TTPH 20200724 - 20200724 don't have data
 TTPH 20200713 - 20200713 don't have data
 TTPH 20200727 - 20200727 don't have data
 TTPH 20200715 - 20200715 don't have data
 TTPH 20200720 - 20200720 don't have data
 TTPH 20200721 - 20200721 don't have data
 TTPH 20200723 - 20200723 don't have data
 TTPH 20200728 - 20200728 don't have data

  0%|          | 0/253 [00:00<?, ?it/s]

  0%|          | 0/253 [00:00<?, ?it/s]

  0%|          | 0/253 [00:00<?, ?it/s]

  0%|          | 0/253 [00:00<?, ?it/s]

  0%|          | 0/253 [00:00<?, ?it/s]

  0%|          | 0/253 [00:00<?, ?it/s]

  0%|          | 0/253 [00:00<?, ?it/s]

 ALIM 20200106 - 20200106 don't have data
 ALIM 20200102 - 20200102 don't have data
 ALIM 20200107 - 20200107 don't have data
 ALIM 20200103 - 20200103 don't have data
 ALIM 20200109 - 20200109 don't have data
 ALIM 20200108 - 20200108 don't have data
 ALIM 20200110 - 20200110 don't have data
 ALIM 20200113 - 20200113 don't have data
 ALIM 20200115 - 20200115 don't have data
 ALIM 20200114 - 20200114 don't have data
 ALIM 20200117 - 20200117 don't have data
 ALIM 20200116 - 20200116 don't have data
 ALIM 20200123 - 20200123 don't have data
 ALIM 20200121 - 20200121 don't have data
 ALIM 20200128 - 20200128 don't have data
 ALIM 20200122 - 20200122 don't have data
 ALIM 20200124 - 20200124 don't have data
 ALIM 20200127 - 20200127 don't have data
 ALIM 20200129 - 20200129 don't have data
 ALIM 20200203 - 20200203 don't have data
 ALIM 20200131 - 20200131 don't have data
 ALIM 20200205 - 20200205 don't have data
 ALIM 20200130 - 20200130 don't have data
 ALIM 20200206 - 20200206 don't have data
 ALIM 20200204 - 20200204 don't have data
 ALIM 20200210 - 20200210 don't have data
 ALIM 20200207 - 20200207 don't have data
 ALIM 20200213 - 20200213 don't have data
 ALIM 20200211 - 20200211 don't have data
 ALIM 20200214 - 20200214 don't have data
 ALIM 20200212 - 20200212 don't have data
 ALIM 20200219 - 20200219 don't have data
 ALIM 20200218 - 20200218 don't have data
 ALIM 20200224 - 20200224 don't have data
 ALIM 20200220 - 20200220 don't have data
 ALIM 20200226 - 20200226 don't have data
 ALIM 20200221 - 20200221 don't have data
 ALIM 20200227 - 20200227 don't have data
 ALIM 20200302 - 20200302 don't have data
 ALIM 20200225 - 20200225 don't have data
 ALIM 20200303 - 20200303 don't have data
 ALIM 20200228 - 20200228 don't have data
 ALIM 20200305 - 20200305 don't have data
 ALIM 20200304 - 20200304 don't have data
 ALIM 20200310 - 20200310 don't have data
 ALIM 20200306 - 20200306 don't have data
 ALIM 20200312 - 20200312 don't have data
 ALIM 20200309 - 20200309 don't have data
 ALIM 20200313 - 20200313 don't have data
 ALIM 20200311 - 20200311 don't have data
 ALIM 20200317 - 20200317 don't have data
 ALIM 20200316 - 20200316 don't have data
 ALIM 20200320 - 20200320 don't have data
 ALIM 20200318 - 20200318 don't have data
 ALIM 20200325 - 20200325 don't have data
 ALIM 20200319 - 20200319 don't have data
 ALIM 20200327 - 20200327 don't have data
 ALIM 20200330 - 20200330 don't have data
 ALIM 20200323 - 20200323 don't have data
 ALIM 20200401 - 20200401 don't have data
 ALIM 20200324 - 20200324 don't have data
 ALIM 20200406 - 20200406 don't have data
 ALIM 20200326 - 20200326 don't have data
 ALIM 20200407 - 20200407 don't have data
 ALIM 20200331 - 20200331 don't have data
 ALIM 20200409 - 20200409 don't have data
 ALIM 20200413 - 20200413 don't have data
 ALIM 20200402 - 20200402 don't have data
 ALIM 20200415 - 20200415 don't have data
 ALIM 20200403 - 20200403 don't have data
 ALIM 20200420 - 20200420 don't have data
 ALIM 20200408 - 20200408 don't have data
 ALIM 20200424 - 20200424 don't have data
 ALIM 20200414 - 20200414 don't have data
 ALIM 20200427 - 20200427 don't have data
 ALIM 20200429 - 20200429 don't have data
 ALIM 20200416 - 20200416 don't have data
 ALIM 20200504 - 20200504 don't have data
 ALIM 20200417 - 20200417 don't have data
 ALIM 20200505 - 20200505 don't have data
 ALIM 20200421 - 20200421 don't have data
 ALIM 20200507 - 20200507 don't have data
 ALIM 20200422 - 20200422 don't have data
 ALIM 20200508 - 20200508 don't have data
 ALIM 20200423 - 20200423 don't have data
 ALIM 20200513 - 20200513 don't have data
 ALIM 20200428 - 20200428 don't have data
 ALIM 20200515 - 20200515 don't have data
 ALIM 20200430 - 20200430 don't have data
 ALIM 20200518 - 20200518 don't have data
 ALIM 20200501 - 20200501 don't have data
 ALIM 20200520 - 20200520 don't have data
 ALIM 20200506 - 20200506 don't have data
 ALIM 20200521 - 20200521 don't have data
 ALIM 20200511 - 20200511 don't have data
 ALIM 20200526 - 20200526 don't have data
 ALIM 20200512 - 20200512 don't have data
 ALIM 20200529 - 20200529 don't have data
 ALIM 20200603 - 20200603 don't have data
 ALIM 20200514 - 20200514 don't have data
 ALIM 20200608 - 20200608 don't have data
 ALIM 20200519 - 20200519 don't have data
 ALIM 20200610 - 20200610 don't have data
 ALIM 20200522 - 20200522 don't have data
 ALIM 20200611 - 20200611 don't have data
 ALIM 20200527 - 20200527 don't have data
 ALIM 20200615 - 20200615 don't have data
 ALIM 20200528 - 20200528 don't have data
 ALIM 20200616 - 20200616 don't have data
 ALIM 20200601 - 20200601 don't have data
 ALIM 20200618 - 20200618 don't have data
 ALIM 20200602 - 20200602 don't have data
 ALIM 20200619 - 20200619 don't have data
 ALIM 20200604 - 20200604 don't have data
 ALIM 20200623 - 20200623 don't have data
 ALIM 20200605 - 20200605 don't have data
 ALIM 20200624 - 20200624 don't have data
 ALIM 20200609 - 20200609 don't have data
 ALIM 20200629 - 20200629 don't have data
 ALIM 20200612 - 20200612 don't have data
 ALIM 20200701 - 20200701 don't have data
 ALIM 20200617 - 20200617 don't have data
 ALIM 20200702 - 20200702 don't have data
 ALIM 20200622 - 20200622 don't have data
 ALIM 20200708 - 20200708 don't have data
 ALIM 20200625 - 20200625 don't have data
 ALIM 20200713 - 20200713 don't have data
 ALIM 20200626 - 20200626 don't have data
 ALIM 20200716 - 20200716 don't have data
 ALIM 20200630 - 20200630 don't have data
 ALIM 20200717 - 20200717 don't have data
 ALIM 20200706 - 20200706 don't have data
 ALIM 20200721 - 20200721 don't have data
 ALIM 20200707 - 20200707 don't have data
 ALIM 20200722 - 20200722 don't have data
 ALIM 20200709 - 20200709 don't have data
 ALIM 20200724 - 20200724 don't have data
 ALIM 20200727 - 20200727 don't have data
 ALIM 20200710 - 20200710 don't have data
 ALIM 20200729 - 20200729 don't have data
 ALIM 20200714 - 20200714 don't have data
 ALIM 20200730 - 20200730 don't have data
 ALIM 20200715 - 20200715 don't have data
 ALIM 20200804 - 20200804 don't have data
 ALIM 20200720 - 20200720 don't have data
 ALIM 20200806 - 20200806 don't have data
 ALIM 20200723 - 20200723 don't have data
 ALIM 20200807 - 20200807 don't have data
 ALIM 20200728 - 20200728 don't have data
 ALIM 20200812 - 20200812 don't have data
 ALIM 20200731 - 20200731 don't have data
 ALIM 20200817 - 20200817 don't have data
 ALIM 20200803 - 20200803 don't have data
 ALIM 20200820 - 20200820 don't have data
 ALIM 20200805 - 20200805 don't have data
 ALIM 20200821 - 20200821 don't have data
 ALIM 20200810 - 20200810 don't have data
 ALIM 20200825 - 20200825 don't have data
 ALIM 20200811 - 20200811 don't have data
 ALIM 20200828 - 20200828 don't have data
 ALIM 20200813 - 20200813 don't have data
 ALIM 20200901 - 20200901 don't have data
 ALIM 20200814 - 20200814 don't have data
 ALIM 20200902 - 20200902 don't have data
 ALIM 20200818 - 20200818 don't have data
 ALIM 20200904 - 20200904 don't have data
 ALIM 20200819 - 20200819 don't have data
 ALIM 20200908 - 20200908 don't have data
 ALIM 20200824 - 20200824 don't have data
 ALIM 20200910 - 20200910 don't have data
 ALIM 20200826 - 20200826 don't have data
 ALIM 20200911 - 20200911 don't have data
 ALIM 20200915 - 20200915 don't have data
 ALIM 20200827 - 20200827 don't have data
 ALIM 20200916 - 20200916 don't have data
 ALIM 20200831 - 20200831 don't have data
 ALIM 20200918 - 20200918 don't have data
 ALIM 20200903 - 20200903 don't have data
 ALIM 20200921 - 20200921 don't have data
 ALIM 20200909 - 20200909 don't have data
 ALIM 20200924 - 20200924 don't have data
 ALIM 20200914 - 20200914 don't have data
 ALIM 20200929 - 20200929 don't have data
 ALIM 20200917 - 20200917 don't have data
 ALIM 20201001 - 20201001 don't have data
 ALIM 20201002 - 20201002 don't have data
 ALIM 20200922 - 20200922 don't have data
 ALIM 20201007 - 20201007 don't have data
 ALIM 20200923 - 20200923 don't have data
 ALIM 20201009 - 20201009 don't have data
 ALIM 20200925 - 20200925 don't have data
 ALIM 20201012 - 20201012 don't have data
 ALIM 20200928 - 20200928 don't have data
 ALIM 20201015 - 20201015 don't have data
 ALIM 20200930 - 20200930 don't have data
 ALIM 20201019 - 20201019 don't have data
 ALIM 20201005 - 20201005 don't have data
 ALIM 20201020 - 20201020 don't have data
 ALIM 20201006 - 20201006 don't have data
 ALIM 20201023 - 20201023 don't have data
 ALIM 20201028 - 20201028 don't have data
 ALIM 20201008 - 20201008 don't have data
 ALIM 20201102 - 20201102 don't have data
 ALIM 20201013 - 20201013 don't have data
 ALIM 20201105 - 20201105 don't have data
 ALIM 20201014 - 20201014 don't have data
 ALIM 20201110 - 20201110 don't have data
 ALIM 20201016 - 20201016 don't have data
 ALIM 20201111 - 20201111 don't have data
 ALIM 20201021 - 20201021 don't have data
 ALIM 20201113 - 20201113 don't have data
 ALIM 20201022 - 20201022 don't have data
 ALIM 20201118 - 20201118 don't have data
 ALIM 20201026 - 20201026 don't have data
 ALIM 20201119 - 20201119 don't have data
 ALIM 20201027 - 20201027 don't have data
 ALIM 20201123 - 20201123 don't have data
 ALIM 20201127 - 20201127 don't have data
 ALIM 20201029 - 20201029 don't have data
 ALIM 20201202 - 20201202 don't have data
 ALIM 20201030 - 20201030 don't have data
 ALIM 20201203 - 20201203 don't have data
 ALIM 20201103 - 20201103 don't have data
 ALIM 20201207 - 20201207 don't have data
 ALIM 20201104 - 20201104 don't have data
 ALIM 20201210 - 20201210 don't have data
 ALIM 20201106 - 20201106 don't have data
 ALIM 20201214 - 20201214 don't have data
 ALIM 20201109 - 20201109 don't have data
 ALIM 20201215 - 20201215 don't have data
 ALIM 20201112 - 20201112 don't have data
 ALIM 20201218 - 20201218 don't have data
 ALIM 20201116 - 20201116 don't have data
 ALIM 20201221 - 20201221 don't have data
 ALIM 20201117 - 20201117 don't have data
 ALIM 20201223 - 20201223 don't have data
 ALIM 20201120 - 20201120 don't have data
 ALIM 20201229 - 20201229 don't have data
 ALIM 20201230 - 20201230 don't have data
 ALIM 20201124 - 20201124 don't have data
 ALIM 20201125 - 20201125 don't have data
 ALIM 20201130 - 20201130 don't have data
 ALIM 20201201 - 20201201 don't have data
 ALIM 20201204 - 20201204 don't have data
 ALIM 20201208 - 20201208 don't have data
 ALIM 20201209 - 20201209 don't have data
 ALIM 20201211 - 20201211 don't have data
 ALIM 20201216 - 20201216 don't have data
 ALIM 20201217 - 20201217 don't have data
 ALIM 20201222 - 20201222 don't have data
 ALIM 20201224 - 20201224 don't have data
 ALIM 20201228 - 20201228 don't have data
 ALIM 20201231 - 20201231 don't have data

  0%|          | 0/253 [00:00<?, ?it/s]

 VIVE 20200102 - 20200102 don't have data
 VIVE 20200103 - 20200103 don't have data
 VIVE 20200107 - 20200107 don't have data
 VIVE 20200106 - 20200106 don't have data
 VIVE 20200110 - 20200110 don't have data
 VIVE 20200108 - 20200108 don't have data
 VIVE 20200114 - 20200114 don't have data
 VIVE 20200113 - 20200113 don't have data
 VIVE 20200117 - 20200117 don't have data
 VIVE 20200121 - 20200121 don't have data
 VIVE 20200115 - 20200115 don't have data
 VIVE 20200122 - 20200122 don't have data
 VIVE 20200116 - 20200116 don't have data
 VIVE 20200124 - 20200124 don't have data
 VIVE 20200109 - 20200109 don't have data
 VIVE 20200127 - 20200127 don't have data
 VIVE 20200123 - 20200123 don't have data
 VIVE 20200129 - 20200129 don't have data
 VIVE 20200128 - 20200128 don't have data
 VIVE 20200203 - 20200203 don't have data
 VIVE 20200130 - 20200130 don't have data
 VIVE 20200205 - 20200205 don't have data
 VIVE 20200131 - 20200131 don't have data
 VIVE 20200207 - 20200207 don't have data
 VIVE 20200204 - 20200204 don't have data
 VIVE 20200210 - 20200210 don't have data
 VIVE 20200212 - 20200212 don't have data
 VIVE 20200206 - 20200206 don't have data
 VIVE 20200213 - 20200213 don't have data
 VIVE 20200211 - 20200211 don't have data
 VIVE 20200218 - 20200218 don't have data
 VIVE 20200214 - 20200214 don't have data
 VIVE 20200221 - 20200221 don't have data
 VIVE 20200219 - 20200219 don't have data
 VIVE 20200224 - 20200224 don't have data
 VIVE 20200220 - 20200220 don't have data
 VIVE 20200226 - 20200226 don't have data
 VIVE 20200225 - 20200225 don't have data
 VIVE 20200228 - 20200228 don't have data
 VIVE 20200227 - 20200227 don't have data
 VIVE 20200302 - 20200302 don't have data
 VIVE 20200303 - 20200303 don't have data
 VIVE 20200305 - 20200305 don't have data
 VIVE 20200304 - 20200304 don't have data
 VIVE 20200309 - 20200309 don't have data
 VIVE 20200310 - 20200310 don't have data
 VIVE 20200306 - 20200306 don't have data
 VIVE 20200312 - 20200312 don't have data
 VIVE 20200311 - 20200311 don't have data
 VIVE 20200317 - 20200317 don't have data
 VIVE 20200313 - 20200313 don't have data
 VIVE 20200320 - 20200320 don't have data
 VIVE 20200316 - 20200316 don't have data
 VIVE 20200324 - 20200324 don't have data
 VIVE 20200318 - 20200318 don't have data
 VIVE 20200325 - 20200325 don't have data
 VIVE 20200319 - 20200319 don't have data
 VIVE 20200330 - 20200330 don't have data
 VIVE 20200323 - 20200323 don't have data
 VIVE 20200401 - 20200401 don't have data
 VIVE 20200326 - 20200326 don't have data
 VIVE 20200402 - 20200402 don't have data
 VIVE 20200406 - 20200406 don't have data
 VIVE 20200327 - 20200327 don't have data
 VIVE 20200409 - 20200409 don't have data
 VIVE 20200331 - 20200331 don't have data
 VIVE 20200414 - 20200414 don't have data
 VIVE 20200403 - 20200403 don't have data
 VIVE 20200415 - 20200415 don't have data
 VIVE 20200407 - 20200407 don't have data
 VIVE 20200417 - 20200417 don't have data
 VIVE 20200420 - 20200420 don't have data
 VIVE 20200408 - 20200408 don't have data
 VIVE 20200423 - 20200423 don't have data
 VIVE 20200413 - 20200413 don't have data
 VIVE 20200428 - 20200428 don't have data
 VIVE 20200416 - 20200416 don't have data
 VIVE 20200429 - 20200429 don't have data
 VIVE 20200421 - 20200421 don't have data
 VIVE 20200501 - 20200501 don't have data
 VIVE 20200422 - 20200422 don't have data
 VIVE 20200504 - 20200504 don't have data
 VIVE 20200506 - 20200506 don't have data
 VIVE 20200424 - 20200424 don't have data
 VIVE 20200507 - 20200507 don't have data
 VIVE 20200427 - 20200427 don't have data
 VIVE 20200512 - 20200512 don't have data
 VIVE 20200430 - 20200430 don't have data
 VIVE 20200514 - 20200514 don't have data
 VIVE 20200505 - 20200505 don't have data
 VIVE 20200515 - 20200515 don't have data
 VIVE 20200508 - 20200508 don't have data
 VIVE 20200520 - 20200520 don't have data
 VIVE 20200511 - 20200511 don't have data
 VIVE 20200522 - 20200522 don't have data
 VIVE 20200513 - 20200513 don't have data
 VIVE 20200526 - 20200526 don't have data
 VIVE 20200518 - 20200518 don't have data
 VIVE 20200528 - 20200528 don't have data
 VIVE 20200519 - 20200519 don't have data
 VIVE 20200529 - 20200529 don't have data
 VIVE 20200603 - 20200603 don't have data
 VIVE 20200521 - 20200521 don't have data
 VIVE 20200605 - 20200605 don't have data
 VIVE 20200527 - 20200527 don't have data
 VIVE 20200608 - 20200608 don't have data
 VIVE 20200601 - 20200601 don't have data
 VIVE 20200611 - 20200611 don't have data
 VIVE 20200602 - 20200602 don't have data
 VIVE 20200615 - 20200615 don't have data
 VIVE 20200604 - 20200604 don't have data
 VIVE 20200616 - 20200616 don't have data
 VIVE 20200609 - 20200609 don't have data
 VIVE 20200619 - 20200619 don't have data
 VIVE 20200610 - 20200610 don't have data
 VIVE 20200624 - 20200624 don't have data
 VIVE 20200625 - 20200625 don't have data
 VIVE 20200612 - 20200612 don't have data
 VIVE 20200630 - 20200630 don't have data
 VIVE 20200617 - 20200617 don't have data
 VIVE 20200702 - 20200702 don't have data
 VIVE 20200618 - 20200618 don't have data
 VIVE 20200706 - 20200706 don't have data
 VIVE 20200622 - 20200622 don't have data
 VIVE 20200709 - 20200709 don't have data
 VIVE 20200623 - 20200623 don't have data
 VIVE 20200714 - 20200714 don't have data
 VIVE 20200626 - 20200626 don't have data
 VIVE 20200716 - 20200716 don't have data
 VIVE 20200629 - 20200629 don't have data
 VIVE 20200717 - 20200717 don't have data
 VIVE 20200722 - 20200722 don't have data
 VIVE 20200701 - 20200701 don't have data
 VIVE 20200727 - 20200727 don't have data
 VIVE 20200707 - 20200707 don't have data
 VIVE 20200728 - 20200728 don't have data
 VIVE 20200708 - 20200708 don't have data
 VIVE 20200730 - 20200730 don't have data
 VIVE 20200710 - 20200710 don't have data
 VIVE 20200731 - 20200731 don't have data
 VIVE 20200713 - 20200713 don't have data
 VIVE 20200804 - 20200804 don't have data
 VIVE 20200715 - 20200715 don't have data
 VIVE 20200805 - 20200805 don't have data
 VIVE 20200807 - 20200807 don't have data
 VIVE 20200720 - 20200720 don't have data
 VIVE 20200810 - 20200810 don't have data
 VIVE 20200721 - 20200721 don't have data
 VIVE 20200812 - 20200812 don't have data
 VIVE 20200723 - 20200723 don't have data
 VIVE 20200813 - 20200813 don't have data
 VIVE 20200724 - 20200724 don't have data
 VIVE 20200818 - 20200818 don't have data
 VIVE 20200729 - 20200729 don't have data
 VIVE 20200819 - 20200819 don't have data
 VIVE 20200803 - 20200803 don't have data
 VIVE 20200821 - 20200821 don't have data
 VIVE 20200806 - 20200806 don't have data
 VIVE 20200824 - 20200824 don't have data
 VIVE 20200811 - 20200811 don't have data
 VIVE 20200826 - 20200826 don't have data
 VIVE 20200814 - 20200814 don't have data
 VIVE 20200827 - 20200827 don't have data
 VIVE 20200817 - 20200817 don't have data
 VIVE 20200831 - 20200831 don't have data
 VIVE 20200901 - 20200901 don't have data
 VIVE 20200820 - 20200820 don't have data
 VIVE 20200903 - 20200903 don't have data
 VIVE 20200825 - 20200825 don't have data
 VIVE 20200904 - 20200904 don't have data
 VIVE 20200828 - 20200828 don't have data
 VIVE 20200909 - 20200909 don't have data
 VIVE 20200902 - 20200902 don't have data
 VIVE 20200910 - 20200910 don't have data
 VIVE 20200908 - 20200908 don't have data
 VIVE 20200914 - 20200914 don't have data
 VIVE 20200911 - 20200911 don't have data
 VIVE 20200917 - 20200917 don't have data
 VIVE 20200915 - 20200915 don't have data
 VIVE 20200918 - 20200918 don't have data
 VIVE 20200916 - 20200916 don't have data
 VIVE 20200922 - 20200922 don't have data
 VIVE 20200921 - 20200921 don't have data
 VIVE 20200923 - 20200923 don't have data
 VIVE 20200924 - 20200924 don't have data
 VIVE 20200925 - 20200925 don't have data
 VIVE 20200928 - 20200928 don't have data
 VIVE 20200930 - 20200930 don't have data
 VIVE 20200929 - 20200929 don't have data
 VIVE 20201005 - 20201005 don't have data
 VIVE 20201001 - 20201001 don't have data
 VIVE 20201008 - 20201008 don't have data
 VIVE 20201002 - 20201002 don't have data
 VIVE 20201009 - 20201009 don't have data
 VIVE 20201006 - 20201006 don't have data
 VIVE 20201013 - 20201013 don't have data
 VIVE 20201007 - 20201007 don't have data
 VIVE 20201014 - 20201014 don't have data
 VIVE 20201012 - 20201012 don't have data
 VIVE 20201016 - 20201016 don't have data
 VIVE 20201015 - 20201015 don't have data
 VIVE 20201021 - 20201021 don't have data
 VIVE 20201019 - 20201019 don't have data
 VIVE 20201022 - 20201022 don't have data
 VIVE 20201020 - 20201020 don't have data
 VIVE 20201026 - 20201026 don't have data
 VIVE 20201029 - 20201029 don't have data
 VIVE 20201023 - 20201023 don't have data
 VIVE 20201030 - 20201030 don't have data
 VIVE 20201027 - 20201027 don't have data
 VIVE 20201103 - 20201103 don't have data
 VIVE 20201028 - 20201028 don't have data
 VIVE 20201106 - 20201106 don't have data
 VIVE 20201102 - 20201102 don't have data
 VIVE 20201110 - 20201110 don't have data
 VIVE 20201104 - 20201104 don't have data
 VIVE 20201111 - 20201111 don't have data
 VIVE 20201105 - 20201105 don't have data
 VIVE 20201116 - 20201116 don't have data
 VIVE 20201109 - 20201109 don't have data
 VIVE 20201119 - 20201119 don't have data
 VIVE 20201112 - 20201112 don't have data
 VIVE 20201124 - 20201124 don't have data
 VIVE 20201113 - 20201113 don't have data
 VIVE 20201125 - 20201125 don't have data
 VIVE 20201130 - 20201130 don't have data
 VIVE 20201117 - 20201117 don't have data
 VIVE 20201201 - 20201201 don't have data
 VIVE 20201118 - 20201118 don't have data
 VIVE 20201203 - 20201203 don't have data
 VIVE 20201120 - 20201120 don't have data
 VIVE 20201204 - 20201204 don't have data
 VIVE 20201123 - 20201123 don't have data
 VIVE 20201208 - 20201208 don't have data
 VIVE 20201127 - 20201127 don't have data
 VIVE 20201211 - 20201211 don't have data
 VIVE 20201202 - 20201202 don't have data
 VIVE 20201214 - 20201214 don't have data
 VIVE 20201207 - 20201207 don't have data
 VIVE 20201217 - 20201217 don't have data
 VIVE 20201209 - 20201209 don't have data
 VIVE 20201222 - 20201222 don't have data
 VIVE 20201210 - 20201210 don't have data
 VIVE 20201224 - 20201224 don't have data
 VIVE 20201215 - 20201215 don't have data
 VIVE 20201228 - 20201228 don't have data
 VIVE 20201231 - 20201231 don't have data
 VIVE 20201216 - 20201216 don't have data
 VIVE 20201218 - 20201218 don't have data
 VIVE 20201221 - 20201221 don't have data
 VIVE 20201223 - 20201223 don't have data
 VIVE 20201229 - 20201229 don't have data
 VIVE 20201230 - 20201230 don't have data

  0%|          | 0/253 [00:00<?, ?it/s]

  0%|          | 0/191 [00:00<?, ?it/s]

  0%|          | 0/253 [00:00<?, ?it/s]

 ALTM 20200102 - 20200102 don't have data
 ALTM 20200103 - 20200103 don't have data
 ALTM 20200108 - 20200108 don't have data
 ALTM 20200110 - 20200110 don't have data
 ALTM 20200109 - 20200109 don't have data
 ALTM 20200113 - 20200113 don't have data
 ALTM 20200114 - 20200114 don't have data
 ALTM 20200116 - 20200116 don't have data
 ALTM 20200115 - 20200115 don't have data
 ALTM 20200121 - 20200121 don't have data
 ALTM 20200117 - 20200117 don't have data
 ALTM 20200122 - 20200122 don't have data
 ALTM 20200106 - 20200106 don't have data
 ALTM 20200107 - 20200107 don't have data
 ALTM 20200123 - 20200123 don't have data
 ALTM 20200129 - 20200129 don't have data
 ALTM 20200127 - 20200127 don't have data
 ALTM 20200130 - 20200130 don't have data
 ALTM 20200128 - 20200128 don't have data
 ALTM 20200203 - 20200203 don't have data
 ALTM 20200124 - 20200124 don't have data
 ALTM 20200204 - 20200204 don't have data
 ALTM 20200205 - 20200205 don't have data
 ALTM 20200131 - 20200131 don't have data
 ALTM 20200207 - 20200207 don't have data
 ALTM 20200206 - 20200206 don't have data
 ALTM 20200211 - 20200211 don't have data
 ALTM 20200212 - 20200212 don't have data
 ALTM 20200210 - 20200210 don't have data
 ALTM 20200218 - 20200218 don't have data
 ALTM 20200213 - 20200213 don't have data
 ALTM 20200220 - 20200220 don't have data
 ALTM 20200214 - 20200214 don't have data
 ALTM 20200221 - 20200221 don't have data
 ALTM 20200219 - 20200219 don't have data
 ALTM 20200225 - 20200225 don't have data
 ALTM 20200224 - 20200224 don't have data
 ALTM 20200226 - 20200226 don't have data
 ALTM 20200227 - 20200227 don't have data
 ALTM 20200228 - 20200228 don't have data
 ALTM 20200304 - 20200304 don't have data
 ALTM 20200302 - 20200302 don't have data
 ALTM 20200306 - 20200306 don't have data
 ALTM 20200303 - 20200303 don't have data
 ALTM 20200309 - 20200309 don't have data
 ALTM 20200305 - 20200305 don't have data
 ALTM 20200312 - 20200312 don't have data
 ALTM 20200310 - 20200310 don't have data
 ALTM 20200316 - 20200316 don't have data
 ALTM 20200311 - 20200311 don't have data
 ALTM 20200317 - 20200317 don't have data
 ALTM 20200319 - 20200319 don't have data
 ALTM 20200313 - 20200313 don't have data
 ALTM 20200324 - 20200324 don't have data
 ALTM 20200318 - 20200318 don't have data
 ALTM 20200327 - 20200327 don't have data
 ALTM 20200320 - 20200320 don't have data
 ALTM 20200401 - 20200401 don't have data
 ALTM 20200323 - 20200323 don't have data
 ALTM 20200406 - 20200406 don't have data
 ALTM 20200325 - 20200325 don't have data
 ALTM 20200407 - 20200407 don't have data
 ALTM 20200326 - 20200326 don't have data
 ALTM 20200409 - 20200409 don't have data
 ALTM 20200413 - 20200413 don't have data
 ALTM 20200330 - 20200330 don't have data
 ALTM 20200415 - 20200415 don't have data
 ALTM 20200331 - 20200331 don't have data
 ALTM 20200416 - 20200416 don't have data
 ALTM 20200402 - 20200402 don't have data
 ALTM 20200420 - 20200420 don't have data
 ALTM 20200403 - 20200403 don't have data
 ALTM 20200421 - 20200421 don't have data
 ALTM 20200408 - 20200408 don't have data
 ALTM 20200424 - 20200424 don't have data
 ALTM 20200414 - 20200414 don't have data
 ALTM 20200429 - 20200429 don't have data
 ALTM 20200417 - 20200417 don't have data
 ALTM 20200430 - 20200430 don't have data
 ALTM 20200504 - 20200504 don't have data
 ALTM 20200422 - 20200422 don't have data
 ALTM 20200505 - 20200505 don't have data
 ALTM 20200423 - 20200423 don't have data
 ALTM 20200507 - 20200507 don't have data
 ALTM 20200427 - 20200427 don't have data
 ALTM 20200508 - 20200508 don't have data
 ALTM 20200428 - 20200428 don't have data
 ALTM 20200513 - 20200513 don't have data
 ALTM 20200501 - 20200501 don't have data
 ALTM 20200518 - 20200518 don't have data
 ALTM 20200506 - 20200506 don't have data
 ALTM 20200522 - 20200522 don't have data
 ALTM 20200527 - 20200527 don't have data
 ALTM 20200511 - 20200511 don't have data
 ALTM 20200528 - 20200528 don't have data
 ALTM 20200512 - 20200512 don't have data
 ALTM 20200601 - 20200601 don't have data
 ALTM 20200514 - 20200514 don't have data
 ALTM 20200604 - 20200604 don't have data
 ALTM 20200515 - 20200515 don't have data
 ALTM 20200605 - 20200605 don't have data
 ALTM 20200519 - 20200519 don't have data
 ALTM 20200609 - 20200609 don't have data
 ALTM 20200520 - 20200520 don't have data
 ALTM 20200610 - 20200610 don't have data
 ALTM 20200615 - 20200615 don't have data
 ALTM 20200521 - 20200521 don't have data
 ALTM 20200617 - 20200617 don't have data
 ALTM 20200526 - 20200526 don't have data
 ALTM 20200618 - 20200618 don't have data
 ALTM 20200529 - 20200529 don't have data
 ALTM 20200623 - 20200623 don't have data
 ALTM 20200602 - 20200602 don't have data
 ALTM 20200625 - 20200625 don't have data
 ALTM 20200603 - 20200603 don't have data
 ALTM 20200626 - 20200626 don't have data
 ALTM 20200608 - 20200608 don't have data
 ALTM 20200701 - 20200701 don't have data
 ALTM 20200707 - 20200707 don't have data
 ALTM 20200611 - 20200611 don't have data
 ALTM 20200708 - 20200708 don't have data
 ALTM 20200612 - 20200612 don't have data
 ALTM 20200713 - 20200713 don't have data
 ALTM 20200616 - 20200616 don't have data
 ALTM 20200715 - 20200715 don't have data
 ALTM 20200619 - 20200619 don't have data
 ALTM 20200716 - 20200716 don't have data
 ALTM 20200622 - 20200622 don't have data
 ALTM 20200721 - 20200721 don't have data
 ALTM 20200724 - 20200724 don't have data
 ALTM 20200624 - 20200624 don't have data
 ALTM 20200727 - 20200727 don't have data
 ALTM 20200629 - 20200629 don't have data
 ALTM 20200729 - 20200729 don't have data
 ALTM 20200630 - 20200630 don't have data
 ALTM 20200730 - 20200730 don't have data
 ALTM 20200702 - 20200702 don't have data
 ALTM 20200803 - 20200803 don't have data
 ALTM 20200804 - 20200804 don't have data
 ALTM 20200706 - 20200706 don't have data
 ALTM 20200806 - 20200806 don't have data
 ALTM 20200709 - 20200709 don't have data
 ALTM 20200807 - 20200807 don't have data
 ALTM 20200812 - 20200812 don't have data
 ALTM 20200710 - 20200710 don't have data
 ALTM 20200817 - 20200817 don't have data
 ALTM 20200714 - 20200714 don't have data
 ALTM 20200819 - 20200819 don't have data
 ALTM 20200717 - 20200717 don't have data
 ALTM 20200820 - 20200820 don't have data
 ALTM 20200720 - 20200720 don't have data
 ALTM 20200825 - 20200825 don't have data
 ALTM 20200722 - 20200722 don't have data
 ALTM 20200828 - 20200828 don't have data
 ALTM 20200723 - 20200723 don't have data
 ALTM 20200831 - 20200831 don't have data
 ALTM 20200728 - 20200728 don't have data
 ALTM 20200902 - 20200902 don't have data
 ALTM 20200731 - 20200731 don't have data
 ALTM 20200908 - 20200908 don't have data
 ALTM 20200805 - 20200805 don't have data
 ALTM 20200909 - 20200909 don't have data
 ALTM 20200810 - 20200810 don't have data
 ALTM 20200911 - 20200911 don't have data
 ALTM 20200811 - 20200811 don't have data
 ALTM 20200914 - 20200914 don't have data
 ALTM 20200813 - 20200813 don't have data
 ALTM 20200916 - 20200916 don't have data
 ALTM 20200814 - 20200814 don't have data
 ALTM 20200917 - 20200917 don't have data
 ALTM 20200818 - 20200818 don't have data
 ALTM 20200921 - 20200921 don't have data
 ALTM 20200922 - 20200922 don't have data
 ALTM 20200821 - 20200821 don't have data
 ALTM 20200925 - 20200925 don't have data
 ALTM 20200824 - 20200824 don't have data
 ALTM 20200930 - 20200930 don't have data
 ALTM 20200826 - 20200826 don't have data
 ALTM 20201005 - 20201005 don't have data
 ALTM 20200827 - 20200827 don't have data
 ALTM 20201006 - 20201006 don't have data
 ALTM 20200901 - 20200901 don't have data
 ALTM 20201008 - 20201008 don't have data
 ALTM 20200903 - 20200903 don't have data
 ALTM 20201009 - 20201009 don't have data
 ALTM 20200904 - 20200904 don't have data
 ALTM 20201012 - 20201012 don't have data
 ALTM 20201014 - 20201014 don't have data
 ALTM 20200910 - 20200910 don't have data
 ALTM 20201019 - 20201019 don't have data
 ALTM 20200915 - 20200915 don't have data
 ALTM 20201022 - 20201022 don't have data
 ALTM 20200918 - 20200918 don't have data
 ALTM 20201027 - 20201027 don't have data
 ALTM 20200923 - 20200923 don't have data
 ALTM 20201030 - 20201030 don't have data
 ALTM 20200924 - 20200924 don't have data
 ALTM 20201102 - 20201102 don't have data
 ALTM 20201104 - 20201104 don't have data
 ALTM 20200928 - 20200928 don't have data
 ALTM 20201105 - 20201105 don't have data
 ALTM 20200929 - 20200929 don't have data
 ALTM 20201110 - 20201110 don't have data
 ALTM 20201001 - 20201001 don't have data
 ALTM 20201112 - 20201112 don't have data
 ALTM 20201002 - 20201002 don't have data
 ALTM 20201113 - 20201113 don't have data
 ALTM 20201007 - 20201007 don't have data
 ALTM 20201118 - 20201118 don't have data
 ALTM 20201013 - 20201013 don't have data
 ALTM 20201120 - 20201120 don't have data
 ALTM 20201015 - 20201015 don't have data
 ALTM 20201123 - 20201123 don't have data
 ALTM 20201127 - 20201127 don't have data
 ALTM 20201016 - 20201016 don't have data
 ALTM 20201202 - 20201202 don't have data
 ALTM 20201020 - 20201020 don't have data
 ALTM 20201207 - 20201207 don't have data
 ALTM 20201021 - 20201021 don't have data
 ALTM 20201210 - 20201210 don't have data
 ALTM 20201023 - 20201023 don't have data
 ALTM 20201215 - 20201215 don't have data
 ALTM 20201026 - 20201026 don't have data
 ALTM 20201218 - 20201218 don't have data
 ALTM 20201028 - 20201028 don't have data
 ALTM 20201221 - 20201221 don't have data
 ALTM 20201029 - 20201029 don't have data
 ALTM 20201223 - 20201223 don't have data
 ALTM 20201103 - 20201103 don't have data
 ALTM 20201229 - 20201229 don't have data
 ALTM 20201106 - 20201106 don't have data
 ALTM 20201230 - 20201230 don't have data
 ALTM 20201109 - 20201109 don't have data
 ALTM 20201111 - 20201111 don't have data
 ALTM 20201116 - 20201116 don't have data
 ALTM 20201117 - 20201117 don't have data
 ALTM 20201119 - 20201119 don't have data
 ALTM 20201124 - 20201124 don't have data
 ALTM 20201125 - 20201125 don't have data
 ALTM 20201130 - 20201130 don't have data
 ALTM 20201201 - 20201201 don't have data
 ALTM 20201203 - 20201203 don't have data
 ALTM 20201204 - 20201204 don't have data
 ALTM 20201208 - 20201208 don't have data
 ALTM 20201209 - 20201209 don't have data
 ALTM 20201211 - 20201211 don't have data
 ALTM 20201214 - 20201214 don't have data
 ALTM 20201216 - 20201216 don't have data
 ALTM 20201217 - 20201217 don't have data
 ALTM 20201222 - 20201222 don't have data
 ALTM 20201224 - 20201224 don't have data
 ALTM 20201228 - 20201228 don't have data
 ALTM 20201231 - 20201231 don't have data

  0%|          | 0/253 [00:00<?, ?it/s]

  0%|          | 0/253 [00:00<?, ?it/s]

 OBLN 20200102 - 20200102 don't have data
 OBLN 20200106 - 20200106 don't have data
 OBLN 20200108 - 20200108 don't have data
 OBLN 20200103 - 20200103 don't have data
 OBLN 20200110 - 20200110 don't have data
 OBLN 20200107 - 20200107 don't have data
 OBLN 20200114 - 20200114 don't have data
 OBLN 20200113 - 20200113 don't have data
 OBLN 20200115 - 20200115 don't have data
 OBLN 20200109 - 20200109 don't have data
 OBLN 20200123 - 20200123 don't have data
 OBLN 20200116 - 20200116 don't have data
 OBLN 20200128 - 20200128 don't have data
 OBLN 20200117 - 20200117 don't have data
 OBLN 20200131 - 20200131 don't have data
 OBLN 20200124 - 20200124 don't have data
 OBLN 20200204 - 20200204 don't have data
 OBLN 20200121 - 20200121 don't have data
 OBLN 20200129 - 20200129 don't have data
 OBLN 20200205 - 20200205 don't have data
 OBLN 20200130 - 20200130 don't have data
 OBLN 20200207 - 20200207 don't have data
 OBLN 20200122 - 20200122 don't have data
 OBLN 20200211 - 20200211 don't have data
 OBLN 20200127 - 20200127 don't have data
 OBLN 20200212 - 20200212 don't have data
 OBLN 20200203 - 20200203 don't have data
 OBLN 20200214 - 20200214 don't have data
 OBLN 20200206 - 20200206 don't have data
 OBLN 20200220 - 20200220 don't have data
 OBLN 20200210 - 20200210 don't have data
 OBLN 20200225 - 20200225 don't have data
 OBLN 20200213 - 20200213 don't have data
 OBLN 20200227 - 20200227 don't have data
 OBLN 20200218 - 20200218 don't have data
 OBLN 20200228 - 20200228 don't have data
 OBLN 20200219 - 20200219 don't have data
 OBLN 20200303 - 20200303 don't have data
 OBLN 20200221 - 20200221 don't have data
 OBLN 20200306 - 20200306 don't have data
 OBLN 20200224 - 20200224 don't have data
 OBLN 20200310 - 20200310 don't have data
 OBLN 20200226 - 20200226 don't have data
 OBLN 20200311 - 20200311 don't have data
 OBLN 20200302 - 20200302 don't have data
 OBLN 20200313 - 20200313 don't have data
 OBLN 20200304 - 20200304 don't have data
 OBLN 20200318 - 20200318 don't have data
 OBLN 20200305 - 20200305 don't have data
 OBLN 20200323 - 20200323 don't have data
 OBLN 20200309 - 20200309 don't have data
 OBLN 20200325 - 20200325 don't have data
 OBLN 20200312 - 20200312 don't have data
 OBLN 20200330 - 20200330 don't have data
 OBLN 20200316 - 20200316 don't have data
 OBLN 20200402 - 20200402 don't have data
 OBLN 20200317 - 20200317 don't have data
 OBLN 20200406 - 20200406 don't have data
 OBLN 20200319 - 20200319 don't have data
 OBLN 20200407 - 20200407 don't have data
 OBLN 20200320 - 20200320 don't have data
 OBLN 20200409 - 20200409 don't have data
 OBLN 20200324 - 20200324 don't have data
 OBLN 20200413 - 20200413 don't have data
 OBLN 20200326 - 20200326 don't have data
 OBLN 20200415 - 20200415 don't have data
 OBLN 20200416 - 20200416 don't have data
 OBLN 20200327 - 20200327 don't have data
 OBLN 20200420 - 20200420 don't have data
 OBLN 20200331 - 20200331 don't have data
 OBLN 20200421 - 20200421 don't have data
 OBLN 20200401 - 20200401 don't have data
 OBLN 20200423 - 20200423 don't have data
 OBLN 20200403 - 20200403 don't have data
 OBLN 20200424 - 20200424 don't have data
 OBLN 20200408 - 20200408 don't have data
 OBLN 20200428 - 20200428 don't have data
 OBLN 20200414 - 20200414 don't have data
 OBLN 20200429 - 20200429 don't have data
 OBLN 20200501 - 20200501 don't have data
 OBLN 20200417 - 20200417 don't have data
 OBLN 20200504 - 20200504 don't have data
 OBLN 20200422 - 20200422 don't have data
 OBLN 20200507 - 20200507 don't have data
 OBLN 20200427 - 20200427 don't have data
 OBLN 20200511 - 20200511 don't have data
 OBLN 20200430 - 20200430 don't have data
 OBLN 20200512 - 20200512 don't have data
 OBLN 20200505 - 20200505 don't have data
 OBLN 20200515 - 20200515 don't have data
 OBLN 20200506 - 20200506 don't have data
 OBLN 20200519 - 20200519 don't have data
 OBLN 20200520 - 20200520 don't have data
 OBLN 20200508 - 20200508 don't have data
 OBLN 20200522 - 20200522 don't have data
 OBLN 20200513 - 20200513 don't have data
 OBLN 20200526 - 20200526 don't have data
 OBLN 20200514 - 20200514 don't have data
 OBLN 20200528 - 20200528 don't have data
 OBLN 20200518 - 20200518 don't have data
 OBLN 20200602 - 20200602 don't have data
 OBLN 20200521 - 20200521 don't have data
 OBLN 20200603 - 20200603 don't have data
 OBLN 20200527 - 20200527 don't have data
 OBLN 20200605 - 20200605 don't have data
 OBLN 20200608 - 20200608 don't have data
 OBLN 20200529 - 20200529 don't have data
 OBLN 20200610 - 20200610 don't have data
 OBLN 20200601 - 20200601 don't have data
 OBLN 20200615 - 20200615 don't have data
 OBLN 20200604 - 20200604 don't have data
 OBLN 20200618 - 20200618 don't have data
 OBLN 20200609 - 20200609 don't have data
 OBLN 20200623 - 20200623 don't have data
 OBLN 20200611 - 20200611 don't have data
 OBLN 20200626 - 20200626 don't have data
 OBLN 20200612 - 20200612 don't have data
 OBLN 20200630 - 20200630 don't have data
 OBLN 20200616 - 20200616 don't have data
 OBLN 20200701 - 20200701 don't have data
 OBLN 20200706 - 20200706 don't have data
 OBLN 20200617 - 20200617 don't have data
 OBLN 20200709 - 20200709 don't have data
 OBLN 20200619 - 20200619 don't have data
 OBLN 20200710 - 20200710 don't have data
 OBLN 20200622 - 20200622 don't have data
 OBLN 20200714 - 20200714 don't have data
 OBLN 20200624 - 20200624 don't have data
 OBLN 20200717 - 20200717 don't have data
 OBLN 20200625 - 20200625 don't have data
 OBLN 20200722 - 20200722 don't have data
 OBLN 20200629 - 20200629 don't have data
 OBLN 20200724 - 20200724 don't have data
 OBLN 20200702 - 20200702 don't have data
 OBLN 20200727 - 20200727 don't have data
 OBLN 20200707 - 20200707 don't have data
 OBLN 20200730 - 20200730 don't have data
 OBLN 20200708 - 20200708 don't have data
 OBLN 20200803 - 20200803 don't have data
 OBLN 20200713 - 20200713 don't have data
 OBLN 20200804 - 20200804 don't have data
 OBLN 20200715 - 20200715 don't have data
 OBLN 20200807 - 20200807 don't have data
 OBLN 20200811 - 20200811 don't have data
 OBLN 20200716 - 20200716 don't have data
 OBLN 20200812 - 20200812 don't have data
 OBLN 20200720 - 20200720 don't have data
 OBLN 20200817 - 20200817 don't have data
 OBLN 20200721 - 20200721 don't have data
 OBLN 20200820 - 20200820 don't have data
 OBLN 20200723 - 20200723 don't have data
 OBLN 20200825 - 20200825 don't have data
 OBLN 20200728 - 20200728 don't have data
 OBLN 20200828 - 20200828 don't have data
 OBLN 20200729 - 20200729 don't have data
 OBLN 20200831 - 20200831 don't have data
 OBLN 20200902 - 20200902 don't have data
 OBLN 20200731 - 20200731 don't have data
 OBLN 20200903 - 20200903 don't have data
 OBLN 20200805 - 20200805 don't have data
 OBLN 20200908 - 20200908 don't have data
 OBLN 20200806 - 20200806 don't have data
 OBLN 20200909 - 20200909 don't have data
 OBLN 20200810 - 20200810 don't have data
 OBLN 20200911 - 20200911 don't have data
 OBLN 20200813 - 20200813 don't have data
 OBLN 20200914 - 20200914 don't have data
 OBLN 20200814 - 20200814 don't have data
 OBLN 20200916 - 20200916 don't have data
 OBLN 20200818 - 20200818 don't have data
 OBLN 20200921 - 20200921 don't have data
 OBLN 20200819 - 20200819 don't have data
 OBLN 20200922 - 20200922 don't have data
 OBLN 20200821 - 20200821 don't have data
 OBLN 20200924 - 20200924 don't have data
 OBLN 20200824 - 20200824 don't have data
 OBLN 20200929 - 20200929 don't have data
 OBLN 20200826 - 20200826 don't have data
 OBLN 20201002 - 20201002 don't have data
 OBLN 20200827 - 20200827 don't have data
 OBLN 20201006 - 20201006 don't have data
 OBLN 20200901 - 20200901 don't have data
 OBLN 20201007 - 20201007 don't have data
 OBLN 20200904 - 20200904 don't have data
 OBLN 20201009 - 20201009 don't have data
 OBLN 20200910 - 20200910 don't have data
 OBLN 20201014 - 20201014 don't have data
 OBLN 20200915 - 20200915 don't have data
 OBLN 20201019 - 20201019 don't have data
 OBLN 20200917 - 20200917 don't have data
 OBLN 20201022 - 20201022 don't have data
 OBLN 20200918 - 20200918 don't have data
 OBLN 20201023 - 20201023 don't have data
 OBLN 20201027 - 20201027 don't have data
 OBLN 20200923 - 20200923 don't have data
 OBLN 20201028 - 20201028 don't have data
 OBLN 20200925 - 20200925 don't have data
 OBLN 20201030 - 20201030 don't have data
 OBLN 20200928 - 20200928 don't have data
 OBLN 20201102 - 20201102 don't have data
 OBLN 20200930 - 20200930 don't have data
 OBLN 20201105 - 20201105 don't have data
 OBLN 20201001 - 20201001 don't have data
 OBLN 20201106 - 20201106 don't have data
 OBLN 20201110 - 20201110 don't have data
 OBLN 20201005 - 20201005 don't have data
 OBLN 20201111 - 20201111 don't have data
 OBLN 20201008 - 20201008 don't have data
 OBLN 20201116 - 20201116 don't have data
 OBLN 20201012 - 20201012 don't have data
 OBLN 20201118 - 20201118 don't have data
 OBLN 20201013 - 20201013 don't have data
 OBLN 20201119 - 20201119 don't have data
 OBLN 20201015 - 20201015 don't have data
 OBLN 20201124 - 20201124 don't have data
 OBLN 20201125 - 20201125 don't have data
 OBLN 20201016 - 20201016 don't have data
 OBLN 20201130 - 20201130 don't have data
 OBLN 20201020 - 20201020 don't have data
 OBLN 20201021 - 20201021 don't have data
 OBLN 20201204 - 20201204 don't have data
 OBLN 20201026 - 20201026 don't have data
 OBLN 20201209 - 20201209 don't have data
 OBLN 20201029 - 20201029 don't have data
 OBLN 20201214 - 20201214 don't have data
 OBLN 20201103 - 20201103 don't have data
 OBLN 20201215 - 20201215 don't have data
 OBLN 20201104 - 20201104 don't have data
 OBLN 20201217 - 20201217 don't have data
 OBLN 20201222 - 20201222 don't have data
 OBLN 20201109 - 20201109 don't have data
 OBLN 20201223 - 20201223 don't have data
 OBLN 20201112 - 20201112 don't have data
 OBLN 20201228 - 20201228 don't have data
 OBLN 20201113 - 20201113 don't have data
 OBLN 20201231 - 20201231 don't have data
 OBLN 20201117 - 20201117 don't have data
 OBLN 20201120 - 20201120 don't have data
 OBLN 20201123 - 20201123 don't have data
 OBLN 20201127 - 20201127 don't have data
 OBLN 20201201 - 20201201 don't have data
 OBLN 20201202 - 20201202 don't have data
 OBLN 20201203 - 20201203 don't have data
 OBLN 20201207 - 20201207 don't have data
 OBLN 20201208 - 20201208 don't have data
 OBLN 20201210 - 20201210 don't have data
 OBLN 20201211 - 20201211 don't have data
 OBLN 20201216 - 20201216 don't have data
 OBLN 20201218 - 20201218 don't have data
 OBLN 20201221 - 20201221 don't have data
 OBLN 20201224 - 20201224 don't have data
 OBLN 20201229 - 20201229 don't have data
 OBLN 20201230 - 20201230 don't have data

  0%|          | 0/253 [00:00<?, ?it/s]

  0%|          | 0/253 [00:00<?, ?it/s]

  0%|          | 0/253 [00:00<?, ?it/s]

 LW 20200106 - 20200106 don't have data
 LW 20200102 - 20200102 don't have data
 LW 20200108 - 20200108 don't have data
 LW 20200103 - 20200103 don't have data
 LW 20200109 - 20200109 don't have data
 LW 20200107 - 20200107 don't have data
 LW 20200113 - 20200113 don't have data
 LW 20200110 - 20200110 don't have data
 LW 20200116 - 20200116 don't have data
 LW 20200114 - 20200114 don't have data
 LW 20200122 - 20200122 don't have data
 LW 20200117 - 20200117 don't have data
 LW 20200128 - 20200128 don't have data
 LW 20200123 - 20200123 don't have data
 LW 20200129 - 20200129 don't have data
 LW 20200124 - 20200124 don't have data
 LW 20200204 - 20200204 don't have data
 LW 20200127 - 20200127 don't have data
 LW 20200115 - 20200115 don't have data
 LW 20200203 - 20200203 don't have data
 LW 20200121 - 20200121 don't have data
 LW 20200130 - 20200130 don't have data
 LW 20200206 - 20200206 don't have data
 LW 20200205 - 20200205 don't have data
 LW 20200211 - 20200211 don't have data
 LW 20200131 - 20200131 don't have data
 LW 20200213 - 20200213 don't have data
 LW 20200207 - 20200207 don't have data
 LW 20200214 - 20200214 don't have data
 LW 20200210 - 20200210 don't have data
 LW 20200219 - 20200219 don't have data
 LW 20200212 - 20200212 don't have data
 LW 20200221 - 20200221 don't have data
 LW 20200218 - 20200218 don't have data
 LW 20200224 - 20200224 don't have data
 LW 20200220 - 20200220 don't have data
 LW 20200226 - 20200226 don't have data
 LW 20200225 - 20200225 don't have data
 LW 20200302 - 20200302 don't have data
 LW 20200227 - 20200227 don't have data
 LW 20200304 - 20200304 don't have data
 LW 20200228 - 20200228 don't have data
 LW 20200305 - 20200305 don't have data
 LW 20200303 - 20200303 don't have data
 LW 20200306 - 20200306 don't have data

  0%|          | 0/253 [00:00<?, ?it/s]

  0%|          | 0/253 [00:00<?, ?it/s]

 LIFE 20200106 - 20200106 don't have data
 LIFE 20200103 - 20200103 don't have data
 LIFE 20200108 - 20200108 don't have data
 LIFE 20200102 - 20200102 don't have data
 LIFE 20200113 - 20200113 don't have data
 LIFE 20200107 - 20200107 don't have data
 LIFE 20200114 - 20200114 don't have data
 LIFE 20200110 - 20200110 don't have data
 LIFE 20200117 - 20200117 don't have data
 LIFE 20200109 - 20200109 don't have data
 LIFE 20200122 - 20200122 don't have data
 LIFE 20200116 - 20200116 don't have data
 LIFE 20200127 - 20200127 don't have data
 LIFE 20200115 - 20200115 don't have data
 LIFE 20200128 - 20200128 don't have data
 LIFE 20200123 - 20200123 don't have data
 LIFE 20200124 - 20200124 don't have data
 LIFE 20200203 - 20200203 don't have data
 LIFE 20200121 - 20200121 don't have data
 LIFE 20200131 - 20200131 don't have data
 LIFE 20200129 - 20200129 don't have data
 LIFE 20200207 - 20200207 don't have data
 LIFE 20200130 - 20200130 don't have data
 LIFE 20200210 - 20200210 don't have data
 LIFE 20200204 - 20200204 don't have data
 LIFE 20200212 - 20200212 don't have data
 LIFE 20200205 - 20200205 don't have data
 LIFE 20200214 - 20200214 don't have data
 LIFE 20200206 - 20200206 don't have data
 LIFE 20200218 - 20200218 don't have data
 LIFE 20200211 - 20200211 don't have data
 LIFE 20200220 - 20200220 don't have data
 LIFE 20200213 - 20200213 don't have data
 LIFE 20200221 - 20200221 don't have data
 LIFE 20200219 - 20200219 don't have data
 LIFE 20200225 - 20200225 don't have data
 LIFE 20200224 - 20200224 don't have data
 LIFE 20200227 - 20200227 don't have data
 LIFE 20200226 - 20200226 don't have data
 LIFE 20200228 - 20200228 don't have data
 LIFE 20200302 - 20200302 don't have data
 LIFE 20200303 - 20200303 don't have data
 LIFE 20200304 - 20200304 don't have data
 LIFE 20200306 - 20200306 don't have data
 LIFE 20200305 - 20200305 don't have data
 LIFE 20200311 - 20200311 don't have data
 LIFE 20200309 - 20200309 don't have data
 LIFE 20200313 - 20200313 don't have data
 LIFE 20200310 - 20200310 don't have data
 LIFE 20200316 - 20200316 don't have data
 LIFE 20200312 - 20200312 don't have data
 LIFE 20200318 - 20200318 don't have data
 LIFE 20200317 - 20200317 don't have data
 LIFE 20200323 - 20200323 don't have data
 LIFE 20200319 - 20200319 don't have data
 LIFE 20200325 - 20200325 don't have data
 LIFE 20200326 - 20200326 don't have data
 LIFE 20200320 - 20200320 don't have data
 LIFE 20200330 - 20200330 don't have data
 LIFE 20200324 - 20200324 don't have data
 LIFE 20200402 - 20200402 don't have data
 LIFE 20200327 - 20200327 don't have data
 LIFE 20200407 - 20200407 don't have data
 LIFE 20200331 - 20200331 don't have data
 LIFE 20200413 - 20200413 don't have data
 LIFE 20200401 - 20200401 don't have data
 LIFE 20200415 - 20200415 don't have data
 LIFE 20200403 - 20200403 don't have data
 LIFE 20200416 - 20200416 don't have data
 LIFE 20200406 - 20200406 don't have data
 LIFE 20200420 - 20200420 don't have data
 LIFE 20200408 - 20200408 don't have data
 LIFE 20200421 - 20200421 don't have data
 LIFE 20200423 - 20200423 don't have data
 LIFE 20200409 - 20200409 don't have data
 LIFE 20200424 - 20200424 don't have data
 LIFE 20200414 - 20200414 don't have data
 LIFE 20200429 - 20200429 don't have data
 LIFE 20200417 - 20200417 don't have data
 LIFE 20200501 - 20200501 don't have data
 LIFE 20200422 - 20200422 don't have data
 LIFE 20200504 - 20200504 don't have data
 LIFE 20200427 - 20200427 don't have data
 LIFE 20200506 - 20200506 don't have data
 LIFE 20200428 - 20200428 don't have data
 LIFE 20200507 - 20200507 don't have data
 LIFE 20200430 - 20200430 don't have data
 LIFE 20200511 - 20200511 don't have data
 LIFE 20200505 - 20200505 don't have data
 LIFE 20200512 - 20200512 don't have data
 LIFE 20200508 - 20200508 don't have data
 LIFE 20200514 - 20200514 don't have data
 LIFE 20200513 - 20200513 don't have data
 LIFE 20200515 - 20200515 don't have data
 LIFE 20200518 - 20200518 don't have data
 LIFE 20200520 - 20200520 don't have data
 LIFE 20200522 - 20200522 don't have data
 LIFE 20200519 - 20200519 don't have data
 LIFE 20200526 - 20200526 don't have data
 LIFE 20200521 - 20200521 don't have data
 LIFE 20200528 - 20200528 don't have data
 LIFE 20200527 - 20200527 don't have data
 LIFE 20200529 - 20200529 don't have data
 LIFE 20200601 - 20200601 don't have data
 LIFE 20200602 - 20200602 don't have data
 LIFE 20200604 - 20200604 don't have data
 LIFE 20200603 - 20200603 don't have data
 LIFE 20200609 - 20200609 don't have data
 LIFE 20200605 - 20200605 don't have data
 LIFE 20200611 - 20200611 don't have data
 LIFE 20200608 - 20200608 don't have data
 LIFE 20200612 - 20200612 don't have data
 LIFE 20200610 - 20200610 don't have data
 LIFE 20200617 - 20200617 don't have data
 LIFE 20200615 - 20200615 don't have data
 LIFE 20200619 - 20200619 don't have data
 LIFE 20200616 - 20200616 don't have data
 LIFE 20200622 - 20200622 don't have data
 LIFE 20200618 - 20200618 don't have data
 LIFE 20200624 - 20200624 don't have data
 LIFE 20200623 - 20200623 don't have data
 LIFE 20200629 - 20200629 don't have data
 LIFE 20200625 - 20200625 don't have data
 LIFE 20200702 - 20200702 don't have data
 LIFE 20200626 - 20200626 don't have data
 LIFE 20200707 - 20200707 don't have data
 LIFE 20200630 - 20200630 don't have data
 LIFE 20200708 - 20200708 don't have data
 LIFE 20200701 - 20200701 don't have data
 LIFE 20200713 - 20200713 don't have data
 LIFE 20200706 - 20200706 don't have data
 LIFE 20200716 - 20200716 don't have data
 LIFE 20200709 - 20200709 don't have data
 LIFE 20200710 - 20200710 don't have data
 LIFE 20200720 - 20200720 don't have data
 LIFE 20200714 - 20200714 don't have data
 LIFE 20200721 - 20200721 don't have data
 LIFE 20200715 - 20200715 don't have data
 LIFE 20200723 - 20200723 don't have data
 LIFE 20200717 - 20200717 don't have data
 LIFE 20200724 - 20200724 don't have data
 LIFE 20200722 - 20200722 don't have data
 LIFE 20200728 - 20200728 don't have data
 LIFE 20200727 - 20200727 don't have data
 LIFE 20200731 - 20200731 don't have data
 LIFE 20200729 - 20200729 don't have data
 LIFE 20200803 - 20200803 don't have data
 LIFE 20200730 - 20200730 don't have data
 LIFE 20200805 - 20200805 don't have data
 LIFE 20200804 - 20200804 don't have data
 LIFE 20200810 - 20200810 don't have data
 LIFE 20200806 - 20200806 don't have data
 LIFE 20200812 - 20200812 don't have data
 LIFE 20200807 - 20200807 don't have data
 LIFE 20200813 - 20200813 don't have data
 LIFE 20200811 - 20200811 don't have data
 LIFE 20200817 - 20200817 don't have data
 LIFE 20200814 - 20200814 don't have data
 LIFE 20200818 - 20200818 don't have data
 LIFE 20200819 - 20200819 don't have data
 LIFE 20200820 - 20200820 don't have data
 LIFE 20200821 - 20200821 don't have data
 LIFE 20200825 - 20200825 don't have data
 LIFE 20200824 - 20200824 don't have data
 LIFE 20200827 - 20200827 don't have data
 LIFE 20200826 - 20200826 don't have data
 LIFE 20200831 - 20200831 don't have data
 LIFE 20200828 - 20200828 don't have data
 LIFE 20200903 - 20200903 don't have data
 LIFE 20200901 - 20200901 don't have data
 LIFE 20200908 - 20200908 don't have data
 LIFE 20200902 - 20200902 don't have data
 LIFE 20200909 - 20200909 don't have data
 LIFE 20200904 - 20200904 don't have data
 LIFE 20200911 - 20200911 don't have data
 LIFE 20200910 - 20200910 don't have data
 LIFE 20200914 - 20200914 don't have data
 LIFE 20200916 - 20200916 don't have data
 LIFE 20200915 - 20200915 don't have data
 LIFE 20200921 - 20200921 don't have data
 LIFE 20200917 - 20200917 don't have data
 LIFE 20200923 - 20200923 don't have data
 LIFE 20200918 - 20200918 don't have data
 LIFE 20200924 - 20200924 don't have data
 LIFE 20200922 - 20200922 don't have data
 LIFE 20200928 - 20200928 don't have data
 LIFE 20200925 - 20200925 don't have data
 LIFE 20200929 - 20200929 don't have data
 LIFE 20200930 - 20200930 don't have data
 LIFE 20201001 - 20201001 don't have data
 LIFE 20201005 - 20201005 don't have data
 LIFE 20201002 - 20201002 don't have data
 LIFE 20201007 - 20201007 don't have data
 LIFE 20201006 - 20201006 don't have data
 LIFE 20201009 - 20201009 don't have data
 LIFE 20201008 - 20201008 don't have data
 LIFE 20201014 - 20201014 don't have data
 LIFE 20201012 - 20201012 don't have data
 LIFE 20201016 - 20201016 don't have data
 LIFE 20201013 - 20201013 don't have data
 LIFE 20201019 - 20201019 don't have data
 LIFE 20201015 - 20201015 don't have data
 LIFE 20201021 - 20201021 don't have data
 LIFE 20201020 - 20201020 don't have data
 LIFE 20201022 - 20201022 don't have data
 LIFE 20201026 - 20201026 don't have data
 LIFE 20201023 - 20201023 don't have data
 LIFE 20201027 - 20201027 don't have data
 LIFE 20201028 - 20201028 don't have data
 LIFE 20201029 - 20201029 don't have data
 LIFE 20201030 - 20201030 don't have data
 LIFE 20201103 - 20201103 don't have data
 LIFE 20201102 - 20201102 don't have data
 LIFE 20201106 - 20201106 don't have data
 LIFE 20201104 - 20201104 don't have data
 LIFE 20201110 - 20201110 don't have data
 LIFE 20201105 - 20201105 don't have data
 LIFE 20201111 - 20201111 don't have data
 LIFE 20201109 - 20201109 don't have data
 LIFE 20201113 - 20201113 don't have data
 LIFE 20201112 - 20201112 don't have data
 LIFE 20201116 - 20201116 don't have data
 LIFE 20201117 - 20201117 don't have data
 LIFE 20201118 - 20201118 don't have data
 LIFE 20201120 - 20201120 don't have data
 LIFE 20201119 - 20201119 don't have data
 LIFE 20201125 - 20201125 don't have data
 LIFE 20201123 - 20201123 don't have data
 LIFE 20201130 - 20201130 don't have data
 LIFE 20201124 - 20201124 don't have data
 LIFE 20201127 - 20201127 don't have data
 LIFE 20201201 - 20201201 don't have data
 LIFE 20201202 - 20201202 don't have data
 LIFE 20201203 - 20201203 don't have data
 LIFE 20201207 - 20201207 don't have data
 LIFE 20201204 - 20201204 don't have data
 LIFE 20201210 - 20201210 don't have data
 LIFE 20201208 - 20201208 don't have data
 LIFE 20201215 - 20201215 don't have data
 LIFE 20201209 - 20201209 don't have data
 LIFE 20201218 - 20201218 don't have data
 LIFE 20201211 - 20201211 don't have data
 LIFE 20201223 - 20201223 don't have data
 LIFE 20201214 - 20201214 don't have data
 LIFE 20201229 - 20201229 don't have data
 LIFE 20201216 - 20201216 don't have data
 LIFE 20201217 - 20201217 don't have data
 LIFE 20201221 - 20201221 don't have data
 LIFE 20201222 - 20201222 don't have data
 LIFE 20201224 - 20201224 don't have data
 LIFE 20201228 - 20201228 don't have data
 LIFE 20201230 - 20201230 don't have data
 LIFE 20201231 - 20201231 don't have data

  0%|          | 0/31 [00:00<?, ?it/s]

  0%|          | 0/253 [00:00<?, ?it/s]

  0%|          | 0/253 [00:00<?, ?it/s]

  0%|          | 0/253 [00:00<?, ?it/s]

  0%|          | 0/253 [00:00<?, ?it/s]

 CGIX 20200106 - 20200106 don't have data
 CGIX 20200102 - 20200102 don't have data
 CGIX 20200107 - 20200107 don't have data
 CGIX 20200103 - 20200103 don't have data
 CGIX 20200109 - 20200109 don't have data
 CGIX 20200108 - 20200108 don't have data
 CGIX 20200114 - 20200114 don't have data
 CGIX 20200113 - 20200113 don't have data
 CGIX 20200115 - 20200115 don't have data
 CGIX 20200110 - 20200110 don't have data
 CGIX 20200117 - 20200117 don't have data
 CGIX 20200116 - 20200116 don't have data
 CGIX 20200122 - 20200122 don't have data
 CGIX 20200121 - 20200121 don't have data
 CGIX 20200128 - 20200128 don't have data
 CGIX 20200123 - 20200123 don't have data
 CGIX 20200127 - 20200127 don't have data
 CGIX 20200124 - 20200124 don't have data
 CGIX 20200130 - 20200130 don't have data
 CGIX 20200129 - 20200129 don't have data
 CGIX 20200203 - 20200203 don't have data
 CGIX 20200131 - 20200131 don't have data
 CGIX 20200204 - 20200204 don't have data
 CGIX 20200206 - 20200206 don't have data
 CGIX 20200205 - 20200205 don't have data
 CGIX 20200210 - 20200210 don't have data
 CGIX 20200207 - 20200207 don't have data
 CGIX 20200211 - 20200211 don't have data
 CGIX 20200212 - 20200212 don't have data
 CGIX 20200213 - 20200213 don't have data
 CGIX 20200214 - 20200214 don't have data
 CGIX 20200218 - 20200218 don't have data
 CGIX 20200220 - 20200220 don't have data
 CGIX 20200219 - 20200219 don't have data
 CGIX 20200221 - 20200221 don't have data
 CGIX 20200224 - 20200224 don't have data
 CGIX 20200225 - 20200225 don't have data
 CGIX 20200226 - 20200226 don't have data
 CGIX 20200227 - 20200227 don't have data
 CGIX 20200302 - 20200302 don't have data
 CGIX 20200228 - 20200228 don't have data
 CGIX 20200305 - 20200305 don't have data
 CGIX 20200303 - 20200303 don't have data
 CGIX 20200309 - 20200309 don't have data
 CGIX 20200304 - 20200304 don't have data
 CGIX 20200310 - 20200310 don't have data
 CGIX 20200312 - 20200312 don't have data
 CGIX 20200306 - 20200306 don't have data
 CGIX 20200313 - 20200313 don't have data
 CGIX 20200311 - 20200311 don't have data
 CGIX 20200317 - 20200317 don't have data
 CGIX 20200316 - 20200316 don't have data
 CGIX 20200318 - 20200318 don't have data
 CGIX 20200319 - 20200319 don't have data
 CGIX 20200320 - 20200320 don't have data
 CGIX 20200323 - 20200323 don't have data
 CGIX 20200324 - 20200324 don't have data
 CGIX 20200326 - 20200326 don't have data
 CGIX 20200325 - 20200325 don't have data
 CGIX 20200331 - 20200331 don't have data
 CGIX 20200327 - 20200327 don't have data
 CGIX 20200402 - 20200402 don't have data
 CGIX 20200330 - 20200330 don't have data
 CGIX 20200403 - 20200403 don't have data
 CGIX 20200401 - 20200401 don't have data
 CGIX 20200407 - 20200407 don't have data
 CGIX 20200406 - 20200406 don't have data
 CGIX 20200413 - 20200413 don't have data
 CGIX 20200408 - 20200408 don't have data
 CGIX 20200414 - 20200414 don't have data
 CGIX 20200409 - 20200409 don't have data
 CGIX 20200416 - 20200416 don't have data
 CGIX 20200415 - 20200415 don't have data
 CGIX 20200421 - 20200421 don't have data
 CGIX 20200417 - 20200417 don't have data
 CGIX 20200424 - 20200424 don't have data
 CGIX 20200420 - 20200420 don't have data
 CGIX 20200429 - 20200429 don't have data
 CGIX 20200422 - 20200422 don't have data
 CGIX 20200423 - 20200423 don't have data
 CGIX 20200504 - 20200504 don't have data
 CGIX 20200427 - 20200427 don't have data
 CGIX 20200507 - 20200507 don't have data
 CGIX 20200428 - 20200428 don't have data
 CGIX 20200512 - 20200512 don't have data
 CGIX 20200430 - 20200430 don't have data
 CGIX 20200515 - 20200515 don't have data
 CGIX 20200501 - 20200501 don't have data
 CGIX 20200520 - 20200520 don't have data
 CGIX 20200505 - 20200505 don't have data
 CGIX 20200522 - 20200522 don't have data
 CGIX 20200506 - 20200506 don't have data
 CGIX 20200526 - 20200526 don't have data
 CGIX 20200508 - 20200508 don't have data
 CGIX 20200511 - 20200511 don't have data
 CGIX 20200528 - 20200528 don't have data
 CGIX 20200513 - 20200513 don't have data
 CGIX 20200602 - 20200602 don't have data
 CGIX 20200514 - 20200514 don't have data
 CGIX 20200603 - 20200603 don't have data
 CGIX 20200518 - 20200518 don't have data
 CGIX 20200605 - 20200605 don't have data
 CGIX 20200519 - 20200519 don't have data
 CGIX 20200608 - 20200608 don't have data
 CGIX 20200521 - 20200521 don't have data
 CGIX 20200611 - 20200611 don't have data
 CGIX 20200527 - 20200527 don't have data
 CGIX 20200615 - 20200615 don't have data
 CGIX 20200529 - 20200529 don't have data
 CGIX 20200616 - 20200616 don't have data
 CGIX 20200601 - 20200601 don't have data
 CGIX 20200619 - 20200619 don't have data
 CGIX 20200604 - 20200604 don't have data
 CGIX 20200609 - 20200609 don't have data
 CGIX 20200624 - 20200624 don't have data
 CGIX 20200610 - 20200610 don't have data
 CGIX 20200629 - 20200629 don't have data
 CGIX 20200612 - 20200612 don't have data
 CGIX 20200702 - 20200702 don't have data
 CGIX 20200617 - 20200617 don't have data
 CGIX 20200708 - 20200708 don't have data
 CGIX 20200713 - 20200713 don't have data
 CGIX 20200618 - 20200618 don't have data
 CGIX 20200622 - 20200622 don't have data
 CGIX 20200716 - 20200716 don't have data
 CGIX 20200623 - 20200623 don't have data
 CGIX 20200721 - 20200721 don't have data
 CGIX 20200625 - 20200625 don't have data
 CGIX 20200722 - 20200722 don't have data
 CGIX 20200626 - 20200626 don't have data
 CGIX 20200724 - 20200724 don't have data
 CGIX 20200630 - 20200630 don't have data
 CGIX 20200727 - 20200727 don't have data
 CGIX 20200701 - 20200701 don't have data
 CGIX 20200729 - 20200729 don't have data
 CGIX 20200706 - 20200706 don't have data
 CGIX 20200730 - 20200730 don't have data
 CGIX 20200707 - 20200707 don't have data
 CGIX 20200803 - 20200803 don't have data
 CGIX 20200709 - 20200709 don't have data
 CGIX 20200804 - 20200804 don't have data
 CGIX 20200710 - 20200710 don't have data
 CGIX 20200806 - 20200806 don't have data
 CGIX 20200714 - 20200714 don't have data
 CGIX 20200807 - 20200807 don't have data
 CGIX 20200715 - 20200715 don't have data
 CGIX 20200811 - 20200811 don't have data
 CGIX 20200717 - 20200717 don't have data
 CGIX 20200812 - 20200812 don't have data
 CGIX 20200720 - 20200720 don't have data
 CGIX 20200814 - 20200814 don't have data
 CGIX 20200723 - 20200723 don't have data
 CGIX 20200819 - 20200819 don't have data
 CGIX 20200728 - 20200728 don't have data
 CGIX 20200824 - 20200824 don't have data
 CGIX 20200731 - 20200731 don't have data
 CGIX 20200826 - 20200826 don't have data
 CGIX 20200805 - 20200805 don't have data
 CGIX 20200827 - 20200827 don't have data
 CGIX 20200810 - 20200810 don't have data
 CGIX 20200831 - 20200831 don't have data
 CGIX 20200813 - 20200813 don't have data
 CGIX 20200901 - 20200901 don't have data
 CGIX 20200817 - 20200817 don't have data
 CGIX 20200903 - 20200903 don't have data
 CGIX 20200818 - 20200818 don't have data
 CGIX 20200909 - 20200909 don't have data
 CGIX 20200820 - 20200820 don't have data
 CGIX 20200914 - 20200914 don't have data
 CGIX 20200821 - 20200821 don't have data
 CGIX 20200917 - 20200917 don't have data
 CGIX 20200825 - 20200825 don't have data
 CGIX 20200921 - 20200921 don't have data
 CGIX 20200828 - 20200828 don't have data
 CGIX 20200922 - 20200922 don't have data
 CGIX 20200902 - 20200902 don't have data
 CGIX 20200924 - 20200924 don't have data
 CGIX 20200904 - 20200904 don't have data
 CGIX 20200925 - 20200925 don't have data
 CGIX 20200908 - 20200908 don't have data
 CGIX 20200929 - 20200929 don't have data
 CGIX 20200910 - 20200910 don't have data
 CGIX 20200930 - 20200930 don't have data
 CGIX 20200911 - 20200911 don't have data
 CGIX 20201002 - 20201002 don't have data
 CGIX 20200915 - 20200915 don't have data
 CGIX 20201007 - 20201007 don't have data
 CGIX 20200916 - 20200916 don't have data
 CGIX 20201008 - 20201008 don't have data
 CGIX 20200918 - 20200918 don't have data
 CGIX 20201012 - 20201012 don't have data
 CGIX 20200923 - 20200923 don't have data
 CGIX 20201015 - 20201015 don't have data
 CGIX 20200928 - 20200928 don't have data
 CGIX 20201016 - 20201016 don't have data
 CGIX 20201001 - 20201001 don't have data
 CGIX 20201020 - 20201020 don't have data
 CGIX 20201005 - 20201005 don't have data
 CGIX 20201023 - 20201023 don't have data
 CGIX 20201006 - 20201006 don't have data
 CGIX 20201028 - 20201028 don't have data
 CGIX 20201009 - 20201009 don't have data
 CGIX 20201013 - 20201013 don't have data
 CGIX 20201102 - 20201102 don't have data
 CGIX 20201014 - 20201014 don't have data
 CGIX 20201105 - 20201105 don't have data
 CGIX 20201019 - 20201019 don't have data
 CGIX 20201110 - 20201110 don't have data
 CGIX 20201021 - 20201021 don't have data
 CGIX 20201111 - 20201111 don't have data
 CGIX 20201022 - 20201022 don't have data
 CGIX 20201113 - 20201113 don't have data
 CGIX 20201026 - 20201026 don't have data
 CGIX 20201118 - 20201118 don't have data
 CGIX 20201027 - 20201027 don't have data
 CGIX 20201119 - 20201119 don't have data
 CGIX 20201029 - 20201029 don't have data
 CGIX 20201123 - 20201123 don't have data
 CGIX 20201030 - 20201030 don't have data
 CGIX 20201127 - 20201127 don't have data
 CGIX 20201103 - 20201103 don't have data
 CGIX 20201130 - 20201130 don't have data
 CGIX 20201104 - 20201104 don't have data
 CGIX 20201106 - 20201106 don't have data
 CGIX 20201202 - 20201202 don't have data
 CGIX 20201109 - 20201109 don't have data
 CGIX 20201203 - 20201203 don't have data
 CGIX 20201112 - 20201112 don't have data
 CGIX 20201208 - 20201208 don't have data
 CGIX 20201116 - 20201116 don't have data
 CGIX 20201210 - 20201210 don't have data
 CGIX 20201117 - 20201117 don't have data
 CGIX 20201211 - 20201211 don't have data
 CGIX 20201120 - 20201120 don't have data
 CGIX 20201216 - 20201216 don't have data
 CGIX 20201124 - 20201124 don't have data
 CGIX 20201217 - 20201217 don't have data
 CGIX 20201125 - 20201125 don't have data
 CGIX 20201221 - 20201221 don't have data
 CGIX 20201201 - 20201201 don't have data
 CGIX 20201204 - 20201204 don't have data
 CGIX 20201224 - 20201224 don't have data
 CGIX 20201207 - 20201207 don't have data
 CGIX 20201230 - 20201230 don't have data
 CGIX 20201209 - 20201209 don't have data
 CGIX 20201214 - 20201214 don't have data
 CGIX 20201215 - 20201215 don't have data
 CGIX 20201218 - 20201218 don't have data
 CGIX 20201222 - 20201222 don't have data
 CGIX 20201223 - 20201223 don't have data
 CGIX 20201228 - 20201228 don't have data
 CGIX 20201229 - 20201229 don't have data
 CGIX 20201231 - 20201231 don't have data

  0%|          | 0/253 [00:00<?, ?it/s]

  0%|          | 0/253 [00:00<?, ?it/s]

  0%|          | 0/253 [00:00<?, ?it/s]

  0%|          | 0/253 [00:00<?, ?it/s]

  0%|          | 0/253 [00:00<?, ?it/s]

  0%|          | 0/253 [00:00<?, ?it/s]

  0%|          | 0/253 [00:00<?, ?it/s]

 VGSH 20200106 - 20200106 don't have data
 VGSH 20200102 - 20200102 don't have data
 VGSH 20200109 - 20200109 don't have data
 VGSH 20200107 - 20200107 don't have data
 VGSH 20200103 - 20200103 don't have data
 VGSH 20200110 - 20200110 don't have data
 VGSH 20200113 - 20200113 don't have data
 VGSH 20200108 - 20200108 don't have data
 VGSH 20200116 - 20200116 don't have data
 VGSH 20200114 - 20200114 don't have data
 VGSH 20200121 - 20200121 don't have data
 VGSH 20200122 - 20200122 don't have data
 VGSH 20200115 - 20200115 don't have data
 VGSH 20200123 - 20200123 don't have data
 VGSH 20200117 - 20200117 don't have data
 VGSH 20200128 - 20200128 don't have data
 VGSH 20200124 - 20200124 don't have data
 VGSH 20200131 - 20200131 don't have data
 VGSH 20200205 - 20200205 don't have data
 VGSH 20200127 - 20200127 don't have data
 VGSH 20200129 - 20200129 don't have data
 VGSH 20200130 - 20200130 don't have data
 VGSH 20200207 - 20200207 don't have data
 VGSH 20200203 - 20200203 don't have data
 VGSH 20200210 - 20200210 don't have data
 VGSH 20200204 - 20200204 don't have data
 VGSH 20200212 - 20200212 don't have data
 VGSH 20200206 - 20200206 don't have data
 VGSH 20200213 - 20200213 don't have data
 VGSH 20200211 - 20200211 don't have data
 VGSH 20200218 - 20200218 don't have data
 VGSH 20200214 - 20200214 don't have data
 VGSH 20200221 - 20200221 don't have data
 VGSH 20200219 - 20200219 don't have data
 VGSH 20200225 - 20200225 don't have data
 VGSH 20200220 - 20200220 don't have data
 VGSH 20200226 - 20200226 don't have data
 VGSH 20200224 - 20200224 don't have data
 VGSH 20200228 - 20200228 don't have data
 VGSH 20200227 - 20200227 don't have data
 VGSH 20200304 - 20200304 don't have data
 VGSH 20200302 - 20200302 don't have data
 VGSH 20200309 - 20200309 don't have data
 VGSH 20200303 - 20200303 don't have data
 VGSH 20200311 - 20200311 don't have data
 VGSH 20200305 - 20200305 don't have data
 VGSH 20200316 - 20200316 don't have data
 VGSH 20200306 - 20200306 don't have data
 VGSH 20200319 - 20200319 don't have data
 VGSH 20200310 - 20200310 don't have data
 VGSH 20200324 - 20200324 don't have data
 VGSH 20200312 - 20200312 don't have data
 VGSH 20200326 - 20200326 don't have data
 VGSH 20200313 - 20200313 don't have data
 VGSH 20200327 - 20200327 don't have data
 VGSH 20200317 - 20200317 don't have data
 VGSH 20200331 - 20200331 don't have data
 VGSH 20200318 - 20200318 don't have data
 VGSH 20200401 - 20200401 don't have data
 VGSH 20200320 - 20200320 don't have data
 VGSH 20200403 - 20200403 don't have data
 VGSH 20200323 - 20200323 don't have data
 VGSH 20200406 - 20200406 don't have data
 VGSH 20200325 - 20200325 don't have data
 VGSH 20200408 - 20200408 don't have data
 VGSH 20200330 - 20200330 don't have data
 VGSH 20200409 - 20200409 don't have data
 VGSH 20200402 - 20200402 don't have data
 VGSH 20200414 - 20200414 don't have data
 VGSH 20200407 - 20200407 don't have data
 VGSH 20200417 - 20200417 don't have data
 VGSH 20200413 - 20200413 don't have data
 VGSH 20200422 - 20200422 don't have data
 VGSH 20200415 - 20200415 don't have data
 VGSH 20200427 - 20200427 don't have data
 VGSH 20200416 - 20200416 don't have data
 VGSH 20200428 - 20200428 don't have data
 VGSH 20200420 - 20200420 don't have data
 VGSH 20200430 - 20200430 don't have data
 VGSH 20200421 - 20200421 don't have data
 VGSH 20200505 - 20200505 don't have data
 VGSH 20200423 - 20200423 don't have data
 VGSH 20200508 - 20200508 don't have data
 VGSH 20200424 - 20200424 don't have data
 VGSH 20200512 - 20200512 don't have data
 VGSH 20200429 - 20200429 don't have data
 VGSH 20200513 - 20200513 don't have data
 VGSH 20200501 - 20200501 don't have data
 VGSH 20200515 - 20200515 don't have data
 VGSH 20200504 - 20200504 don't have data
 VGSH 20200520 - 20200520 don't have data
 VGSH 20200506 - 20200506 don't have data
 VGSH 20200521 - 20200521 don't have data
 VGSH 20200526 - 20200526 don't have data
 VGSH 20200507 - 20200507 don't have data
 VGSH 20200529 - 20200529 don't have data
 VGSH 20200511 - 20200511 don't have data
 VGSH 20200602 - 20200602 don't have data
 VGSH 20200514 - 20200514 don't have data
 VGSH 20200603 - 20200603 don't have data
 VGSH 20200518 - 20200518 don't have data
 VGSH 20200519 - 20200519 don't have data
 VGSH 20200522 - 20200522 don't have data
 VGSH 20200527 - 20200527 don't have data
 VGSH 20200528 - 20200528 don't have data
 VGSH 20200601 - 20200601 don't have data
 VGSH 20200604 - 20200604 don't have data
 VGSH 20200605 - 20200605 don't have data

  0%|          | 0/253 [00:00<?, ?it/s]

 CYRN 20200103 - 20200103 don't have data
 CYRN 20200102 - 20200102 don't have data
 CYRN 20200107 - 20200107 don't have data
 CYRN 20200106 - 20200106 don't have data
 CYRN 20200108 - 20200108 don't have data
 CYRN 20200110 - 20200110 don't have data
 CYRN 20200109 - 20200109 don't have data
 CYRN 20200113 - 20200113 don't have data
 CYRN 20200114 - 20200114 don't have data
 CYRN 20200115 - 20200115 don't have data
 CYRN 20200116 - 20200116 don't have data
 CYRN 20200117 - 20200117 don't have data
 CYRN 20200121 - 20200121 don't have data
 CYRN 20200122 - 20200122 don't have data
 CYRN 20200123 - 20200123 don't have data
 CYRN 20200124 - 20200124 don't have data
 CYRN 20200127 - 20200127 don't have data
 CYRN 20200128 - 20200128 don't have data
 CYRN 20200129 - 20200129 don't have data
 CYRN 20200203 - 20200203 don't have data
 CYRN 20200130 - 20200130 don't have data
 CYRN 20200204 - 20200204 don't have data
 CYRN 20200131 - 20200131 don't have data
 CYRN 20200206 - 20200206 don't have data
 CYRN 20200205 - 20200205 don't have data
 CYRN 20200211 - 20200211 don't have data
 CYRN 20200207 - 20200207 don't have data
 CYRN 20200213 - 20200213 don't have data
 CYRN 20200210 - 20200210 don't have data
 CYRN 20200214 - 20200214 don't have data
 CYRN 20200212 - 20200212 don't have data
 CYRN 20200219 - 20200219 don't have data
 CYRN 20200218 - 20200218 don't have data
 CYRN 20200220 - 20200220 don't have data
 CYRN 20200224 - 20200224 don't have data
 CYRN 20200221 - 20200221 don't have data
 CYRN 20200227 - 20200227 don't have data
 CYRN 20200225 - 20200225 don't have data
 CYRN 20200302 - 20200302 don't have data
 CYRN 20200226 - 20200226 don't have data
 CYRN 20200303 - 20200303 don't have data
 CYRN 20200228 - 20200228 don't have data
 CYRN 20200305 - 20200305 don't have data
 CYRN 20200304 - 20200304 don't have data
 CYRN 20200310 - 20200310 don't have data
 CYRN 20200306 - 20200306 don't have data
 CYRN 20200312 - 20200312 don't have data
 CYRN 20200309 - 20200309 don't have data
 CYRN 20200313 - 20200313 don't have data
 CYRN 20200311 - 20200311 don't have data
 CYRN 20200317 - 20200317 don't have data
 CYRN 20200316 - 20200316 don't have data
 CYRN 20200320 - 20200320 don't have data
 CYRN 20200318 - 20200318 don't have data
 CYRN 20200325 - 20200325 don't have data
 CYRN 20200319 - 20200319 don't have data
 CYRN 20200327 - 20200327 don't have data
 CYRN 20200330 - 20200330 don't have data
 CYRN 20200323 - 20200323 don't have data
 CYRN 20200401 - 20200401 don't have data
 CYRN 20200324 - 20200324 don't have data
 CYRN 20200406 - 20200406 don't have data
 CYRN 20200326 - 20200326 don't have data
 CYRN 20200409 - 20200409 don't have data
 CYRN 20200331 - 20200331 don't have data
 CYRN 20200414 - 20200414 don't have data
 CYRN 20200402 - 20200402 don't have data
 CYRN 20200415 - 20200415 don't have data
 CYRN 20200417 - 20200417 don't have data
 CYRN 20200403 - 20200403 don't have data
 CYRN 20200420 - 20200420 don't have data
 CYRN 20200407 - 20200407 don't have data
 CYRN 20200422 - 20200422 don't have data
 CYRN 20200408 - 20200408 don't have data
 CYRN 20200423 - 20200423 don't have data
 CYRN 20200427 - 20200427 don't have data
 CYRN 20200413 - 20200413 don't have data
 CYRN 20200428 - 20200428 don't have data
 CYRN 20200416 - 20200416 don't have data
 CYRN 20200430 - 20200430 don't have data
 CYRN 20200421 - 20200421 don't have data
 CYRN 20200501 - 20200501 don't have data
 CYRN 20200424 - 20200424 don't have data
 CYRN 20200505 - 20200505 don't have data
 CYRN 20200429 - 20200429 don't have data
 CYRN 20200506 - 20200506 don't have data
 CYRN 20200504 - 20200504 don't have data
 CYRN 20200511 - 20200511 don't have data
 CYRN 20200507 - 20200507 don't have data
 CYRN 20200513 - 20200513 don't have data
 CYRN 20200508 - 20200508 don't have data
 CYRN 20200514 - 20200514 don't have data
 CYRN 20200519 - 20200519 don't have data
 CYRN 20200512 - 20200512 don't have data
 CYRN 20200522 - 20200522 don't have data
 CYRN 20200515 - 20200515 don't have data
 CYRN 20200527 - 20200527 don't have data
 CYRN 20200518 - 20200518 don't have data
 CYRN 20200528 - 20200528 don't have data
 CYRN 20200520 - 20200520 don't have data
 CYRN 20200602 - 20200602 don't have data
 CYRN 20200521 - 20200521 don't have data
 CYRN 20200604 - 20200604 don't have data
 CYRN 20200526 - 20200526 don't have data
 CYRN 20200605 - 20200605 don't have data
 CYRN 20200529 - 20200529 don't have data
 CYRN 20200609 - 20200609 don't have data
 CYRN 20200601 - 20200601 don't have data
 CYRN 20200610 - 20200610 don't have data
 CYRN 20200603 - 20200603 don't have data
 CYRN 20200612 - 20200612 don't have data
 CYRN 20200615 - 20200615 don't have data
 CYRN 20200608 - 20200608 don't have data
 CYRN 20200617 - 20200617 don't have data
 CYRN 20200611 - 20200611 don't have data
 CYRN 20200618 - 20200618 don't have data
 CYRN 20200616 - 20200616 don't have data
 CYRN 20200623 - 20200623 don't have data
 CYRN 20200619 - 20200619 don't have data
 CYRN 20200625 - 20200625 don't have data
 CYRN 20200622 - 20200622 don't have data
 CYRN 20200626 - 20200626 don't have data
 CYRN 20200624 - 20200624 don't have data
 CYRN 20200701 - 20200701 don't have data
 CYRN 20200629 - 20200629 don't have data
 CYRN 20200707 - 20200707 don't have data
 CYRN 20200630 - 20200630 don't have data
 CYRN 20200708 - 20200708 don't have data
 CYRN 20200702 - 20200702 don't have data
 CYRN 20200710 - 20200710 don't have data
 CYRN 20200706 - 20200706 don't have data
 CYRN 20200715 - 20200715 don't have data
 CYRN 20200709 - 20200709 don't have data
 CYRN 20200716 - 20200716 don't have data
 CYRN 20200713 - 20200713 don't have data
 CYRN 20200721 - 20200721 don't have data
 CYRN 20200714 - 20200714 don't have data
 CYRN 20200723 - 20200723 don't have data
 CYRN 20200724 - 20200724 don't have data
 CYRN 20200717 - 20200717 don't have data
 CYRN 20200729 - 20200729 don't have data
 CYRN 20200720 - 20200720 don't have data
 CYRN 20200803 - 20200803 don't have data
 CYRN 20200722 - 20200722 don't have data
 CYRN 20200806 - 20200806 don't have data
 CYRN 20200727 - 20200727 don't have data
 CYRN 20200811 - 20200811 don't have data
 CYRN 20200728 - 20200728 don't have data
 CYRN 20200814 - 20200814 don't have data
 CYRN 20200730 - 20200730 don't have data
 CYRN 20200819 - 20200819 don't have data
 CYRN 20200731 - 20200731 don't have data
 CYRN 20200824 - 20200824 don't have data
 CYRN 20200804 - 20200804 don't have data
 CYRN 20200825 - 20200825 don't have data
 CYRN 20200805 - 20200805 don't have data
 CYRN 20200827 - 20200827 don't have data
 CYRN 20200807 - 20200807 don't have data
 CYRN 20200901 - 20200901 don't have data
 CYRN 20200810 - 20200810 don't have data
 CYRN 20200904 - 20200904 don't have data
 CYRN 20200812 - 20200812 don't have data
 CYRN 20200910 - 20200910 don't have data
 CYRN 20200813 - 20200813 don't have data
 CYRN 20200915 - 20200915 don't have data
 CYRN 20200817 - 20200817 don't have data
 CYRN 20200918 - 20200918 don't have data
 CYRN 20200818 - 20200818 don't have data
 CYRN 20200922 - 20200922 don't have data
 CYRN 20200923 - 20200923 don't have data
 CYRN 20200820 - 20200820 don't have data
 CYRN 20200928 - 20200928 don't have data
 CYRN 20200821 - 20200821 don't have data
 CYRN 20201001 - 20201001 don't have data
 CYRN 20200826 - 20200826 don't have data
 CYRN 20201006 - 20201006 don't have data
 CYRN 20200828 - 20200828 don't have data
 CYRN 20201009 - 20201009 don't have data
 CYRN 20200831 - 20200831 don't have data
 CYRN 20201014 - 20201014 don't have data
 CYRN 20201019 - 20201019 don't have data
 CYRN 20200902 - 20200902 don't have data
 CYRN 20200903 - 20200903 don't have data
 CYRN 20201022 - 20201022 don't have data
 CYRN 20200908 - 20200908 don't have data
 CYRN 20201026 - 20201026 don't have data
 CYRN 20200909 - 20200909 don't have data
 CYRN 20201027 - 20201027 don't have data
 CYRN 20200911 - 20200911 don't have data
 CYRN 20201028 - 20201028 don't have data
 CYRN 20201030 - 20201030 don't have data
 CYRN 20200914 - 20200914 don't have data
 CYRN 20201102 - 20201102 don't have data
 CYRN 20200916 - 20200916 don't have data
 CYRN 20201104 - 20201104 don't have data
 CYRN 20200917 - 20200917 don't have data
 CYRN 20201105 - 20201105 don't have data
 CYRN 20200921 - 20200921 don't have data
 CYRN 20201110 - 20201110 don't have data
 CYRN 20201113 - 20201113 don't have data
 CYRN 20200924 - 20200924 don't have data
 CYRN 20201116 - 20201116 don't have data
 CYRN 20200925 - 20200925 don't have data
 CYRN 20201118 - 20201118 don't have data
 CYRN 20200929 - 20200929 don't have data
 CYRN 20201123 - 20201123 don't have data
 CYRN 20200930 - 20200930 don't have data
 CYRN 20201124 - 20201124 don't have data
 CYRN 20201002 - 20201002 don't have data
 CYRN 20201127 - 20201127 don't have data
 CYRN 20201005 - 20201005 don't have data
 CYRN 20201130 - 20201130 don't have data
 CYRN 20201007 - 20201007 don't have data
 CYRN 20201202 - 20201202 don't have data
 CYRN 20201008 - 20201008 don't have data
 CYRN 20201207 - 20201207 don't have data
 CYRN 20201012 - 20201012 don't have data
 CYRN 20201208 - 20201208 don't have data
 CYRN 20201210 - 20201210 don't have data
 CYRN 20201013 - 20201013 don't have data
 CYRN 20201215 - 20201215 don't have data
 CYRN 20201015 - 20201015 don't have data
 CYRN 20201216 - 20201216 don't have data
 CYRN 20201016 - 20201016 don't have data
 CYRN 20201218 - 20201218 don't have data
 CYRN 20201020 - 20201020 don't have data
 CYRN 20201221 - 20201221 don't have data
 CYRN 20201021 - 20201021 don't have data
 CYRN 20201222 - 20201222 don't have data
 CYRN 20201023 - 20201023 don't have data
 CYRN 20201224 - 20201224 don't have data
 CYRN 20201029 - 20201029 don't have data
 CYRN 20201230 - 20201230 don't have data
 CYRN 20201103 - 20201103 don't have data
 CYRN 20201231 - 20201231 don't have data
 CYRN 20201106 - 20201106 don't have data
 CYRN 20201109 - 20201109 don't have data
 CYRN 20201111 - 20201111 don't have data
 CYRN 20201112 - 20201112 don't have data
 CYRN 20201117 - 20201117 don't have data
 CYRN 20201119 - 20201119 don't have data
 CYRN 20201120 - 20201120 don't have data
 CYRN 20201125 - 20201125 don't have data
 CYRN 20201201 - 20201201 don't have data
 CYRN 20201203 - 20201203 don't have data
 CYRN 20201204 - 20201204 don't have data
 CYRN 20201209 - 20201209 don't have data
 CYRN 20201211 - 20201211 don't have data
 CYRN 20201214 - 20201214 don't have data
 CYRN 20201217 - 20201217 don't have data
 CYRN 20201223 - 20201223 don't have data
 CYRN 20201228 - 20201228 don't have data
 CYRN 20201229 - 20201229 don't have data

  0%|          | 0/253 [00:00<?, ?it/s]

 MDCA 20200103 - 20200103 don't have data
 MDCA 20200102 - 20200102 don't have data
 MDCA 20200106 - 20200106 don't have data
 MDCA 20200107 - 20200107 don't have data
 MDCA 20200108 - 20200108 don't have data
 MDCA 20200109 - 20200109 don't have data
 MDCA 20200110 - 20200110 don't have data
 MDCA 20200113 - 20200113 don't have data
 MDCA 20200114 - 20200114 don't have data
 MDCA 20200116 - 20200116 don't have data
 MDCA 20200115 - 20200115 don't have data
 MDCA 20200117 - 20200117 don't have data
 MDCA 20200121 - 20200121 don't have data
 MDCA 20200124 - 20200124 don't have data
 MDCA 20200122 - 20200122 don't have data
 MDCA 20200127 - 20200127 don't have data
 MDCA 20200123 - 20200123 don't have data
 MDCA 20200129 - 20200129 don't have data
 MDCA 20200128 - 20200128 don't have data
 MDCA 20200131 - 20200131 don't have data
 MDCA 20200130 - 20200130 don't have data
 MDCA 20200204 - 20200204 don't have data
 MDCA 20200203 - 20200203 don't have data
 MDCA 20200206 - 20200206 don't have data
 MDCA 20200205 - 20200205 don't have data
 MDCA 20200211 - 20200211 don't have data
 MDCA 20200207 - 20200207 don't have data
 MDCA 20200214 - 20200214 don't have data
 MDCA 20200210 - 20200210 don't have data
 MDCA 20200219 - 20200219 don't have data
 MDCA 20200212 - 20200212 don't have data
 MDCA 20200220 - 20200220 don't have data
 MDCA 20200213 - 20200213 don't have data
 MDCA 20200224 - 20200224 don't have data
 MDCA 20200218 - 20200218 don't have data
 MDCA 20200227 - 20200227 don't have data
 MDCA 20200221 - 20200221 don't have data
 MDCA 20200302 - 20200302 don't have data
 MDCA 20200225 - 20200225 don't have data
 MDCA 20200303 - 20200303 don't have data
 MDCA 20200226 - 20200226 don't have data
 MDCA 20200305 - 20200305 don't have data
 MDCA 20200228 - 20200228 don't have data
 MDCA 20200304 - 20200304 don't have data
 MDCA 20200306 - 20200306 don't have data

  0%|          | 0/253 [00:00<?, ?it/s]

  0%|          | 0/253 [00:00<?, ?it/s]

  0%|          | 0/253 [00:00<?, ?it/s]

  0%|          | 0/253 [00:00<?, ?it/s]

  0%|          | 0/253 [00:00<?, ?it/s]

  0%|          | 0/253 [00:00<?, ?it/s]

  0%|          | 0/253 [00:00<?, ?it/s]

# Update EOD options

In [18]:
def get_option_eod(t: str, start_date: str, end_date: str):
    if end_date < '20160101':
        return None
        
    params = {
        'root': t, 'exp': 0,
        'start_date': start_date, 'end_date': end_date,  
        'use_csv': 'True'
    }
    ans, status_code = make_request('bulk_hist', 'option', 'eod', params)
    
    if status_code == 472:
        print(f"\033[1;91m {t} {start_date} - {end_date} don't have data \033[0m")
        return None
    elif status_code == 572:
        print(f"\033[1;91m {t} an error \033[0m")
        return None
    
    ans_df = pl.read_csv(StringIO(ans)).with_columns(pl.lit(t).alias('ticker'))
    
    return ans_df

In [25]:
with open('data/all_tickers_expir.pickle', 'rb') as f:
    tickers_all_exp = pickle.load(f)

need_year: str = '2024'
already_tickers = [file for file in os.listdir('data/options') if (need_year in file)][::-1]

already_tickers = [t for t in already_tickers if 'SPY_' in t] 

for ticker_file in tqdm(already_tickers):
    start_date = ticker_file.split('_')[0]
    end_date = ticker_file.split('_')[1]
    ticker = ticker_file.split('_')[2]

    # Find tickers without updates 
    if ticker in tickers_all_exp.keys():
        need_dates = pd.Series(
            tickers_all_exp[ticker]['trade_dates'],
            tickers_all_exp[ticker]['trade_dates']
        )[f'{need_year}0101':]
        
        earlest_dates = need_dates[:start_date][:-1]
        latest_dates = need_dates[end_date:][1:]
        if (len(earlest_dates) != 0) or (len(latest_dates) != 0):
            need_dates = pd.concat([earlest_dates, latest_dates])
        else:
            need_dates = None
        expirations = tickers_all_exp[ticker]['expirations']

    else:
        need_dates = pd.Series(
            tickers_all_exp['SPY']['trade_dates'],
            tickers_all_exp['SPY']['trade_dates']
        )[f'{need_year}0101':]
        
        earlest_dates = need_dates[:start_date][:-1]
        latest_dates = need_dates[end_date:][1:]
        if (len(earlest_dates) != 0) or (len(latest_dates) != 0):
            need_dates = pd.concat([earlest_dates, latest_dates])
        else:
            need_dates = None
        expirations = tickers_all_exp['SPY']['expirations']

    if need_dates is None:
        continue
        
    interseс = set(need_dates.values) & set(pd.Series(expirations).astype(str))
    if len(interseс) == 0:
        continue

    # Load new data
    final_df = pl.DataFrame()   
    with ThreadPoolExecutor(max_workers=24) as executor:
        futures = {
            executor.submit(get_option_eod, ticker, start, end): 
            (ticker, start, end) for start, end in zip(need_dates, need_dates)
        }
        for future in tqdm(as_completed(futures), total=len(need_dates)):
            try:
                cur_df = future.result()
                if (cur_df is None) or len(cur_df) == 0: 
                    continue
                final_df = pl.concat([final_df, cur_df])
            except Exception as e:
                print(cur_df)
                print(e)
                raise Exception
    try:
        if (final_df is None) or len(final_df) == 0: 
            continue
        final_df = final_df.sort('date', 'expiration', 'right', 'strike')\
            .with_columns(pl.col('date').cast(pl.String).str.strptime(pl.Date, '%Y%m%d', strict=False))\
            .unique(subset=['expiration', 'date', 'right', 'strike'])
        load_df = pl.read_parquet(f'data/options/{ticker_file}')
        final_df = pl.concat([final_df, load_df])

        for year in final_df['date'].dt.year().unique():
            cur_df = final_df.filter(pl.col('date').dt.year() == year)\
                .unique(subset=['expiration', 'date', 'right', 'strike'])
            min_date = cur_df['date'].min().strftime('%Y%m%d')
            max_date = cur_df['date'].max().strftime('%Y%m%d')

            cur_df.write_parquet(f'data/options/{min_date}_{max_date}_{ticker}_opts.parquet')
            
        os.remove(f'data/options/{ticker_file}')
        
    except Exception as e:
        print(final_df)
        print(load_df)
        print(e)
        raise Exception

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/43 [00:00<?, ?it/s]

# Update 1m stocks

In [3]:
def get_stock_1m(t: str, start_date: str, end_date: str):
    if end_date < '20160101':
        return None
        
    print(start_date, end_date)
    params = {
        'root': t, 'exp': 0,
        'start_date': start_date, 'end_date': end_date,  
        'use_csv': 'True', 'ivl': '60000'
    }
    ans, status_code = make_request('hist', 'stock', 'ohlc', params)
    
    if status_code == 472:
        print(f"\033[1;91m {t} {start_date} - {end_date} don't have data \033[0m")
        return None
    elif status_code == 572:
        print(f"\033[1;91m {t} an error \033[0m")
        return None
    
    ans_df = pl.read_csv(StringIO(ans)).with_columns(pl.lit(t).alias('ticker'))
    
    return ans_df

In [7]:
start_range = '20160101'
end_range = datetime.datetime.now().strftime('%Y%m%d')

weekly_start = list(pd.date_range(start_range, end_range, freq='W-MON').strftime('%Y%m%d')[::-1])
weekly_end = list(pd.date_range(start_range, end_range, freq='W-SUN').strftime('%Y%m%d')[::-1])
weekly_end.extend([end_range])
weekly_end = np.sort(weekly_end)[::-1]

with open('data/all_tickers_expir.pickle', 'rb') as f:
    tickers_all_exp = pickle.load(f)

already_tickers = [file for file in os.listdir('data/stocks/m1')][::-1]

    
need_tickers = ['SPY', 'GLD', 'IWM', 'QQQ', 'SLV', 'TLT', 'UNG', 'USO']
# need_tickers = ['SPY']
for t in tqdm(need_tickers, total=len(need_tickers)):
    final_df = pl.DataFrame()    
    start_time = time.time()

    already_df = None
    cur_file = [file for file in already_tickers if f'{t}_' in file]
    if len(cur_file) > 1: 
        print(cur_file)
        raise Exception
    elif len(cur_file) == 1: 
        cur_file = cur_file[0]
        already_df = pl.read_parquet(f'data/stocks/m1/{cur_file}')

        cur_w_start = [w for w in weekly_start if int(w) > already_df['date'].max()]
        cur_w_end = [w for w in weekly_end if int(w) > already_df['date'].max()]
        add_start = (pd.to_datetime(already_df['date'].max(), format='%Y%m%d') + pd.Timedelta(days=1)).strftime('%Y%m%d')
        add_end = (pd.to_datetime(cur_w_end[-1]) - pd.Timedelta(days=1)).strftime('%Y%m%d')
        cur_w_start.append(add_start)
        cur_w_end.append(add_end)
    else:
        cur_w_start = weekly_start
        cur_w_end = weekly_end

    # count = 0
    with ThreadPoolExecutor(max_workers=24) as executor:
        futures = {
            executor.submit(get_stock_1m, t, cur_s, cur_e): 
            (t, cur_s, cur_e) for cur_s, cur_e in zip(cur_w_start, cur_w_end)
        }
        for future in tqdm(as_completed(futures), total=len(cur_w_start)):
            cur_df = future.result()
            if cur_df is None: 
                continue
            final_df = pl.concat([final_df, cur_df])

            if len(final_df) == 0:
                count = 0
                continue

            # count += 1
            # if count > 10:
            #     final_df = final_df.sort('date')
            #     final_df.write_parquet(f'data/stocks/{start_range}_{end_range}_{t}_opts.parquet')
            #     count = 0

    if already_df is None:
        final_df = final_df.sort('date')
    else:
        final_df = pl.concat([already_df, final_df]).sort('date', 'ms_of_day')
    final_df.write_parquet(f'data/stocks/m1/{start_range}_{end_range}_{t}_opts.parquet')

  0%|          | 0/8 [00:00<?, ?it/s]

['20160101_20250326_SPY_opts.parquet', '20160101_20250127_SPY_opts.parquet']

Exception:

# Update 1m Options

In [3]:
ticker: str = 'SPY'

In [4]:
with open('data/all_tickers_expir.pickle', 'rb') as f:
    tickers_all_exp = pickle.load(f)

expirs = pd.Series(data=tickers_all_exp[ticker]['expirations'], index=tickers_all_exp[ticker]['expirations'])
min_date = tickers_all_exp[ticker]['trade_dates'][0]
max_date = tickers_all_exp[ticker]['trade_dates'][-1]
expirs = expirs.loc[min_date:max_date]

expirs = pd.DataFrame(expirs, columns=['expir'])
expirs['expir'] = expirs['expir'].astype(str)
expirs['ticker'] = ticker

expirs['dayOfWeek'] = pd.to_datetime(expirs['expir']).dt.dayofweek
expirs = expirs[~expirs['dayOfWeek'].isin([5, 6])]

expirs.groupby('dayOfWeek').agg(cnt=('ticker', 'count')).sort_index()

           cnt
dayOfWeek
0          235
1          131
2          261
3          121
4          256